// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	Token
	RevokeTokenRequest
	RevokeTokenResponse
	PruneTokensRequest
	PruneTokensResponse
	ID
	GetLoginRequest
	GetLoginResponse
	CreateLoginRequest
	CreateLoginResponse
	AcceptLoginRequest
	AcceptLoginResponse
	GetConsentRequest
	GetConsentResponse
	CreateConsentRequest
	CreateConsentResponse
	AcceptConsentRequest
	AcceptConsentResponse
	CreateLogoutRequest
	CreateLogoutResponse
	AcceptLogoutRequest
	AcceptLogoutResponse
	CreateAuthCodeRequest
	CreateAuthCodeResponse
	VerifyTokenRequest
	VerifyTokenResponse
	ExchangeRequest
	ExchangeResponse
	RefreshTokenRequest
	RefreshTokenResponse
	PersonalAccessToken
	PatGenerateRequest
	PatGenerateResponse
	PatListRequest
	PatListResponse
	PatRevokeRequest
	PatRevokeResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PatType int32

const (
	PatType_ANY      PatType = 0
	PatType_PERSONAL PatType = 1
	PatType_DOCUMENT PatType = 2
)

var PatType_name = map[int32]string{
	0: "ANY",
	1: "PERSONAL",
	2: "DOCUMENT",
}
var PatType_value = map[string]int32{
	"ANY":      0,
	"PERSONAL": 1,
	"DOCUMENT": 2,
}

func (x PatType) String() string {
	return proto.EnumName(PatType_name, int32(x))
}
func (PatType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Token struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=AccessToken" json:"AccessToken,omitempty"`
	IDToken      string `protobuf:"bytes,2,opt,name=IDToken" json:"IDToken,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
	ExpiresAt    string `protobuf:"bytes,4,opt,name=ExpiresAt" json:"ExpiresAt,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetIDToken() string {
	if m != nil {
		return m.IDToken
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetExpiresAt() string {
	if m != nil {
		return m.ExpiresAt
	}
	return ""
}

type RevokeTokenRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *RevokeTokenRequest) Reset()                    { *m = RevokeTokenRequest{} }
func (m *RevokeTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*RevokeTokenRequest) ProtoMessage()               {}
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RevokeTokenRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type RevokeTokenResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *RevokeTokenResponse) Reset()                    { *m = RevokeTokenResponse{} }
func (m *RevokeTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*RevokeTokenResponse) ProtoMessage()               {}
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RevokeTokenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PruneTokensRequest struct {
}

func (m *PruneTokensRequest) Reset()                    { *m = PruneTokensRequest{} }
func (m *PruneTokensRequest) String() string            { return proto.CompactTextString(m) }
func (*PruneTokensRequest) ProtoMessage()               {}
func (*PruneTokensRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PruneTokensResponse struct {
	Tokens []string `protobuf:"bytes,1,rep,name=tokens" json:"tokens,omitempty"`
}

func (m *PruneTokensResponse) Reset()                    { *m = PruneTokensResponse{} }
func (m *PruneTokensResponse) String() string            { return proto.CompactTextString(m) }
func (*PruneTokensResponse) ProtoMessage()               {}
func (*PruneTokensResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PruneTokensResponse) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type ID struct {
	Challenge string `protobuf:"bytes,1,opt,name=Challenge" json:"Challenge,omitempty"`
	Verifier  string `protobuf:"bytes,2,opt,name=Verifier" json:"Verifier,omitempty"`
	CSRF      string `protobuf:"bytes,3,opt,name=CSRF" json:"CSRF,omitempty"`
}

func (m *ID) Reset()                    { *m = ID{} }
func (m *ID) String() string            { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()               {}
func (*ID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ID) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *ID) GetVerifier() string {
	if m != nil {
		return m.Verifier
	}
	return ""
}

func (m *ID) GetCSRF() string {
	if m != nil {
		return m.CSRF
	}
	return ""
}

type GetLoginRequest struct {
	Challenge string `protobuf:"bytes,1,opt,name=Challenge" json:"Challenge,omitempty"`
}

func (m *GetLoginRequest) Reset()                    { *m = GetLoginRequest{} }
func (m *GetLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLoginRequest) ProtoMessage()               {}
func (*GetLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetLoginRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

type GetLoginResponse struct {
	Challenge         string   `protobuf:"bytes,1,opt,name=Challenge" json:"Challenge,omitempty"`
	Subject           string   `protobuf:"bytes,2,opt,name=Subject" json:"Subject,omitempty"`
	SessionID         string   `protobuf:"bytes,3,opt,name=SessionID" json:"SessionID,omitempty"`
	RequestURL        string   `protobuf:"bytes,4,opt,name=RequestURL" json:"RequestURL,omitempty"`
	RequestedScope    []string `protobuf:"bytes,5,rep,name=RequestedScope" json:"RequestedScope,omitempty"`
	RequestedAudience []string `protobuf:"bytes,6,rep,name=RequestedAudience" json:"RequestedAudience,omitempty"`
	ClientID          string   `protobuf:"bytes,7,opt,name=ClientID" json:"ClientID,omitempty"`
}

func (m *GetLoginResponse) Reset()                    { *m = GetLoginResponse{} }
func (m *GetLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*GetLoginResponse) ProtoMessage()               {}
func (*GetLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetLoginResponse) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *GetLoginResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *GetLoginResponse) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *GetLoginResponse) GetRequestURL() string {
	if m != nil {
		return m.RequestURL
	}
	return ""
}

func (m *GetLoginResponse) GetRequestedScope() []string {
	if m != nil {
		return m.RequestedScope
	}
	return nil
}

func (m *GetLoginResponse) GetRequestedAudience() []string {
	if m != nil {
		return m.RequestedAudience
	}
	return nil
}

func (m *GetLoginResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type CreateLoginRequest struct {
	ClientID  string   `protobuf:"bytes,1,opt,name=ClientID" json:"ClientID,omitempty"`
	Scopes    []string `protobuf:"bytes,2,rep,name=Scopes" json:"Scopes,omitempty"`
	Audiences []string `protobuf:"bytes,3,rep,name=Audiences" json:"Audiences,omitempty"`
}

func (m *CreateLoginRequest) Reset()                    { *m = CreateLoginRequest{} }
func (m *CreateLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateLoginRequest) ProtoMessage()               {}
func (*CreateLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateLoginRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *CreateLoginRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *CreateLoginRequest) GetAudiences() []string {
	if m != nil {
		return m.Audiences
	}
	return nil
}

type CreateLoginResponse struct {
	Login *ID `protobuf:"bytes,1,opt,name=Login" json:"Login,omitempty"`
}

func (m *CreateLoginResponse) Reset()                    { *m = CreateLoginResponse{} }
func (m *CreateLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateLoginResponse) ProtoMessage()               {}
func (*CreateLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CreateLoginResponse) GetLogin() *ID {
	if m != nil {
		return m.Login
	}
	return nil
}

type AcceptLoginRequest struct {
	Challenge string `protobuf:"bytes,1,opt,name=Challenge" json:"Challenge,omitempty"`
	Verifier  string `protobuf:"bytes,2,opt,name=Verifier" json:"Verifier,omitempty"`
	Subject   string `protobuf:"bytes,3,opt,name=Subject" json:"Subject,omitempty"`
}

func (m *AcceptLoginRequest) Reset()                    { *m = AcceptLoginRequest{} }
func (m *AcceptLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*AcceptLoginRequest) ProtoMessage()               {}
func (*AcceptLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AcceptLoginRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *AcceptLoginRequest) GetVerifier() string {
	if m != nil {
		return m.Verifier
	}
	return ""
}

func (m *AcceptLoginRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

type AcceptLoginResponse struct {
}

func (m *AcceptLoginResponse) Reset()                    { *m = AcceptLoginResponse{} }
func (m *AcceptLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*AcceptLoginResponse) ProtoMessage()               {}
func (*AcceptLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type GetConsentRequest struct {
	Challenge string `protobuf:"bytes,1,opt,name=Challenge" json:"Challenge,omitempty"`
}

func (m *GetConsentRequest) Reset()                    { *m = GetConsentRequest{} }
func (m *GetConsentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConsentRequest) ProtoMessage()               {}
func (*GetConsentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetConsentRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

type GetConsentResponse struct {
	Challenge         string `protobuf:"bytes,1,opt,name=Challenge" json:"Challenge,omitempty"`
	LoginSessionID    string `protobuf:"bytes,2,opt,name=LoginSessionID" json:"LoginSessionID,omitempty"`
	SubjectIdentifier string `protobuf:"bytes,3,opt,name=SubjectIdentifier" json:"SubjectIdentifier,omitempty"`
	Subject           string `protobuf:"bytes,4,opt,name=Subject" json:"Subject,omitempty"`
	ClientID          string `protobuf:"bytes,5,opt,name=ClientID" json:"ClientID,omitempty"`
}

func (m *GetConsentResponse) Reset()                    { *m = GetConsentResponse{} }
func (m *GetConsentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetConsentResponse) ProtoMessage()               {}
func (*GetConsentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetConsentResponse) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *GetConsentResponse) GetLoginSessionID() string {
	if m != nil {
		return m.LoginSessionID
	}
	return ""
}

func (m *GetConsentResponse) GetSubjectIdentifier() string {
	if m != nil {
		return m.SubjectIdentifier
	}
	return ""
}

func (m *GetConsentResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *GetConsentResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type CreateConsentRequest struct {
	LoginChallenge string `protobuf:"bytes,1,opt,name=LoginChallenge" json:"LoginChallenge,omitempty"`
}

func (m *CreateConsentRequest) Reset()                    { *m = CreateConsentRequest{} }
func (m *CreateConsentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateConsentRequest) ProtoMessage()               {}
func (*CreateConsentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CreateConsentRequest) GetLoginChallenge() string {
	if m != nil {
		return m.LoginChallenge
	}
	return ""
}

type CreateConsentResponse struct {
	Consent *ID `protobuf:"bytes,1,opt,name=Consent" json:"Consent,omitempty"`
}

func (m *CreateConsentResponse) Reset()                    { *m = CreateConsentResponse{} }
func (m *CreateConsentResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateConsentResponse) ProtoMessage()               {}
func (*CreateConsentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CreateConsentResponse) GetConsent() *ID {
	if m != nil {
		return m.Consent
	}
	return nil
}

type AcceptConsentRequest struct {
	Challenge   string            `protobuf:"bytes,1,opt,name=Challenge" json:"Challenge,omitempty"`
	Scopes      []string          `protobuf:"bytes,2,rep,name=Scopes" json:"Scopes,omitempty"`
	Audiences   []string          `protobuf:"bytes,3,rep,name=Audiences" json:"Audiences,omitempty"`
	AccessToken map[string]string `protobuf:"bytes,4,rep,name=AccessToken" json:"AccessToken,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IDToken     map[string]string `protobuf:"bytes,5,rep,name=IDToken" json:"IDToken,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AcceptConsentRequest) Reset()                    { *m = AcceptConsentRequest{} }
func (m *AcceptConsentRequest) String() string            { return proto.CompactTextString(m) }
func (*AcceptConsentRequest) ProtoMessage()               {}
func (*AcceptConsentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AcceptConsentRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *AcceptConsentRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *AcceptConsentRequest) GetAudiences() []string {
	if m != nil {
		return m.Audiences
	}
	return nil
}

func (m *AcceptConsentRequest) GetAccessToken() map[string]string {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *AcceptConsentRequest) GetIDToken() map[string]string {
	if m != nil {
		return m.IDToken
	}
	return nil
}

type AcceptConsentResponse struct {
}

func (m *AcceptConsentResponse) Reset()                    { *m = AcceptConsentResponse{} }
func (m *AcceptConsentResponse) String() string            { return proto.CompactTextString(m) }
func (*AcceptConsentResponse) ProtoMessage()               {}
func (*AcceptConsentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type CreateLogoutRequest struct {
	RequestURL string `protobuf:"bytes,1,opt,name=RequestURL" json:"RequestURL,omitempty"`
	Subject    string `protobuf:"bytes,2,opt,name=Subject" json:"Subject,omitempty"`
	SessionID  string `protobuf:"bytes,3,opt,name=SessionID" json:"SessionID,omitempty"`
}

func (m *CreateLogoutRequest) Reset()                    { *m = CreateLogoutRequest{} }
func (m *CreateLogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateLogoutRequest) ProtoMessage()               {}
func (*CreateLogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CreateLogoutRequest) GetRequestURL() string {
	if m != nil {
		return m.RequestURL
	}
	return ""
}

func (m *CreateLogoutRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CreateLogoutRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type CreateLogoutResponse struct {
	Logout *ID `protobuf:"bytes,1,opt,name=Logout" json:"Logout,omitempty"`
}

func (m *CreateLogoutResponse) Reset()                    { *m = CreateLogoutResponse{} }
func (m *CreateLogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateLogoutResponse) ProtoMessage()               {}
func (*CreateLogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CreateLogoutResponse) GetLogout() *ID {
	if m != nil {
		return m.Logout
	}
	return nil
}

type AcceptLogoutRequest struct {
	Challenge    string `protobuf:"bytes,1,opt,name=Challenge" json:"Challenge,omitempty"`
	AccessToken  string `protobuf:"bytes,2,opt,name=AccessToken" json:"AccessToken,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
}

func (m *AcceptLogoutRequest) Reset()                    { *m = AcceptLogoutRequest{} }
func (m *AcceptLogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*AcceptLogoutRequest) ProtoMessage()               {}
func (*AcceptLogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *AcceptLogoutRequest) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

func (m *AcceptLogoutRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AcceptLogoutRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type AcceptLogoutResponse struct {
}

func (m *AcceptLogoutResponse) Reset()                    { *m = AcceptLogoutResponse{} }
func (m *AcceptLogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*AcceptLogoutResponse) ProtoMessage()               {}
func (*AcceptLogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type CreateAuthCodeRequest struct {
	Consent     *ID    `protobuf:"bytes,1,opt,name=Consent" json:"Consent,omitempty"`
	ClientID    string `protobuf:"bytes,2,opt,name=ClientID" json:"ClientID,omitempty"`
	RedirectURI string `protobuf:"bytes,3,opt,name=RedirectURI" json:"RedirectURI,omitempty"`
}

func (m *CreateAuthCodeRequest) Reset()                    { *m = CreateAuthCodeRequest{} }
func (m *CreateAuthCodeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAuthCodeRequest) ProtoMessage()               {}
func (*CreateAuthCodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *CreateAuthCodeRequest) GetConsent() *ID {
	if m != nil {
		return m.Consent
	}
	return nil
}

func (m *CreateAuthCodeRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *CreateAuthCodeRequest) GetRedirectURI() string {
	if m != nil {
		return m.RedirectURI
	}
	return ""
}

type CreateAuthCodeResponse struct {
	Code string `protobuf:"bytes,1,opt,name=Code" json:"Code,omitempty"`
}

func (m *CreateAuthCodeResponse) Reset()                    { *m = CreateAuthCodeResponse{} }
func (m *CreateAuthCodeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAuthCodeResponse) ProtoMessage()               {}
func (*CreateAuthCodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CreateAuthCodeResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type VerifyTokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=Token" json:"Token,omitempty"`
}

func (m *VerifyTokenRequest) Reset()                    { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()               {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *VerifyTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *VerifyTokenResponse) Reset()                    { *m = VerifyTokenResponse{} }
func (m *VerifyTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyTokenResponse) ProtoMessage()               {}
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *VerifyTokenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *VerifyTokenResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExchangeRequest struct {
	Code         string `protobuf:"bytes,1,opt,name=Code,json=code" json:"Code,omitempty"`
	CodeVerifier string `protobuf:"bytes,2,opt,name=CodeVerifier,json=code_verifier" json:"CodeVerifier,omitempty"`
}

func (m *ExchangeRequest) Reset()                    { *m = ExchangeRequest{} }
func (m *ExchangeRequest) String() string            { return proto.CompactTextString(m) }
func (*ExchangeRequest) ProtoMessage()               {}
func (*ExchangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ExchangeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ExchangeRequest) GetCodeVerifier() string {
	if m != nil {
		return m.CodeVerifier
	}
	return ""
}

type ExchangeResponse struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=AccessToken,json=access_token" json:"AccessToken,omitempty"`
	IDToken      string `protobuf:"bytes,2,opt,name=IDToken,json=id_token" json:"IDToken,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=RefreshToken,json=refresh_token" json:"RefreshToken,omitempty"`
	Expiry       int64  `protobuf:"varint,4,opt,name=Expiry,json=expiry" json:"Expiry,omitempty"`
}

func (m *ExchangeResponse) Reset()                    { *m = ExchangeResponse{} }
func (m *ExchangeResponse) String() string            { return proto.CompactTextString(m) }
func (*ExchangeResponse) ProtoMessage()               {}
func (*ExchangeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ExchangeResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *ExchangeResponse) GetIDToken() string {
	if m != nil {
		return m.IDToken
	}
	return ""
}

func (m *ExchangeResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *ExchangeResponse) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type RefreshTokenRequest struct {
	RefreshToken string `protobuf:"bytes,1,opt,name=RefreshToken" json:"RefreshToken,omitempty"`
}

func (m *RefreshTokenRequest) Reset()                    { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()               {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *RefreshTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=AccessToken,json=access_token" json:"AccessToken,omitempty"`
	IDToken      string `protobuf:"bytes,2,opt,name=IDToken,json=id_token" json:"IDToken,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=RefreshToken,json=refresh_token" json:"RefreshToken,omitempty"`
	Expiry       int64  `protobuf:"varint,4,opt,name=Expiry,json=expiry" json:"Expiry,omitempty"`
}

func (m *RefreshTokenResponse) Reset()                    { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()               {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *RefreshTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshTokenResponse) GetIDToken() string {
	if m != nil {
		return m.IDToken
	}
	return ""
}

func (m *RefreshTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *RefreshTokenResponse) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type PersonalAccessToken struct {
	Uuid              string   `protobuf:"bytes,1,opt,name=Uuid" json:"Uuid,omitempty"`
	Type              PatType  `protobuf:"varint,2,opt,name=Type,enum=auth.PatType" json:"Type,omitempty"`
	Label             string   `protobuf:"bytes,3,opt,name=Label" json:"Label,omitempty"`
	UserUuid          string   `protobuf:"bytes,4,opt,name=UserUuid" json:"UserUuid,omitempty"`
	UserLogin         string   `protobuf:"bytes,5,opt,name=UserLogin" json:"UserLogin,omitempty"`
	Scopes            []string `protobuf:"bytes,6,rep,name=Scopes" json:"Scopes,omitempty"`
	AutoRefreshWindow int32    `protobuf:"varint,7,opt,name=AutoRefreshWindow" json:"AutoRefreshWindow,omitempty"`
	ExpiresAt         int64    `protobuf:"varint,8,opt,name=ExpiresAt" json:"ExpiresAt,omitempty"`
	CreatedBy         string   `protobuf:"bytes,9,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedAt         int64    `protobuf:"varint,10,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	UpdatedAt         int64    `protobuf:"varint,11,opt,name=UpdatedAt" json:"UpdatedAt,omitempty"`
}

func (m *PersonalAccessToken) Reset()                    { *m = PersonalAccessToken{} }
func (m *PersonalAccessToken) String() string            { return proto.CompactTextString(m) }
func (*PersonalAccessToken) ProtoMessage()               {}
func (*PersonalAccessToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PersonalAccessToken) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PersonalAccessToken) GetType() PatType {
	if m != nil {
		return m.Type
	}
	return PatType_ANY
}

func (m *PersonalAccessToken) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *PersonalAccessToken) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *PersonalAccessToken) GetUserLogin() string {
	if m != nil {
		return m.UserLogin
	}
	return ""
}

func (m *PersonalAccessToken) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *PersonalAccessToken) GetAutoRefreshWindow() int32 {
	if m != nil {
		return m.AutoRefreshWindow
	}
	return 0
}

func (m *PersonalAccessToken) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *PersonalAccessToken) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *PersonalAccessToken) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *PersonalAccessToken) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type PatGenerateRequest struct {
	Type              PatType  `protobuf:"varint,1,opt,name=Type,enum=auth.PatType" json:"Type,omitempty"`
	UserUuid          string   `protobuf:"bytes,2,opt,name=UserUuid" json:"UserUuid,omitempty"`
	UserLogin         string   `protobuf:"bytes,3,opt,name=UserLogin" json:"UserLogin,omitempty"`
	Label             string   `protobuf:"bytes,4,opt,name=Label" json:"Label,omitempty"`
	AutoRefreshWindow int32    `protobuf:"varint,5,opt,name=AutoRefreshWindow" json:"AutoRefreshWindow,omitempty"`
	ExpiresAt         int64    `protobuf:"varint,6,opt,name=ExpiresAt" json:"ExpiresAt,omitempty"`
	Issuer            string   `protobuf:"bytes,7,opt,name=Issuer" json:"Issuer,omitempty"`
	Scopes            []string `protobuf:"bytes,8,rep,name=Scopes" json:"Scopes,omitempty"`
}

func (m *PatGenerateRequest) Reset()                    { *m = PatGenerateRequest{} }
func (m *PatGenerateRequest) String() string            { return proto.CompactTextString(m) }
func (*PatGenerateRequest) ProtoMessage()               {}
func (*PatGenerateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *PatGenerateRequest) GetType() PatType {
	if m != nil {
		return m.Type
	}
	return PatType_ANY
}

func (m *PatGenerateRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *PatGenerateRequest) GetUserLogin() string {
	if m != nil {
		return m.UserLogin
	}
	return ""
}

func (m *PatGenerateRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *PatGenerateRequest) GetAutoRefreshWindow() int32 {
	if m != nil {
		return m.AutoRefreshWindow
	}
	return 0
}

func (m *PatGenerateRequest) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *PatGenerateRequest) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *PatGenerateRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type PatGenerateResponse struct {
	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken" json:"AccessToken,omitempty"`
	TokenUuid   string `protobuf:"bytes,2,opt,name=TokenUuid" json:"TokenUuid,omitempty"`
}

func (m *PatGenerateResponse) Reset()                    { *m = PatGenerateResponse{} }
func (m *PatGenerateResponse) String() string            { return proto.CompactTextString(m) }
func (*PatGenerateResponse) ProtoMessage()               {}
func (*PatGenerateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *PatGenerateResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *PatGenerateResponse) GetTokenUuid() string {
	if m != nil {
		return m.TokenUuid
	}
	return ""
}

type PatListRequest struct {
	Type        PatType `protobuf:"varint,1,opt,name=Type,enum=auth.PatType" json:"Type,omitempty"`
	ByUserLogin string  `protobuf:"bytes,2,opt,name=ByUserLogin" json:"ByUserLogin,omitempty"`
}

func (m *PatListRequest) Reset()                    { *m = PatListRequest{} }
func (m *PatListRequest) String() string            { return proto.CompactTextString(m) }
func (*PatListRequest) ProtoMessage()               {}
func (*PatListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *PatListRequest) GetType() PatType {
	if m != nil {
		return m.Type
	}
	return PatType_ANY
}

func (m *PatListRequest) GetByUserLogin() string {
	if m != nil {
		return m.ByUserLogin
	}
	return ""
}

type PatListResponse struct {
	Tokens []*PersonalAccessToken `protobuf:"bytes,1,rep,name=Tokens" json:"Tokens,omitempty"`
}

func (m *PatListResponse) Reset()                    { *m = PatListResponse{} }
func (m *PatListResponse) String() string            { return proto.CompactTextString(m) }
func (*PatListResponse) ProtoMessage()               {}
func (*PatListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PatListResponse) GetTokens() []*PersonalAccessToken {
	if m != nil {
		return m.Tokens
	}
	return nil
}

type PatRevokeRequest struct {
	Uuid string `protobuf:"bytes,1,opt,name=Uuid" json:"Uuid,omitempty"`
}

func (m *PatRevokeRequest) Reset()                    { *m = PatRevokeRequest{} }
func (m *PatRevokeRequest) String() string            { return proto.CompactTextString(m) }
func (*PatRevokeRequest) ProtoMessage()               {}
func (*PatRevokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *PatRevokeRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type PatRevokeResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *PatRevokeResponse) Reset()                    { *m = PatRevokeResponse{} }
func (m *PatRevokeResponse) String() string            { return proto.CompactTextString(m) }
func (*PatRevokeResponse) ProtoMessage()               {}
func (*PatRevokeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *PatRevokeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*RevokeTokenRequest)(nil), "auth.RevokeTokenRequest")
	proto.RegisterType((*RevokeTokenResponse)(nil), "auth.RevokeTokenResponse")
	proto.RegisterType((*PruneTokensRequest)(nil), "auth.PruneTokensRequest")
	proto.RegisterType((*PruneTokensResponse)(nil), "auth.PruneTokensResponse")
	proto.RegisterType((*ID)(nil), "auth.ID")
	proto.RegisterType((*GetLoginRequest)(nil), "auth.GetLoginRequest")
	proto.RegisterType((*GetLoginResponse)(nil), "auth.GetLoginResponse")
	proto.RegisterType((*CreateLoginRequest)(nil), "auth.CreateLoginRequest")
	proto.RegisterType((*CreateLoginResponse)(nil), "auth.CreateLoginResponse")
	proto.RegisterType((*AcceptLoginRequest)(nil), "auth.AcceptLoginRequest")
	proto.RegisterType((*AcceptLoginResponse)(nil), "auth.AcceptLoginResponse")
	proto.RegisterType((*GetConsentRequest)(nil), "auth.GetConsentRequest")
	proto.RegisterType((*GetConsentResponse)(nil), "auth.GetConsentResponse")
	proto.RegisterType((*CreateConsentRequest)(nil), "auth.CreateConsentRequest")
	proto.RegisterType((*CreateConsentResponse)(nil), "auth.CreateConsentResponse")
	proto.RegisterType((*AcceptConsentRequest)(nil), "auth.AcceptConsentRequest")
	proto.RegisterType((*AcceptConsentResponse)(nil), "auth.AcceptConsentResponse")
	proto.RegisterType((*CreateLogoutRequest)(nil), "auth.CreateLogoutRequest")
	proto.RegisterType((*CreateLogoutResponse)(nil), "auth.CreateLogoutResponse")
	proto.RegisterType((*AcceptLogoutRequest)(nil), "auth.AcceptLogoutRequest")
	proto.RegisterType((*AcceptLogoutResponse)(nil), "auth.AcceptLogoutResponse")
	proto.RegisterType((*CreateAuthCodeRequest)(nil), "auth.CreateAuthCodeRequest")
	proto.RegisterType((*CreateAuthCodeResponse)(nil), "auth.CreateAuthCodeResponse")
	proto.RegisterType((*VerifyTokenRequest)(nil), "auth.VerifyTokenRequest")
	proto.RegisterType((*VerifyTokenResponse)(nil), "auth.VerifyTokenResponse")
	proto.RegisterType((*ExchangeRequest)(nil), "auth.ExchangeRequest")
	proto.RegisterType((*ExchangeResponse)(nil), "auth.ExchangeResponse")
	proto.RegisterType((*RefreshTokenRequest)(nil), "auth.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResponse)(nil), "auth.RefreshTokenResponse")
	proto.RegisterType((*PersonalAccessToken)(nil), "auth.PersonalAccessToken")
	proto.RegisterType((*PatGenerateRequest)(nil), "auth.PatGenerateRequest")
	proto.RegisterType((*PatGenerateResponse)(nil), "auth.PatGenerateResponse")
	proto.RegisterType((*PatListRequest)(nil), "auth.PatListRequest")
	proto.RegisterType((*PatListResponse)(nil), "auth.PatListResponse")
	proto.RegisterType((*PatRevokeRequest)(nil), "auth.PatRevokeRequest")
	proto.RegisterType((*PatRevokeResponse)(nil), "auth.PatRevokeResponse")
	proto.RegisterEnum("auth.PatType", PatType_name, PatType_value)
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0x16, 0xf5, 0x67, 0xf9, 0x48, 0xb6, 0xe5, 0x91, 0xac, 0x28, 0xba, 0x41, 0xa0, 0x4c, 0x80,
	0xdc, 0x20, 0x37, 0x71, 0x10, 0x5d, 0x04, 0x37, 0x37, 0x01, 0x12, 0x28, 0x92, 0x6b, 0x28, 0x70,
	0x12, 0x81, 0xb6, 0xfa, 0xb3, 0x0a, 0x18, 0x71, 0x12, 0xb3, 0x71, 0x49, 0x95, 0xa4, 0xdc, 0x68,
	0x5d, 0x74, 0xd9, 0x45, 0x97, 0xdd, 0xf6, 0x41, 0xfa, 0x12, 0xdd, 0x14, 0x7d, 0x86, 0x3e, 0x40,
	0xd1, 0x55, 0x31, 0x7f, 0xe4, 0xcc, 0x90, 0x75, 0xec, 0x6c, 0xba, 0xe3, 0x9c, 0x33, 0x73, 0xe6,
	0xfc, 0xcf, 0x77, 0x08, 0xe0, 0x2c, 0xe3, 0xe3, 0xdd, 0x45, 0x18, 0xc4, 0x01, 0x2a, 0xd3, 0x6f,
	0xfc, 0x9d, 0x05, 0x95, 0xa3, 0xe0, 0x1d, 0xf1, 0x51, 0x1f, 0xea, 0xc3, 0xf9, 0x9c, 0x44, 0x11,
	0x5b, 0x76, 0xad, 0xbe, 0x75, 0x73, 0xdd, 0x56, 0x49, 0xa8, 0x0b, 0x6b, 0x93, 0x31, 0xe7, 0x16,
	0x19, 0x57, 0x2e, 0x11, 0x86, 0x86, 0x4d, 0xde, 0x84, 0x24, 0x3a, 0xe6, 0xec, 0x12, 0x63, 0x6b,
	0x34, 0x74, 0x05, 0xd6, 0xf7, 0xde, 0x2f, 0xbc, 0x90, 0x44, 0xc3, 0xb8, 0x5b, 0x66, 0x1b, 0x52,
	0x02, 0xfe, 0x1f, 0x20, 0x9b, 0x9c, 0x06, 0xef, 0x08, 0xdb, 0x6c, 0x93, 0xaf, 0x97, 0x24, 0x8a,
	0xd1, 0x35, 0xa1, 0x1c, 0xd3, 0xa6, 0x3e, 0xa8, 0xef, 0x32, 0xfd, 0xf9, 0x16, 0xce, 0xc1, 0x77,
	0xa1, 0xa5, 0x1d, 0x8c, 0x16, 0x81, 0x1f, 0x11, 0xaa, 0xeb, 0xe1, 0x92, 0xe9, 0xce, 0xce, 0xd6,
	0x6c, 0xb9, 0xc4, 0x6d, 0x40, 0xd3, 0x70, 0xe9, 0xf3, 0xfd, 0x91, 0xb8, 0x09, 0xdf, 0x81, 0x96,
	0x46, 0x15, 0x62, 0x3a, 0x50, 0x8d, 0x19, 0xa5, 0x6b, 0xf5, 0x4b, 0x37, 0xd7, 0x6d, 0xb1, 0xc2,
	0x36, 0x14, 0x27, 0x63, 0x6a, 0xd2, 0xe8, 0xd8, 0x39, 0x39, 0x21, 0xfe, 0x5b, 0x22, 0x1c, 0x96,
	0x12, 0x50, 0x0f, 0x6a, 0x9f, 0x92, 0xd0, 0x7b, 0xe3, 0x91, 0x50, 0xf8, 0x2b, 0x59, 0x23, 0x04,
	0xe5, 0xd1, 0xa1, 0xfd, 0x89, 0x70, 0x14, 0xfb, 0xc6, 0x77, 0x61, 0x6b, 0x9f, 0xc4, 0x07, 0xc1,
	0x5b, 0x2f, 0xb1, 0xff, 0xcc, 0x0b, 0xf0, 0x9f, 0x16, 0x34, 0xd3, 0x13, 0x42, 0xe3, 0xb3, 0x75,
	0x62, 0x6e, 0x79, 0xfd, 0x25, 0x99, 0xc7, 0x32, 0x84, 0x62, 0x49, 0xcf, 0x1d, 0x92, 0x28, 0xf2,
	0x02, 0x7f, 0x32, 0x16, 0x6a, 0xa5, 0x04, 0x74, 0x15, 0x40, 0xe8, 0x34, 0xb3, 0x0f, 0x44, 0xf4,
	0x14, 0x0a, 0xba, 0x01, 0x9b, 0x62, 0x45, 0xdc, 0xc3, 0x79, 0xb0, 0x20, 0xdd, 0x0a, 0xf3, 0x97,
	0x41, 0x45, 0xb7, 0x61, 0x3b, 0xa1, 0x0c, 0x97, 0xae, 0x47, 0xfc, 0x39, 0xe9, 0x56, 0xd9, 0xd6,
	0x2c, 0x83, 0x7a, 0x70, 0x74, 0xe2, 0x11, 0x3f, 0x9e, 0x8c, 0xbb, 0x6b, 0xdc, 0x83, 0x72, 0x8d,
	0xdf, 0x00, 0x1a, 0x85, 0xc4, 0x89, 0x89, 0xe6, 0x30, 0xf5, 0x84, 0xa5, 0x9f, 0xa0, 0xb1, 0x64,
	0x4a, 0x44, 0xdd, 0x22, 0x8f, 0x25, 0x5f, 0x51, 0xcb, 0xe5, 0x8d, 0x51, 0xb7, 0xc4, 0x58, 0x29,
	0x01, 0xdf, 0x87, 0x96, 0x76, 0x8f, 0x70, 0xf3, 0x55, 0xa8, 0x30, 0x82, 0xc8, 0xcc, 0x1a, 0xcf,
	0xcc, 0xc9, 0xd8, 0xe6, 0x64, 0x7c, 0x0c, 0x88, 0x96, 0xce, 0xe2, 0x02, 0xf1, 0x3c, 0x33, 0x61,
	0x94, 0xc0, 0x95, 0xb4, 0xc0, 0xe1, 0x1d, 0x68, 0x69, 0x37, 0x71, 0x05, 0xf1, 0x3d, 0xd8, 0xde,
	0x27, 0xf1, 0x88, 0x7e, 0xfb, 0xf1, 0xf9, 0xf2, 0xe9, 0x67, 0x0b, 0x90, 0x7a, 0xe6, 0x5c, 0x19,
	0x75, 0x03, 0x36, 0xd9, 0xc5, 0x69, 0xf2, 0x70, 0xd5, 0x0d, 0x2a, 0x8d, 0xbc, 0xd0, 0x78, 0xe2,
	0x12, 0x3f, 0xe6, 0x56, 0x72, 0x53, 0xb2, 0x0c, 0xd5, 0xdc, 0xb2, 0x9e, 0xa7, 0x6a, 0x84, 0x2b,
	0x46, 0x4e, 0x3c, 0x86, 0x36, 0x8f, 0x95, 0x61, 0xb6, 0xd4, 0xd1, 0x34, 0xc3, 0xa0, 0xe2, 0x47,
	0xb0, 0x63, 0x9c, 0x17, 0x2e, 0xc0, 0xb0, 0x26, 0x48, 0x99, 0x78, 0x4b, 0x06, 0xfe, 0xa3, 0x08,
	0x6d, 0x1e, 0x88, 0x8b, 0x38, 0xfd, 0xe3, 0xb2, 0x12, 0x3d, 0xd7, 0x9b, 0x75, 0xb9, 0x5f, 0xba,
	0x59, 0x1f, 0xfc, 0x87, 0x2b, 0x95, 0xa7, 0xc4, 0xae, 0xb2, 0x7b, 0xcf, 0x8f, 0xc3, 0x95, 0xde,
	0xd9, 0x87, 0x69, 0x67, 0xaf, 0x30, 0x51, 0xff, 0x3e, 0x43, 0x94, 0xd8, 0xc9, 0xc5, 0xc8, 0x73,
	0xbd, 0xc7, 0xd0, 0x34, 0xef, 0x40, 0x4d, 0x28, 0xbd, 0x23, 0x2b, 0x61, 0x33, 0xfd, 0x44, 0x6d,
	0xa8, 0x9c, 0x3a, 0x27, 0x4b, 0x22, 0x92, 0x84, 0x2f, 0x1e, 0x16, 0x1f, 0x58, 0xbd, 0x87, 0xd0,
	0x50, 0x05, 0x5f, 0xe4, 0x2c, 0xbe, 0x04, 0x3b, 0x86, 0xa6, 0xa2, 0x08, 0xbe, 0x52, 0x8a, 0x37,
	0x58, 0x26, 0x11, 0xd1, 0xbb, 0x99, 0x95, 0xe9, 0x66, 0x1f, 0xd9, 0x25, 0xf1, 0x03, 0x99, 0x7f,
	0xf2, 0x3a, 0x91, 0x3e, 0x7d, 0xa8, 0x72, 0x4a, 0x26, 0x7b, 0x04, 0x1d, 0xaf, 0x94, 0x22, 0x56,
	0x14, 0x3d, 0x3b, 0x75, 0x8c, 0x17, 0xbb, 0x98, 0x7d, 0xb1, 0xcf, 0xf1, 0x2e, 0xe3, 0x8e, 0x4c,
	0x5b, 0x5d, 0x69, 0xbc, 0x92, 0xc5, 0x30, 0x5c, 0xc6, 0xc7, 0xa3, 0xc0, 0x25, 0x52, 0xa9, 0x73,
	0x14, 0x83, 0x56, 0xa5, 0x45, 0xa3, 0x0f, 0xf7, 0xa1, 0x6e, 0x13, 0xd7, 0x0b, 0xc9, 0x3c, 0x9e,
	0xd9, 0x13, 0xa1, 0x93, 0x4a, 0xc2, 0xb7, 0xa1, 0x63, 0x5e, 0x2d, 0x3c, 0x49, 0xdf, 0xcd, 0xc0,
	0x95, 0xbe, 0x60, 0xdf, 0xf8, 0x16, 0x20, 0xd6, 0x26, 0x57, 0x1a, 0x74, 0x68, 0xab, 0xd0, 0x61,
	0x5d, 0xa2, 0x85, 0x11, 0xb4, 0xb4, 0xbd, 0x1f, 0x42, 0x0b, 0xf4, 0xc2, 0xb1, 0x13, 0x3b, 0xcc,
	0x88, 0x86, 0xcd, 0xbe, 0xf1, 0x33, 0xd8, 0xda, 0x7b, 0x3f, 0x3f, 0x76, 0xfc, 0xb7, 0x89, 0x4f,
	0x0c, 0xbd, 0xe6, 0x81, 0x4b, 0xd0, 0x75, 0x68, 0x50, 0x9a, 0xd1, 0xd2, 0x37, 0x28, 0xef, 0xd5,
	0xa9, 0x20, 0xe2, 0xef, 0x2d, 0x68, 0xa6, 0xc2, 0x84, 0x3a, 0xd7, 0xf2, 0xa0, 0x58, 0xc3, 0x61,
	0xa4, 0x57, 0x0c, 0x81, 0xa0, 0xcb, 0x26, 0x16, 0xab, 0x79, 0xae, 0x60, 0x5d, 0xcf, 0x0d, 0xfa,
	0x46, 0xc8, 0x69, 0x62, 0x53, 0x07, 0xaa, 0x0c, 0x7c, 0xad, 0x58, 0x7f, 0x2d, 0xd9, 0x55, 0xc2,
	0x56, 0xf8, 0xff, 0x14, 0x4e, 0xa5, 0x87, 0xd3, 0x98, 0xeb, 0x32, 0xad, 0x9c, 0x44, 0xfa, 0xc1,
	0x82, 0xb6, 0x7e, 0xf6, 0x9f, 0x37, 0xe7, 0xb7, 0x22, 0xb4, 0xa6, 0x24, 0x8c, 0x02, 0xdf, 0x39,
	0x51, 0x0b, 0x03, 0x41, 0x79, 0xb6, 0xf4, 0x5c, 0x19, 0x2f, 0xfa, 0x8d, 0xae, 0x41, 0xf9, 0x68,
	0xb5, 0xe0, 0xed, 0x65, 0x73, 0xb0, 0xc1, 0x93, 0x7a, 0xea, 0xc4, 0x94, 0x68, 0x33, 0x16, 0x4d,
	0xaa, 0x03, 0xe7, 0x35, 0x39, 0x11, 0x4a, 0xf0, 0x05, 0x4d, 0xf6, 0x59, 0x44, 0x42, 0x26, 0x90,
	0xbf, 0x56, 0xc9, 0x9a, 0x56, 0x30, 0xfd, 0xe6, 0x58, 0x81, 0xbf, 0x57, 0x29, 0x41, 0x69, 0xfe,
	0x55, 0xad, 0xf9, 0xdf, 0x86, 0xed, 0xe1, 0x32, 0x0e, 0x84, 0xdd, 0x9f, 0x79, 0xbe, 0x1b, 0x7c,
	0xc3, 0x10, 0x50, 0xc5, 0xce, 0x32, 0x74, 0x64, 0x5d, 0x63, 0xf6, 0xa7, 0x04, 0xd6, 0x43, 0x58,
	0x31, 0xb9, 0x4f, 0x57, 0xdd, 0x75, 0xd1, 0x43, 0x24, 0x41, 0xe1, 0x0e, 0xe3, 0x2e, 0xf0, 0xb3,
	0x09, 0x81, 0x69, 0xbf, 0x70, 0x05, 0xb7, 0xce, 0xb9, 0x09, 0x01, 0x7f, 0x5b, 0x04, 0x34, 0x75,
	0xe2, 0x7d, 0xe2, 0x93, 0xd0, 0x89, 0x49, 0x0a, 0xda, 0xb9, 0x1f, 0xad, 0xbf, 0xf7, 0xa3, 0xea,
	0xb1, 0xe2, 0x59, 0x1e, 0x2b, 0x99, 0x1e, 0x4b, 0x22, 0x50, 0x56, 0x23, 0x90, 0xeb, 0xaf, 0xca,
	0xb9, 0xfc, 0x55, 0x35, 0xfd, 0xd5, 0x81, 0xea, 0x24, 0x8a, 0x96, 0x24, 0x14, 0x90, 0x53, 0xac,
	0x94, 0x58, 0xd5, 0xd4, 0x58, 0xe1, 0x19, 0xb4, 0x34, 0x27, 0x24, 0x3d, 0xff, 0x43, 0xe3, 0xd4,
	0x15, 0x58, 0x67, 0x1f, 0x8a, 0x17, 0x52, 0x02, 0x9e, 0xc1, 0xe6, 0xd4, 0x89, 0x0f, 0xbc, 0x28,
	0xbe, 0x80, 0x5f, 0xfb, 0x50, 0x7f, 0xba, 0x4a, 0xbd, 0x27, 0x5e, 0x04, 0x85, 0x84, 0xc7, 0xb0,
	0x95, 0x88, 0x15, 0x9a, 0xde, 0x83, 0xea, 0x51, 0x3a, 0xe3, 0xd4, 0x07, 0x97, 0x85, 0xe4, 0x6c,
	0xd9, 0xd8, 0x62, 0x23, 0xbe, 0x01, 0xcd, 0xa9, 0x13, 0xf3, 0xb9, 0x4b, 0x69, 0x81, 0x66, 0x49,
	0xe1, 0x3b, 0xb0, 0xad, 0xec, 0xfb, 0x50, 0xb3, 0xbd, 0xb5, 0x0b, 0x6b, 0xc2, 0x1e, 0xb4, 0x06,
	0xa5, 0xe1, 0x8b, 0x2f, 0x9a, 0x05, 0xd4, 0x80, 0xda, 0x74, 0xcf, 0x3e, 0x7c, 0xf9, 0x62, 0x78,
	0xd0, 0xb4, 0xe8, 0x6a, 0xfc, 0x72, 0x34, 0x7b, 0xbe, 0xf7, 0xe2, 0xa8, 0x59, 0x1c, 0xfc, 0x68,
	0x41, 0x93, 0x3e, 0x11, 0xa2, 0xdd, 0xd0, 0x5b, 0x42, 0xf4, 0x04, 0xaa, 0xfc, 0x13, 0x75, 0xb9,
	0x21, 0xd9, 0xb9, 0xb2, 0x77, 0x39, 0x87, 0x23, 0x9e, 0xbd, 0x02, 0x1a, 0x43, 0x5d, 0x19, 0x05,
	0xa5, 0x94, 0xec, 0xcc, 0x28, 0xa5, 0xe4, 0xcc, 0x8d, 0xb8, 0x30, 0xf8, 0xd5, 0x82, 0x0d, 0xe6,
	0xf2, 0x69, 0x18, 0x9c, 0x7a, 0x2e, 0x09, 0xd1, 0x23, 0xa8, 0xc9, 0x69, 0x0d, 0xed, 0xf0, 0xa3,
	0xc6, 0xbc, 0xd7, 0xeb, 0x98, 0x64, 0x55, 0x29, 0x65, 0x0c, 0x91, 0x4a, 0x65, 0x27, 0x20, 0xa9,
	0x54, 0xce, 0xcc, 0xc2, 0xa5, 0x28, 0xb3, 0x82, 0x94, 0x92, 0x1d, 0x54, 0xa4, 0x94, 0xbc, 0xc1,
	0xa2, 0x30, 0xf8, 0xdd, 0x82, 0x2d, 0xf1, 0xd0, 0x27, 0xc6, 0x0d, 0x01, 0xd2, 0xd1, 0x01, 0x5d,
	0x4a, 0xec, 0xd0, 0xb1, 0x63, 0xaf, 0x9b, 0x65, 0x24, 0xca, 0x3d, 0x83, 0x0d, 0x0d, 0x7d, 0xa3,
	0x9e, 0x6a, 0x8a, 0x21, 0xe8, 0x5f, 0xb9, 0x3c, 0x55, 0x96, 0x86, 0x08, 0xa5, 0xac, 0x3c, 0x40,
	0x2b, 0x65, 0xe5, 0x43, 0xc8, 0xc2, 0xe0, 0x27, 0x8b, 0x8d, 0x0f, 0xc1, 0x32, 0xb5, 0x76, 0x1f,
	0x1a, 0x2a, 0xd0, 0x43, 0xa6, 0xd3, 0x53, 0x08, 0xd7, 0xeb, 0xe5, 0xb1, 0x12, 0x3d, 0xf7, 0xa1,
	0xa1, 0x82, 0x2f, 0x64, 0xfa, 0x3d, 0x2b, 0x28, 0x17, 0xab, 0x15, 0x06, 0x0e, 0xaf, 0x04, 0x0a,
	0x38, 0x12, 0x2d, 0x9f, 0xc3, 0xa6, 0x0e, 0xa3, 0x90, 0xe6, 0x35, 0x03, 0xd7, 0xf5, 0xae, 0xe4,
	0x33, 0x93, 0x2b, 0x8e, 0x58, 0x93, 0xe5, 0xc5, 0x96, 0xcc, 0xa5, 0x4f, 0xa0, 0xca, 0x01, 0x95,
	0x4c, 0xa6, 0x2c, 0x14, 0x93, 0xc9, 0x94, 0x03, 0xbc, 0x70, 0x61, 0x30, 0xe5, 0x52, 0xe9, 0x5d,
	0x12, 0x07, 0xb1, 0x52, 0x91, 0x0b, 0x59, 0x2a, 0x06, 0xe2, 0x92, 0xa5, 0x62, 0x62, 0x27, 0x5c,
	0x18, 0x7c, 0x0e, 0x48, 0x69, 0x0a, 0xac, 0xf1, 0x93, 0x10, 0x3d, 0x85, 0x35, 0xb1, 0x40, 0x49,
	0xf5, 0x67, 0x70, 0x8e, 0x74, 0x72, 0x1e, 0x8c, 0xc1, 0x85, 0xc1, 0x2f, 0x16, 0xf4, 0x72, 0xda,
	0xe2, 0x21, 0x09, 0x4f, 0xbd, 0x39, 0x41, 0x43, 0x5a, 0xe0, 0xfc, 0x19, 0x48, 0xba, 0x46, 0xe6,
	0x79, 0x4c, 0xba, 0x46, 0xf6, 0xcd, 0xc0, 0x05, 0xf4, 0x28, 0x69, 0x5e, 0x9d, 0x64, 0x9b, 0xd6,
	0x66, 0x7b, 0x97, 0x32, 0xf4, 0xe4, 0xf0, 0x7d, 0x28, 0xd3, 0xc6, 0x8e, 0xda, 0xc9, 0x16, 0xe5,
	0xf9, 0xe8, 0xed, 0x18, 0x54, 0x79, 0xec, 0x75, 0x95, 0xfd, 0x0f, 0xfc, 0xef, 0x5f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x35, 0xfe, 0x46, 0xb9, 0x1d, 0x14, 0x00, 0x00,
}
