apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cells.fullname" . }}-controller
  labels:
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" .) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "cells.fullname" . }}-controller
  template:
    metadata:
      labels:
        app: {{ include "cells.fullname" . }}-controller
      annotations:
      {{- if (include "cells.vault.enabled" .) }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: {{ include "cells.serviceAccountName" . }}
        vault.hashicorp.com/service: "http://{{ include "cells.vault.host" . }}:{{ include "cells.vault.port" . }}"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject-token: "true"
      {{- end }}
      {{- if and .Values.externalVault.enabled (not (empty .Values.externalVault.annotations)) -}}
      {{- toYaml .Values.externalVault.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "cells.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: CELLS_BOOTSTRAP_FILE
              value: /var/cells-bootstrap/bootstrap.yaml
            - name: CELLS_START_K8S_MANAGER
              value: "true"
            - name: CELLS_START_K8S_MANAGER_SECRET
              value: {{ include "cells.auth.secretName" . }}
            - name: CELLS_START_K8S_MANAGER_CONFIGMAP
              value: {{ include "cells.fullname" .}}
            - name: CELLS_WORKING_DIR
              value: /var/cells
            - name: CELLS_LOG_DIR
              value: /var/log/cells
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
                  {{- include "cells.auth.envvar" (dict "prefix" "CELLS" "auth" .Values.auth) | nindent 12 -}}
                  {{- include "cells.discovery.envvar" . | nindent 12 -}}
                  {{- include "cells.broker.envvar" . | nindent 12 -}}
                  {{- include "cells.cache.envvar" . | nindent 12 -}}
                  {{- include "cells.vault.envvar" . | nindent 12 -}}
                  {{- include "cells.discovery.auth.envvar" . | nindent 12 -}}
                  {{- include "cells.database.auth.envvar" . | nindent 12 -}}
                  {{- include "cells.broker.auth.envvar" . | nindent 12 -}}
                  {{- include "cells.cache.auth.envvar" . | nindent 12 -}}
                  {{- include "cells.nosql.auth.envvar" . | nindent 12 -}}
                  {{- include "cells.s3.auth.envvar" . | nindent 12 -}}
                  {{- include "cells.vault.auth.envvar" . | nindent 12 }}
            {{- if .Values.extraControllerEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraControllerEnvVars "context" $) | nindent 12 -}}
            {{- end }}
          {{- if .Values.image.local }}
          image: "{{ .Values.image.repository }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh" ]
          args:
            [ '-c', 'source /var/cells-install/source && cells start' ]
          name: {{ include "cells.fullname" . }}-controller
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
          volumeMounts:
            - mountPath: /var/cells-bootstrap
              name: {{ include "cells.fullname" . }}-controller
            - name: install
              mountPath: /var/cells-install
            {{- if not (empty .Values.extraControllerVolumeMounts) -}}
            {{- toYaml .Values.extraControllerVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - configMap:
            name: {{ include "cells.fullname" . }}-controller
          name: {{ include "cells.fullname" . }}-controller
        - name: install
          configMap:
            name: {{ include "cells.fullname" . }}
        {{- if (include "cells.vault.tls.enabled" .) }}
        - name: vault-ca-certs
          secret:
            secretName: {{ include "cells.vault.tls.ca.existingSecret" . }}
        - name: vault-client-certs
          secret:
            secretName: {{ include "cells.vault.tls.client.existingSecret" . }}
        {{- end }}
        {{- if .Values.extraControllerVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraControllerVolumes "context" $) | nindent 8 }}
        {{- end }}