{{- if and .Values.keyring.enabled .Values.keyring.masterKey.enabled }}
{{- $masterKeySecretName := (include "common.secrets.name" (dict "context" . "existingSecret" .Values.keyring.masterKey.existingSecret "defaultNameSuffix" "master-key")) -}}
{{- $masterKeySecretKey := (include "common.secrets.key" (dict "existingSecret" .Values.keyring.masterKey.existingSecret "key" "masterKey")) -}}
{{- if not .Values.keyring.masterKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $masterKeySecretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.keyring.masterKey.annotations .Values.commonAnnotations }}
  annotations:
      {{- if .Values.keyring.masterKey.annotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.keyring.masterKey.annotations "context" $ ) | nindent 4 }}
      {{- end }}
      {{- if .Values.commonAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
  {{- end }}
type: Opaque
stringData:
  {{ $masterKeySecretKey }}: | {{- dict "pydio.grpc.user-key" (dict "keyring.master" (include "common.secrets.passwords.manage" (dict "secret" $masterKeySecretName "key" $masterKeySecretKey "providedValues" (list "keyring.masterKey.value") "strong" true "skipQuote" true "skipB64enc" false "length" 50 "honorProvidedValues" true "context" $))) | toPrettyJson | nindent 4 }}
{{- end -}}
{{- end -}}