# Handle certificate and download in a distinct stage to reduce image size
FROM alpine as certs
ARG version

RUN apk update && apk add ca-certificates
ENV CELLS_VERSION ${version}

WORKDIR /pydio
RUN wget "https://download.pydio.com/pub/cells/release/${CELLS_VERSION}/linux-amd64/cells"
RUN wget --output-document=jq "https://download.pydio.com/pub/linux/tools/jq-linux64-v1.6"
RUN chmod +x /pydio/cells /pydio/jq 

# Create the target image
FROM busybox:glibc
ARG version

# Add necessary files
COPY docker-entrypoint.sh /pydio/docker-entrypoint.sh
COPY libdl.so.2 /pydio/libdl.so.2
COPY --from=certs /pydio/jq /bin/jq
COPY --from=certs /etc/ssl/certs /etc/ssl/certs
COPY --from=certs /pydio/cells /pydio/cells

ENV CADDYPATH /var/cells/certs 
ENV CELLS_WORKING_DIR /var/cells
WORKDIR $CELLS_WORKING_DIR

# Final configuration
RUN ln -s /pydio/cells /bin/cells \
    && ln -s /pydio/libdl.so.2 /lib64/libdl.so.2 \
    && ln -s /pydio/docker-entrypoint.sh /bin/docker-entrypoint.sh \
    && chmod +x /pydio/docker-entrypoint.sh \
    && echo "Pydio Cells Home Docker Image" > /var/cells/package.info \
    && echo "  A ready-to-go docker image based on BusyBox to configure and launch Cells in no time." >> /var/cells/package.info \
    && echo "  Generated on $(date) with docker build script from version ${version}" >> /var/cells/package.info

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["cells", "start"]
