# https://github.com/mongodb/mongodb-kubernetes/blob/master/docs/mongodbcommunity/users.md
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-secret
type: Opaque
#stringData:
data:
  password: Y2VsbHM=