entryPoints:
  dashboard:
    address: :8080
  web:
    address: :80
  websecure:
    address: :443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

api:
  dashboard: true
  debug: true

log:
  level: DEBUG