# https://github.com/mongodb/helm-charts/blob/main/charts/community-operator/values.yaml
---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
    tls:
      enabled: false
      certificateKeySecretRef:
        # search for tls.crt, tls.key
        name: mongodb-tls
      caCertificateSecretRef:
        # search for ca.crt
        name: mongodb-tls
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-cells-secret
      roles:
        - name: clusterAdmin
          db: admin
        - name: root
          db: admin          
      scramCredentialsSecretName: my-scram1
    - name: cells
      db: admin
      passwordSecretRef:
        name: mongodb-cells-secret
      roles:
        - name: dbOwner
          db: cells
      scramCredentialsSecretName: my-scram2 
    # - name: backup
    #   db: admin
    #   passwordSecretRef:
    #     name: mongodb-cells-secret
    #   roles:
    #     - name: read
    #       db: cells
    #   scramCredentialsSecretName: my-scram3         
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
