apiVersion: v1
kind: Secret
metadata:  
  name: mariadb-secret
type: Opaque
data:
  mariadb-password: Y2VsbHM=
  mariadb-username: Y2VsbHM=
  mariadb-replication-password: cmVwbFBhc3M=
  mariadb-root-password: cm9vdFBhc3M=
