// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tree.proto

/*
Package tree is a generated protocol buffer package.

It is generated from these files:
	tree.proto

It has these top-level messages:
	ReadNodeRequest
	ReadNodeResponse
	ListNodesRequest
	ListNodesResponse
	CreateNodeRequest
	CreateNodeResponse
	UpdateNodeRequest
	UpdateNodeResponse
	DeleteNodeRequest
	DeleteNodeResponse
	IndexationSession
	IndexationOperation
	OpenSessionRequest
	OpenSessionResponse
	FlushSessionRequest
	FlushSessionResponse
	CloseSessionRequest
	CloseSessionResponse
	WatchNodeRequest
	WatchNodeResponse
	SearchRequest
	SearchResponse
	CreateVersionRequest
	CreateVersionResponse
	ListVersionsRequest
	ListVersionsResponse
	HeadVersionRequest
	HeadVersionResponse
	StoreVersionRequest
	StoreVersionResponse
	PruneVersionsRequest
	PruneVersionsResponse
	VersioningPolicy
	VersioningKeepPeriod
	Node
	WorkspaceRelativePath
	ChangeLog
	Query
	GeoQuery
	GeoPoint
	NodeChangeEvent
	IndexEvent
	GetEncryptionKeyRequest
	GetEncryptionKeyResponse
	SyncChange
	SyncChangeNode
	PutSyncChangeResponse
	SearchSyncChangeRequest
*/
package tree

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ==========================================================
// * Standard Messages
// ==========================================================
type NodeType int32

const (
	NodeType_UNKNOWN    NodeType = 0
	NodeType_LEAF       NodeType = 1
	NodeType_COLLECTION NodeType = 2
)

var NodeType_name = map[int32]string{
	0: "UNKNOWN",
	1: "LEAF",
	2: "COLLECTION",
}
var NodeType_value = map[string]int32{
	"UNKNOWN":    0,
	"LEAF":       1,
	"COLLECTION": 2,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}
func (NodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NodeChangeEvent_EventType int32

const (
	NodeChangeEvent_CREATE         NodeChangeEvent_EventType = 0
	NodeChangeEvent_READ           NodeChangeEvent_EventType = 1
	NodeChangeEvent_UPDATE_PATH    NodeChangeEvent_EventType = 2
	NodeChangeEvent_UPDATE_CONTENT NodeChangeEvent_EventType = 3
	NodeChangeEvent_UPDATE_META    NodeChangeEvent_EventType = 4
	NodeChangeEvent_DELETE         NodeChangeEvent_EventType = 5
)

var NodeChangeEvent_EventType_name = map[int32]string{
	0: "CREATE",
	1: "READ",
	2: "UPDATE_PATH",
	3: "UPDATE_CONTENT",
	4: "UPDATE_META",
	5: "DELETE",
}
var NodeChangeEvent_EventType_value = map[string]int32{
	"CREATE":         0,
	"READ":           1,
	"UPDATE_PATH":    2,
	"UPDATE_CONTENT": 3,
	"UPDATE_META":    4,
	"DELETE":         5,
}

func (x NodeChangeEvent_EventType) String() string {
	return proto.EnumName(NodeChangeEvent_EventType_name, int32(x))
}
func (NodeChangeEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{40, 0}
}

type SyncChange_Type int32

const (
	SyncChange_unknown SyncChange_Type = 0
	SyncChange_create  SyncChange_Type = 1
	SyncChange_delete  SyncChange_Type = 2
	SyncChange_path    SyncChange_Type = 3
	SyncChange_content SyncChange_Type = 4
)

var SyncChange_Type_name = map[int32]string{
	0: "unknown",
	1: "create",
	2: "delete",
	3: "path",
	4: "content",
}
var SyncChange_Type_value = map[string]int32{
	"unknown": 0,
	"create":  1,
	"delete":  2,
	"path":    3,
	"content": 4,
}

func (x SyncChange_Type) String() string {
	return proto.EnumName(SyncChange_Type_name, int32(x))
}
func (SyncChange_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{44, 0} }

// Request / Responses Messages
type ReadNodeRequest struct {
	Node              *Node `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	WithCommits       bool  `protobuf:"varint,2,opt,name=WithCommits" json:"WithCommits,omitempty"`
	WithExtendedStats bool  `protobuf:"varint,3,opt,name=WithExtendedStats" json:"WithExtendedStats,omitempty"`
}

func (m *ReadNodeRequest) Reset()                    { *m = ReadNodeRequest{} }
func (m *ReadNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadNodeRequest) ProtoMessage()               {}
func (*ReadNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReadNodeRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ReadNodeRequest) GetWithCommits() bool {
	if m != nil {
		return m.WithCommits
	}
	return false
}

func (m *ReadNodeRequest) GetWithExtendedStats() bool {
	if m != nil {
		return m.WithExtendedStats
	}
	return false
}

type ReadNodeResponse struct {
	Success bool  `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Node    *Node `protobuf:"bytes,2,opt,name=Node" json:"Node,omitempty"`
}

func (m *ReadNodeResponse) Reset()                    { *m = ReadNodeResponse{} }
func (m *ReadNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadNodeResponse) ProtoMessage()               {}
func (*ReadNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadNodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ReadNodeResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type ListNodesRequest struct {
	Node         *Node    `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	Recursive    bool     `protobuf:"varint,2,opt,name=Recursive" json:"Recursive,omitempty"`
	Ancestors    bool     `protobuf:"varint,3,opt,name=Ancestors" json:"Ancestors,omitempty"`
	WithVersions bool     `protobuf:"varint,7,opt,name=WithVersions" json:"WithVersions,omitempty"`
	WithCommits  bool     `protobuf:"varint,8,opt,name=WithCommits" json:"WithCommits,omitempty"`
	Limit        int64    `protobuf:"varint,4,opt,name=Limit" json:"Limit,omitempty"`
	Offset       int64    `protobuf:"varint,5,opt,name=Offset" json:"Offset,omitempty"`
	FilterType   NodeType `protobuf:"varint,6,opt,name=FilterType,enum=tree.NodeType" json:"FilterType,omitempty"`
}

func (m *ListNodesRequest) Reset()                    { *m = ListNodesRequest{} }
func (m *ListNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListNodesRequest) ProtoMessage()               {}
func (*ListNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListNodesRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ListNodesRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

func (m *ListNodesRequest) GetAncestors() bool {
	if m != nil {
		return m.Ancestors
	}
	return false
}

func (m *ListNodesRequest) GetWithVersions() bool {
	if m != nil {
		return m.WithVersions
	}
	return false
}

func (m *ListNodesRequest) GetWithCommits() bool {
	if m != nil {
		return m.WithCommits
	}
	return false
}

func (m *ListNodesRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListNodesRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListNodesRequest) GetFilterType() NodeType {
	if m != nil {
		return m.FilterType
	}
	return NodeType_UNKNOWN
}

type ListNodesResponse struct {
	Node *Node `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
}

func (m *ListNodesResponse) Reset()                    { *m = ListNodesResponse{} }
func (m *ListNodesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListNodesResponse) ProtoMessage()               {}
func (*ListNodesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListNodesResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

// Request / Responses Messages
type CreateNodeRequest struct {
	Node              *Node  `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	UpdateIfExists    bool   `protobuf:"varint,2,opt,name=UpdateIfExists" json:"UpdateIfExists,omitempty"`
	IndexationSession string `protobuf:"bytes,3,opt,name=IndexationSession" json:"IndexationSession,omitempty"`
	Silent            bool   `protobuf:"varint,4,opt,name=Silent" json:"Silent,omitempty"`
}

func (m *CreateNodeRequest) Reset()                    { *m = CreateNodeRequest{} }
func (m *CreateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeRequest) ProtoMessage()               {}
func (*CreateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateNodeRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *CreateNodeRequest) GetUpdateIfExists() bool {
	if m != nil {
		return m.UpdateIfExists
	}
	return false
}

func (m *CreateNodeRequest) GetIndexationSession() string {
	if m != nil {
		return m.IndexationSession
	}
	return ""
}

func (m *CreateNodeRequest) GetSilent() bool {
	if m != nil {
		return m.Silent
	}
	return false
}

type CreateNodeResponse struct {
	Success bool  `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Node    *Node `protobuf:"bytes,2,opt,name=Node" json:"Node,omitempty"`
}

func (m *CreateNodeResponse) Reset()                    { *m = CreateNodeResponse{} }
func (m *CreateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateNodeResponse) ProtoMessage()               {}
func (*CreateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateNodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateNodeResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type UpdateNodeRequest struct {
	From              *Node  `protobuf:"bytes,1,opt,name=From" json:"From,omitempty"`
	To                *Node  `protobuf:"bytes,2,opt,name=To" json:"To,omitempty"`
	IndexationSession string `protobuf:"bytes,3,opt,name=IndexationSession" json:"IndexationSession,omitempty"`
	Silent            bool   `protobuf:"varint,4,opt,name=Silent" json:"Silent,omitempty"`
}

func (m *UpdateNodeRequest) Reset()                    { *m = UpdateNodeRequest{} }
func (m *UpdateNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeRequest) ProtoMessage()               {}
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateNodeRequest) GetFrom() *Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *UpdateNodeRequest) GetTo() *Node {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *UpdateNodeRequest) GetIndexationSession() string {
	if m != nil {
		return m.IndexationSession
	}
	return ""
}

func (m *UpdateNodeRequest) GetSilent() bool {
	if m != nil {
		return m.Silent
	}
	return false
}

type UpdateNodeResponse struct {
	Success bool  `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Node    *Node `protobuf:"bytes,2,opt,name=Node" json:"Node,omitempty"`
}

func (m *UpdateNodeResponse) Reset()                    { *m = UpdateNodeResponse{} }
func (m *UpdateNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateNodeResponse) ProtoMessage()               {}
func (*UpdateNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateNodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateNodeResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type DeleteNodeRequest struct {
	Node              *Node  `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	IndexationSession string `protobuf:"bytes,2,opt,name=IndexationSession" json:"IndexationSession,omitempty"`
	Silent            bool   `protobuf:"varint,3,opt,name=Silent" json:"Silent,omitempty"`
}

func (m *DeleteNodeRequest) Reset()                    { *m = DeleteNodeRequest{} }
func (m *DeleteNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeRequest) ProtoMessage()               {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteNodeRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *DeleteNodeRequest) GetIndexationSession() string {
	if m != nil {
		return m.IndexationSession
	}
	return ""
}

func (m *DeleteNodeRequest) GetSilent() bool {
	if m != nil {
		return m.Silent
	}
	return false
}

type DeleteNodeResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *DeleteNodeResponse) Reset()                    { *m = DeleteNodeResponse{} }
func (m *DeleteNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodeResponse) ProtoMessage()               {}
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteNodeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type IndexationSession struct {
	Uuid                    string `protobuf:"bytes,1,opt,name=Uuid" json:"Uuid,omitempty"`
	Description             string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
	RootNode                *Node  `protobuf:"bytes,3,opt,name=RootNode" json:"RootNode,omitempty"`
	ExpectedOperationsCount int64  `protobuf:"varint,4,opt,name=ExpectedOperationsCount" json:"ExpectedOperationsCount,omitempty"`
	CurrentOperationCount   int64  `protobuf:"varint,5,opt,name=CurrentOperationCount" json:"CurrentOperationCount,omitempty"`
}

func (m *IndexationSession) Reset()                    { *m = IndexationSession{} }
func (m *IndexationSession) String() string            { return proto.CompactTextString(m) }
func (*IndexationSession) ProtoMessage()               {}
func (*IndexationSession) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *IndexationSession) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *IndexationSession) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *IndexationSession) GetRootNode() *Node {
	if m != nil {
		return m.RootNode
	}
	return nil
}

func (m *IndexationSession) GetExpectedOperationsCount() int64 {
	if m != nil {
		return m.ExpectedOperationsCount
	}
	return 0
}

func (m *IndexationSession) GetCurrentOperationCount() int64 {
	if m != nil {
		return m.CurrentOperationCount
	}
	return 0
}

type IndexationOperation struct {
	SessionUuid string `protobuf:"bytes,1,opt,name=SessionUuid" json:"SessionUuid,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
	Cursor      int64  `protobuf:"varint,3,opt,name=Cursor" json:"Cursor,omitempty"`
}

func (m *IndexationOperation) Reset()                    { *m = IndexationOperation{} }
func (m *IndexationOperation) String() string            { return proto.CompactTextString(m) }
func (*IndexationOperation) ProtoMessage()               {}
func (*IndexationOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *IndexationOperation) GetSessionUuid() string {
	if m != nil {
		return m.SessionUuid
	}
	return ""
}

func (m *IndexationOperation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *IndexationOperation) GetCursor() int64 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type OpenSessionRequest struct {
	Session *IndexationSession `protobuf:"bytes,1,opt,name=Session" json:"Session,omitempty"`
}

func (m *OpenSessionRequest) Reset()                    { *m = OpenSessionRequest{} }
func (m *OpenSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionRequest) ProtoMessage()               {}
func (*OpenSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *OpenSessionRequest) GetSession() *IndexationSession {
	if m != nil {
		return m.Session
	}
	return nil
}

type OpenSessionResponse struct {
	Session *IndexationSession `protobuf:"bytes,1,opt,name=Session" json:"Session,omitempty"`
}

func (m *OpenSessionResponse) Reset()                    { *m = OpenSessionResponse{} }
func (m *OpenSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*OpenSessionResponse) ProtoMessage()               {}
func (*OpenSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *OpenSessionResponse) GetSession() *IndexationSession {
	if m != nil {
		return m.Session
	}
	return nil
}

type FlushSessionRequest struct {
	Session *IndexationSession `protobuf:"bytes,1,opt,name=Session" json:"Session,omitempty"`
}

func (m *FlushSessionRequest) Reset()                    { *m = FlushSessionRequest{} }
func (m *FlushSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*FlushSessionRequest) ProtoMessage()               {}
func (*FlushSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *FlushSessionRequest) GetSession() *IndexationSession {
	if m != nil {
		return m.Session
	}
	return nil
}

type FlushSessionResponse struct {
	Session *IndexationSession `protobuf:"bytes,1,opt,name=Session" json:"Session,omitempty"`
}

func (m *FlushSessionResponse) Reset()                    { *m = FlushSessionResponse{} }
func (m *FlushSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*FlushSessionResponse) ProtoMessage()               {}
func (*FlushSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *FlushSessionResponse) GetSession() *IndexationSession {
	if m != nil {
		return m.Session
	}
	return nil
}

type CloseSessionRequest struct {
	Session *IndexationSession `protobuf:"bytes,1,opt,name=Session" json:"Session,omitempty"`
}

func (m *CloseSessionRequest) Reset()                    { *m = CloseSessionRequest{} }
func (m *CloseSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionRequest) ProtoMessage()               {}
func (*CloseSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *CloseSessionRequest) GetSession() *IndexationSession {
	if m != nil {
		return m.Session
	}
	return nil
}

type CloseSessionResponse struct {
	Session *IndexationSession `protobuf:"bytes,1,opt,name=Session" json:"Session,omitempty"`
}

func (m *CloseSessionResponse) Reset()                    { *m = CloseSessionResponse{} }
func (m *CloseSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CloseSessionResponse) ProtoMessage()               {}
func (*CloseSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CloseSessionResponse) GetSession() *IndexationSession {
	if m != nil {
		return m.Session
	}
	return nil
}

// Request / Responses Messages
type WatchNodeRequest struct {
	Node *Node `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
}

func (m *WatchNodeRequest) Reset()                    { *m = WatchNodeRequest{} }
func (m *WatchNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchNodeRequest) ProtoMessage()               {}
func (*WatchNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *WatchNodeRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type WatchNodeResponse struct {
	Node *Node `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
}

func (m *WatchNodeResponse) Reset()                    { *m = WatchNodeResponse{} }
func (m *WatchNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*WatchNodeResponse) ProtoMessage()               {}
func (*WatchNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *WatchNodeResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type SearchRequest struct {
	// The query object
	Query *Query `protobuf:"bytes,1,opt,name=Query" json:"Query,omitempty"`
	// Limit the number of results
	Size int32 `protobuf:"varint,2,opt,name=Size" json:"Size,omitempty"`
	// Start at given position
	From int32 `protobuf:"varint,3,opt,name=From" json:"From,omitempty"`
	// Load node details
	Details bool `protobuf:"varint,4,opt,name=Details" json:"Details,omitempty"`
	// Facet search
	Facet string `protobuf:"bytes,5,opt,name=Facet" json:"Facet,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *SearchRequest) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SearchRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SearchRequest) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SearchRequest) GetDetails() bool {
	if m != nil {
		return m.Details
	}
	return false
}

func (m *SearchRequest) GetFacet() string {
	if m != nil {
		return m.Facet
	}
	return ""
}

type SearchResponse struct {
	Node *Node `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *SearchResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type CreateVersionRequest struct {
	Node         *Node            `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	TriggerEvent *NodeChangeEvent `protobuf:"bytes,2,opt,name=TriggerEvent" json:"TriggerEvent,omitempty"`
}

func (m *CreateVersionRequest) Reset()                    { *m = CreateVersionRequest{} }
func (m *CreateVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateVersionRequest) ProtoMessage()               {}
func (*CreateVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *CreateVersionRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *CreateVersionRequest) GetTriggerEvent() *NodeChangeEvent {
	if m != nil {
		return m.TriggerEvent
	}
	return nil
}

type CreateVersionResponse struct {
	Version *ChangeLog `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
}

func (m *CreateVersionResponse) Reset()                    { *m = CreateVersionResponse{} }
func (m *CreateVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateVersionResponse) ProtoMessage()               {}
func (*CreateVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CreateVersionResponse) GetVersion() *ChangeLog {
	if m != nil {
		return m.Version
	}
	return nil
}

type ListVersionsRequest struct {
	Node *Node `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
}

func (m *ListVersionsRequest) Reset()                    { *m = ListVersionsRequest{} }
func (m *ListVersionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListVersionsRequest) ProtoMessage()               {}
func (*ListVersionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ListVersionsRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type ListVersionsResponse struct {
	Version *ChangeLog `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
}

func (m *ListVersionsResponse) Reset()                    { *m = ListVersionsResponse{} }
func (m *ListVersionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListVersionsResponse) ProtoMessage()               {}
func (*ListVersionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ListVersionsResponse) GetVersion() *ChangeLog {
	if m != nil {
		return m.Version
	}
	return nil
}

type HeadVersionRequest struct {
	Node      *Node  `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	VersionId string `protobuf:"bytes,2,opt,name=VersionId" json:"VersionId,omitempty"`
}

func (m *HeadVersionRequest) Reset()                    { *m = HeadVersionRequest{} }
func (m *HeadVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*HeadVersionRequest) ProtoMessage()               {}
func (*HeadVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *HeadVersionRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *HeadVersionRequest) GetVersionId() string {
	if m != nil {
		return m.VersionId
	}
	return ""
}

type HeadVersionResponse struct {
	Version *ChangeLog `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
}

func (m *HeadVersionResponse) Reset()                    { *m = HeadVersionResponse{} }
func (m *HeadVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*HeadVersionResponse) ProtoMessage()               {}
func (*HeadVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *HeadVersionResponse) GetVersion() *ChangeLog {
	if m != nil {
		return m.Version
	}
	return nil
}

type StoreVersionRequest struct {
	Node    *Node      `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
	Version *ChangeLog `protobuf:"bytes,2,opt,name=Version" json:"Version,omitempty"`
}

func (m *StoreVersionRequest) Reset()                    { *m = StoreVersionRequest{} }
func (m *StoreVersionRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreVersionRequest) ProtoMessage()               {}
func (*StoreVersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *StoreVersionRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *StoreVersionRequest) GetVersion() *ChangeLog {
	if m != nil {
		return m.Version
	}
	return nil
}

type StoreVersionResponse struct {
	Success       bool         `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	PruneVersions []*ChangeLog `protobuf:"bytes,2,rep,name=PruneVersions" json:"PruneVersions,omitempty"`
}

func (m *StoreVersionResponse) Reset()                    { *m = StoreVersionResponse{} }
func (m *StoreVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreVersionResponse) ProtoMessage()               {}
func (*StoreVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *StoreVersionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *StoreVersionResponse) GetPruneVersions() []*ChangeLog {
	if m != nil {
		return m.PruneVersions
	}
	return nil
}

type PruneVersionsRequest struct {
	UniqueNode      *Node `protobuf:"bytes,1,opt,name=UniqueNode" json:"UniqueNode,omitempty"`
	AllDeletedNodes bool  `protobuf:"varint,2,opt,name=AllDeletedNodes" json:"AllDeletedNodes,omitempty"`
}

func (m *PruneVersionsRequest) Reset()                    { *m = PruneVersionsRequest{} }
func (m *PruneVersionsRequest) String() string            { return proto.CompactTextString(m) }
func (*PruneVersionsRequest) ProtoMessage()               {}
func (*PruneVersionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PruneVersionsRequest) GetUniqueNode() *Node {
	if m != nil {
		return m.UniqueNode
	}
	return nil
}

func (m *PruneVersionsRequest) GetAllDeletedNodes() bool {
	if m != nil {
		return m.AllDeletedNodes
	}
	return false
}

type PruneVersionsResponse struct {
	DeletedVersions []string `protobuf:"bytes,1,rep,name=DeletedVersions" json:"DeletedVersions,omitempty"`
}

func (m *PruneVersionsResponse) Reset()                    { *m = PruneVersionsResponse{} }
func (m *PruneVersionsResponse) String() string            { return proto.CompactTextString(m) }
func (*PruneVersionsResponse) ProtoMessage()               {}
func (*PruneVersionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *PruneVersionsResponse) GetDeletedVersions() []string {
	if m != nil {
		return m.DeletedVersions
	}
	return nil
}

type VersioningPolicy struct {
	Uuid                     string                  `protobuf:"bytes,1,opt,name=Uuid" json:"Uuid,omitempty"`
	Name                     string                  `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Description              string                  `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	VersionsDataSourceName   string                  `protobuf:"bytes,4,opt,name=VersionsDataSourceName" json:"VersionsDataSourceName,omitempty"`
	VersionsDataSourceBucket string                  `protobuf:"bytes,5,opt,name=VersionsDataSourceBucket" json:"VersionsDataSourceBucket,omitempty"`
	MaxTotalSize             int64                   `protobuf:"varint,6,opt,name=MaxTotalSize" json:"MaxTotalSize,omitempty"`
	MaxSizePerFile           int64                   `protobuf:"varint,7,opt,name=MaxSizePerFile" json:"MaxSizePerFile,omitempty"`
	IgnoreFilesGreaterThan   int64                   `protobuf:"varint,8,opt,name=IgnoreFilesGreaterThan" json:"IgnoreFilesGreaterThan,omitempty"`
	KeepPeriods              []*VersioningKeepPeriod `protobuf:"bytes,9,rep,name=KeepPeriods" json:"KeepPeriods,omitempty"`
}

func (m *VersioningPolicy) Reset()                    { *m = VersioningPolicy{} }
func (m *VersioningPolicy) String() string            { return proto.CompactTextString(m) }
func (*VersioningPolicy) ProtoMessage()               {}
func (*VersioningPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *VersioningPolicy) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *VersioningPolicy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VersioningPolicy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *VersioningPolicy) GetVersionsDataSourceName() string {
	if m != nil {
		return m.VersionsDataSourceName
	}
	return ""
}

func (m *VersioningPolicy) GetVersionsDataSourceBucket() string {
	if m != nil {
		return m.VersionsDataSourceBucket
	}
	return ""
}

func (m *VersioningPolicy) GetMaxTotalSize() int64 {
	if m != nil {
		return m.MaxTotalSize
	}
	return 0
}

func (m *VersioningPolicy) GetMaxSizePerFile() int64 {
	if m != nil {
		return m.MaxSizePerFile
	}
	return 0
}

func (m *VersioningPolicy) GetIgnoreFilesGreaterThan() int64 {
	if m != nil {
		return m.IgnoreFilesGreaterThan
	}
	return 0
}

func (m *VersioningPolicy) GetKeepPeriods() []*VersioningKeepPeriod {
	if m != nil {
		return m.KeepPeriods
	}
	return nil
}

type VersioningKeepPeriod struct {
	IntervalStart string `protobuf:"bytes,1,opt,name=IntervalStart" json:"IntervalStart,omitempty"`
	MaxNumber     int32  `protobuf:"varint,3,opt,name=MaxNumber" json:"MaxNumber,omitempty"`
}

func (m *VersioningKeepPeriod) Reset()                    { *m = VersioningKeepPeriod{} }
func (m *VersioningKeepPeriod) String() string            { return proto.CompactTextString(m) }
func (*VersioningKeepPeriod) ProtoMessage()               {}
func (*VersioningKeepPeriod) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *VersioningKeepPeriod) GetIntervalStart() string {
	if m != nil {
		return m.IntervalStart
	}
	return ""
}

func (m *VersioningKeepPeriod) GetMaxNumber() int32 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

type Node struct {
	// ------------------------------------
	// Core identification of the node
	// ------------------------------------
	Uuid string   `protobuf:"bytes,1,opt,name=Uuid" json:"Uuid,omitempty"`
	Path string   `protobuf:"bytes,2,opt,name=Path" json:"Path,omitempty"`
	Type NodeType `protobuf:"varint,3,opt,name=Type,enum=tree.NodeType" json:"Type,omitempty"`
	// Size of the file, or cumulated size of folder
	Size int64 `protobuf:"varint,4,opt,name=Size" json:"Size,omitempty"`
	// Last modification Timestamp
	MTime int64 `protobuf:"varint,5,opt,name=MTime" json:"MTime,omitempty"`
	// Permission mode, like 0777
	Mode int32 `protobuf:"varint,6,opt,name=Mode" json:"Mode,omitempty"`
	// Hash of the content if node is a LEAF, Uuid or
	Etag string `protobuf:"bytes,7,opt,name=Etag" json:"Etag,omitempty"`
	// List of successive commits
	Commits []*ChangeLog `protobuf:"bytes,9,rep,name=Commits" json:"Commits,omitempty"`
	// ------------------------------------
	// Then a free K => V representation of any kind of metadata
	// ------------------------------------
	MetaStore map[string]string `protobuf:"bytes,8,rep,name=MetaStore" json:"MetaStore,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Can be used for output when node is appearing in multiple workspaces
	AppearsIn []*WorkspaceRelativePath `protobuf:"bytes,10,rep,name=AppearsIn" json:"AppearsIn,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *Node) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Node) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Node) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_UNKNOWN
}

func (m *Node) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Node) GetMTime() int64 {
	if m != nil {
		return m.MTime
	}
	return 0
}

func (m *Node) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *Node) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *Node) GetCommits() []*ChangeLog {
	if m != nil {
		return m.Commits
	}
	return nil
}

func (m *Node) GetMetaStore() map[string]string {
	if m != nil {
		return m.MetaStore
	}
	return nil
}

func (m *Node) GetAppearsIn() []*WorkspaceRelativePath {
	if m != nil {
		return m.AppearsIn
	}
	return nil
}

// Used in AppearsIn to signal a node is
// appearing in multiple workspaces in the current context
type WorkspaceRelativePath struct {
	// Workspace Id
	WsUuid string `protobuf:"bytes,1,opt,name=WsUuid" json:"WsUuid,omitempty"`
	// Workspace Label
	WsLabel string `protobuf:"bytes,2,opt,name=WsLabel" json:"WsLabel,omitempty"`
	// Relative Path inside workspace
	Path string `protobuf:"bytes,3,opt,name=Path" json:"Path,omitempty"`
}

func (m *WorkspaceRelativePath) Reset()                    { *m = WorkspaceRelativePath{} }
func (m *WorkspaceRelativePath) String() string            { return proto.CompactTextString(m) }
func (*WorkspaceRelativePath) ProtoMessage()               {}
func (*WorkspaceRelativePath) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *WorkspaceRelativePath) GetWsUuid() string {
	if m != nil {
		return m.WsUuid
	}
	return ""
}

func (m *WorkspaceRelativePath) GetWsLabel() string {
	if m != nil {
		return m.WsLabel
	}
	return ""
}

func (m *WorkspaceRelativePath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ChangeLog struct {
	// Unique commit ID
	Uuid string `protobuf:"bytes,1,opt,name=Uuid" json:"Uuid,omitempty"`
	// Human-readable description of what happened
	Description string `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
	// Unix Timestamp
	MTime int64 `protobuf:"varint,3,opt,name=MTime" json:"MTime,omitempty"`
	// Content Size at that moment
	Size int64 `protobuf:"varint,4,opt,name=Size" json:"Size,omitempty"`
	// Arbitrary additional data
	Data []byte `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
	// Who performed this action
	OwnerUuid string `protobuf:"bytes,6,opt,name=OwnerUuid" json:"OwnerUuid,omitempty"`
	// Event that triggered this change
	Event *NodeChangeEvent `protobuf:"bytes,7,opt,name=Event" json:"Event,omitempty"`
}

func (m *ChangeLog) Reset()                    { *m = ChangeLog{} }
func (m *ChangeLog) String() string            { return proto.CompactTextString(m) }
func (*ChangeLog) ProtoMessage()               {}
func (*ChangeLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *ChangeLog) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ChangeLog) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ChangeLog) GetMTime() int64 {
	if m != nil {
		return m.MTime
	}
	return 0
}

func (m *ChangeLog) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ChangeLog) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ChangeLog) GetOwnerUuid() string {
	if m != nil {
		return m.OwnerUuid
	}
	return ""
}

func (m *ChangeLog) GetEvent() *NodeChangeEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

// Search Queries
type Query struct {
	// Limit to a given subtree
	PathPrefix []string `protobuf:"bytes,1,rep,name=PathPrefix" json:"PathPrefix,omitempty"`
	// Range for size
	MinSize int64 `protobuf:"varint,2,opt,name=MinSize" json:"MinSize,omitempty"`
	MaxSize int64 `protobuf:"varint,3,opt,name=MaxSize" json:"MaxSize,omitempty"`
	// Range for date
	MinDate int64 `protobuf:"varint,4,opt,name=MinDate" json:"MinDate,omitempty"`
	MaxDate int64 `protobuf:"varint,5,opt,name=MaxDate" json:"MaxDate,omitempty"`
	// Limit to a given node type
	Type NodeType `protobuf:"varint,6,opt,name=Type,enum=tree.NodeType" json:"Type,omitempty"`
	// Search in filename
	FileName string `protobuf:"bytes,7,opt,name=FileName" json:"FileName,omitempty"`
	// Search in content
	Content string `protobuf:"bytes,8,opt,name=Content" json:"Content,omitempty"`
	// Free Query String (for metadata)
	FreeString string `protobuf:"bytes,9,opt,name=FreeString" json:"FreeString,omitempty"`
	// Search files by extension
	Extension string `protobuf:"bytes,10,opt,name=Extension" json:"Extension,omitempty"`
	// Search geographically
	GeoQuery *GeoQuery `protobuf:"bytes,11,opt,name=GeoQuery" json:"GeoQuery,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *Query) GetPathPrefix() []string {
	if m != nil {
		return m.PathPrefix
	}
	return nil
}

func (m *Query) GetMinSize() int64 {
	if m != nil {
		return m.MinSize
	}
	return 0
}

func (m *Query) GetMaxSize() int64 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *Query) GetMinDate() int64 {
	if m != nil {
		return m.MinDate
	}
	return 0
}

func (m *Query) GetMaxDate() int64 {
	if m != nil {
		return m.MaxDate
	}
	return 0
}

func (m *Query) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_UNKNOWN
}

func (m *Query) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Query) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Query) GetFreeString() string {
	if m != nil {
		return m.FreeString
	}
	return ""
}

func (m *Query) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

func (m *Query) GetGeoQuery() *GeoQuery {
	if m != nil {
		return m.GeoQuery
	}
	return nil
}

type GeoQuery struct {
	// Either use a center point and a distance
	Center *GeoPoint `protobuf:"bytes,1,opt,name=Center" json:"Center,omitempty"`
	// Example formats supported:
	// "5in" "5inch" "7yd" "7yards" "9ft" "9feet" "11km" "11kilometers"
	// "3nm" "3nauticalmiles" "13mm" "13millimeters" "15cm" "15centimeters"
	// "17mi" "17miles" "19m" "19meters"
	// If the unit cannot be determined, the entire string is parsed and the
	// unit of meters is assumed.
	Distance string `protobuf:"bytes,2,opt,name=Distance" json:"Distance,omitempty"`
	// Or use a bounding box with TopLeft and BottomRight points
	TopLeft     *GeoPoint `protobuf:"bytes,3,opt,name=TopLeft" json:"TopLeft,omitempty"`
	BottomRight *GeoPoint `protobuf:"bytes,4,opt,name=BottomRight" json:"BottomRight,omitempty"`
}

func (m *GeoQuery) Reset()                    { *m = GeoQuery{} }
func (m *GeoQuery) String() string            { return proto.CompactTextString(m) }
func (*GeoQuery) ProtoMessage()               {}
func (*GeoQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *GeoQuery) GetCenter() *GeoPoint {
	if m != nil {
		return m.Center
	}
	return nil
}

func (m *GeoQuery) GetDistance() string {
	if m != nil {
		return m.Distance
	}
	return ""
}

func (m *GeoQuery) GetTopLeft() *GeoPoint {
	if m != nil {
		return m.TopLeft
	}
	return nil
}

func (m *GeoQuery) GetBottomRight() *GeoPoint {
	if m != nil {
		return m.BottomRight
	}
	return nil
}

type GeoPoint struct {
	Lat float64 `protobuf:"fixed64,1,opt,name=Lat" json:"Lat,omitempty"`
	Lon float64 `protobuf:"fixed64,2,opt,name=Lon" json:"Lon,omitempty"`
}

func (m *GeoPoint) Reset()                    { *m = GeoPoint{} }
func (m *GeoPoint) String() string            { return proto.CompactTextString(m) }
func (*GeoPoint) ProtoMessage()               {}
func (*GeoPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *GeoPoint) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *GeoPoint) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type NodeChangeEvent struct {
	Type   NodeChangeEvent_EventType `protobuf:"varint,1,opt,name=Type,enum=tree.NodeChangeEvent_EventType" json:"Type,omitempty"`
	Source *Node                     `protobuf:"bytes,2,opt,name=Source" json:"Source,omitempty"`
	Target *Node                     `protobuf:"bytes,3,opt,name=Target" json:"Target,omitempty"`
	Silent bool                      `protobuf:"varint,4,opt,name=Silent" json:"Silent,omitempty"`
}

func (m *NodeChangeEvent) Reset()                    { *m = NodeChangeEvent{} }
func (m *NodeChangeEvent) String() string            { return proto.CompactTextString(m) }
func (*NodeChangeEvent) ProtoMessage()               {}
func (*NodeChangeEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *NodeChangeEvent) GetType() NodeChangeEvent_EventType {
	if m != nil {
		return m.Type
	}
	return NodeChangeEvent_CREATE
}

func (m *NodeChangeEvent) GetSource() *Node {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *NodeChangeEvent) GetTarget() *Node {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *NodeChangeEvent) GetSilent() bool {
	if m != nil {
		return m.Silent
	}
	return false
}

type IndexEvent struct {
	ErrorDetected     bool   `protobuf:"varint,1,opt,name=ErrorDetected" json:"ErrorDetected,omitempty"`
	DataSourceName    string `protobuf:"bytes,2,opt,name=DataSourceName" json:"DataSourceName,omitempty"`
	ErrorPath         string `protobuf:"bytes,3,opt,name=ErrorPath" json:"ErrorPath,omitempty"`
	SessionForceClose string `protobuf:"bytes,4,opt,name=SessionForceClose" json:"SessionForceClose,omitempty"`
}

func (m *IndexEvent) Reset()                    { *m = IndexEvent{} }
func (m *IndexEvent) String() string            { return proto.CompactTextString(m) }
func (*IndexEvent) ProtoMessage()               {}
func (*IndexEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *IndexEvent) GetErrorDetected() bool {
	if m != nil {
		return m.ErrorDetected
	}
	return false
}

func (m *IndexEvent) GetDataSourceName() string {
	if m != nil {
		return m.DataSourceName
	}
	return ""
}

func (m *IndexEvent) GetErrorPath() string {
	if m != nil {
		return m.ErrorPath
	}
	return ""
}

func (m *IndexEvent) GetSessionForceClose() string {
	if m != nil {
		return m.SessionForceClose
	}
	return ""
}

type GetEncryptionKeyRequest struct {
	User     string `protobuf:"bytes,1,opt,name=User" json:"User,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	Node     *Node  `protobuf:"bytes,3,opt,name=Node" json:"Node,omitempty"`
	Create   bool   `protobuf:"varint,5,opt,name=Create" json:"Create,omitempty"`
}

func (m *GetEncryptionKeyRequest) Reset()                    { *m = GetEncryptionKeyRequest{} }
func (m *GetEncryptionKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEncryptionKeyRequest) ProtoMessage()               {}
func (*GetEncryptionKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *GetEncryptionKeyRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *GetEncryptionKeyRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GetEncryptionKeyRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *GetEncryptionKeyRequest) GetCreate() bool {
	if m != nil {
		return m.Create
	}
	return false
}

type GetEncryptionKeyResponse struct {
	Key []byte `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
}

func (m *GetEncryptionKeyResponse) Reset()                    { *m = GetEncryptionKeyResponse{} }
func (m *GetEncryptionKeyResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEncryptionKeyResponse) ProtoMessage()               {}
func (*GetEncryptionKeyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *GetEncryptionKeyResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type SyncChange struct {
	Seq    uint64          `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	NodeId string          `protobuf:"bytes,2,opt,name=nodeId,json=node_id" json:"nodeId,omitempty"`
	Type   SyncChange_Type `protobuf:"varint,3,opt,name=type,enum=tree.SyncChange_Type" json:"type,omitempty"`
	Source string          `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	Target string          `protobuf:"bytes,5,opt,name=target" json:"target,omitempty"`
	Node   *SyncChangeNode `protobuf:"bytes,6,opt,name=node" json:"node,omitempty"`
}

func (m *SyncChange) Reset()                    { *m = SyncChange{} }
func (m *SyncChange) String() string            { return proto.CompactTextString(m) }
func (*SyncChange) ProtoMessage()               {}
func (*SyncChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *SyncChange) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SyncChange) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *SyncChange) GetType() SyncChange_Type {
	if m != nil {
		return m.Type
	}
	return SyncChange_unknown
}

func (m *SyncChange) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SyncChange) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *SyncChange) GetNode() *SyncChangeNode {
	if m != nil {
		return m.Node
	}
	return nil
}

type SyncChangeNode struct {
	Bytesize             int64  `protobuf:"varint,1,opt,name=bytesize" json:"bytesize,omitempty"`
	Md5                  string `protobuf:"bytes,2,opt,name=md5" json:"md5,omitempty"`
	Mtime                int64  `protobuf:"varint,3,opt,name=mtime" json:"mtime,omitempty"`
	NodePath             string `protobuf:"bytes,4,opt,name=nodePath,json=node_path" json:"nodePath,omitempty"`
	RepositoryIdentifier string `protobuf:"bytes,5,opt,name=repositoryIdentifier,json=repository_identifier" json:"repositoryIdentifier,omitempty"`
}

func (m *SyncChangeNode) Reset()                    { *m = SyncChangeNode{} }
func (m *SyncChangeNode) String() string            { return proto.CompactTextString(m) }
func (*SyncChangeNode) ProtoMessage()               {}
func (*SyncChangeNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *SyncChangeNode) GetBytesize() int64 {
	if m != nil {
		return m.Bytesize
	}
	return 0
}

func (m *SyncChangeNode) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *SyncChangeNode) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *SyncChangeNode) GetNodePath() string {
	if m != nil {
		return m.NodePath
	}
	return ""
}

func (m *SyncChangeNode) GetRepositoryIdentifier() string {
	if m != nil {
		return m.RepositoryIdentifier
	}
	return ""
}

type PutSyncChangeResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *PutSyncChangeResponse) Reset()                    { *m = PutSyncChangeResponse{} }
func (m *PutSyncChangeResponse) String() string            { return proto.CompactTextString(m) }
func (*PutSyncChangeResponse) ProtoMessage()               {}
func (*PutSyncChangeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *PutSyncChangeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PutSyncChangeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SearchSyncChangeRequest struct {
	Seq         uint64 `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
	Flatten     bool   `protobuf:"varint,2,opt,name=flatten" json:"flatten,omitempty"`
	Prefix      string `protobuf:"bytes,3,opt,name=prefix" json:"prefix,omitempty"`
	LastSeqOnly bool   `protobuf:"varint,4,opt,name=lastSeqOnly" json:"lastSeqOnly,omitempty"`
}

func (m *SearchSyncChangeRequest) Reset()                    { *m = SearchSyncChangeRequest{} }
func (m *SearchSyncChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchSyncChangeRequest) ProtoMessage()               {}
func (*SearchSyncChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *SearchSyncChangeRequest) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SearchSyncChangeRequest) GetFlatten() bool {
	if m != nil {
		return m.Flatten
	}
	return false
}

func (m *SearchSyncChangeRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *SearchSyncChangeRequest) GetLastSeqOnly() bool {
	if m != nil {
		return m.LastSeqOnly
	}
	return false
}

func init() {
	proto.RegisterType((*ReadNodeRequest)(nil), "tree.ReadNodeRequest")
	proto.RegisterType((*ReadNodeResponse)(nil), "tree.ReadNodeResponse")
	proto.RegisterType((*ListNodesRequest)(nil), "tree.ListNodesRequest")
	proto.RegisterType((*ListNodesResponse)(nil), "tree.ListNodesResponse")
	proto.RegisterType((*CreateNodeRequest)(nil), "tree.CreateNodeRequest")
	proto.RegisterType((*CreateNodeResponse)(nil), "tree.CreateNodeResponse")
	proto.RegisterType((*UpdateNodeRequest)(nil), "tree.UpdateNodeRequest")
	proto.RegisterType((*UpdateNodeResponse)(nil), "tree.UpdateNodeResponse")
	proto.RegisterType((*DeleteNodeRequest)(nil), "tree.DeleteNodeRequest")
	proto.RegisterType((*DeleteNodeResponse)(nil), "tree.DeleteNodeResponse")
	proto.RegisterType((*IndexationSession)(nil), "tree.IndexationSession")
	proto.RegisterType((*IndexationOperation)(nil), "tree.IndexationOperation")
	proto.RegisterType((*OpenSessionRequest)(nil), "tree.OpenSessionRequest")
	proto.RegisterType((*OpenSessionResponse)(nil), "tree.OpenSessionResponse")
	proto.RegisterType((*FlushSessionRequest)(nil), "tree.FlushSessionRequest")
	proto.RegisterType((*FlushSessionResponse)(nil), "tree.FlushSessionResponse")
	proto.RegisterType((*CloseSessionRequest)(nil), "tree.CloseSessionRequest")
	proto.RegisterType((*CloseSessionResponse)(nil), "tree.CloseSessionResponse")
	proto.RegisterType((*WatchNodeRequest)(nil), "tree.WatchNodeRequest")
	proto.RegisterType((*WatchNodeResponse)(nil), "tree.WatchNodeResponse")
	proto.RegisterType((*SearchRequest)(nil), "tree.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "tree.SearchResponse")
	proto.RegisterType((*CreateVersionRequest)(nil), "tree.CreateVersionRequest")
	proto.RegisterType((*CreateVersionResponse)(nil), "tree.CreateVersionResponse")
	proto.RegisterType((*ListVersionsRequest)(nil), "tree.ListVersionsRequest")
	proto.RegisterType((*ListVersionsResponse)(nil), "tree.ListVersionsResponse")
	proto.RegisterType((*HeadVersionRequest)(nil), "tree.HeadVersionRequest")
	proto.RegisterType((*HeadVersionResponse)(nil), "tree.HeadVersionResponse")
	proto.RegisterType((*StoreVersionRequest)(nil), "tree.StoreVersionRequest")
	proto.RegisterType((*StoreVersionResponse)(nil), "tree.StoreVersionResponse")
	proto.RegisterType((*PruneVersionsRequest)(nil), "tree.PruneVersionsRequest")
	proto.RegisterType((*PruneVersionsResponse)(nil), "tree.PruneVersionsResponse")
	proto.RegisterType((*VersioningPolicy)(nil), "tree.VersioningPolicy")
	proto.RegisterType((*VersioningKeepPeriod)(nil), "tree.VersioningKeepPeriod")
	proto.RegisterType((*Node)(nil), "tree.Node")
	proto.RegisterType((*WorkspaceRelativePath)(nil), "tree.WorkspaceRelativePath")
	proto.RegisterType((*ChangeLog)(nil), "tree.ChangeLog")
	proto.RegisterType((*Query)(nil), "tree.Query")
	proto.RegisterType((*GeoQuery)(nil), "tree.GeoQuery")
	proto.RegisterType((*GeoPoint)(nil), "tree.GeoPoint")
	proto.RegisterType((*NodeChangeEvent)(nil), "tree.NodeChangeEvent")
	proto.RegisterType((*IndexEvent)(nil), "tree.IndexEvent")
	proto.RegisterType((*GetEncryptionKeyRequest)(nil), "tree.GetEncryptionKeyRequest")
	proto.RegisterType((*GetEncryptionKeyResponse)(nil), "tree.GetEncryptionKeyResponse")
	proto.RegisterType((*SyncChange)(nil), "tree.SyncChange")
	proto.RegisterType((*SyncChangeNode)(nil), "tree.SyncChangeNode")
	proto.RegisterType((*PutSyncChangeResponse)(nil), "tree.PutSyncChangeResponse")
	proto.RegisterType((*SearchSyncChangeRequest)(nil), "tree.SearchSyncChangeRequest")
	proto.RegisterEnum("tree.NodeType", NodeType_name, NodeType_value)
	proto.RegisterEnum("tree.NodeChangeEvent_EventType", NodeChangeEvent_EventType_name, NodeChangeEvent_EventType_value)
	proto.RegisterEnum("tree.SyncChange_Type", SyncChange_Type_name, SyncChange_Type_value)
}

func init() { proto.RegisterFile("tree.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x19, 0xcb, 0x6e, 0x1b, 0xc9,
	0x51, 0xc3, 0xa1, 0x28, 0xb2, 0xf4, 0xa2, 0x5a, 0x94, 0xc5, 0xa5, 0x77, 0x1d, 0x65, 0xb0, 0x30,
	0xb4, 0x8e, 0x21, 0x78, 0xe5, 0x38, 0xeb, 0xdd, 0x6c, 0x00, 0xd3, 0x14, 0x65, 0x2b, 0x7a, 0x31,
	0x43, 0x7a, 0x05, 0x04, 0x58, 0x38, 0x63, 0xb2, 0x44, 0x0d, 0x4c, 0xce, 0x50, 0x3d, 0x4d, 0x59,
	0xcc, 0x25, 0xf1, 0x25, 0x87, 0x04, 0xb9, 0x2c, 0x90, 0x0f, 0xc8, 0x25, 0x87, 0x7c, 0x4a, 0xae,
	0x39, 0xe4, 0x9c, 0x5b, 0xfe, 0x21, 0x97, 0x45, 0xbf, 0xe6, 0xc1, 0x19, 0xad, 0x25, 0x7b, 0x2f,
	0xc4, 0xd4, 0xa3, 0xab, 0xeb, 0xd5, 0x5d, 0xd5, 0x45, 0x00, 0x46, 0x11, 0xb7, 0x46, 0xd4, 0x67,
	0x3e, 0xc9, 0xf3, 0x6f, 0xeb, 0xad, 0x01, 0xcb, 0x36, 0x3a, 0xbd, 0x23, 0xbf, 0x87, 0x36, 0x9e,
	0x8f, 0x31, 0x60, 0xe4, 0x0e, 0xe4, 0x39, 0x58, 0x35, 0x36, 0x8c, 0xcd, 0xf9, 0x6d, 0xd8, 0x12,
	0x8b, 0x04, 0x83, 0xc0, 0x93, 0x0d, 0x98, 0x3f, 0x71, 0xd9, 0x59, 0xc3, 0x1f, 0x0e, 0x5d, 0x16,
	0x54, 0x73, 0x1b, 0xc6, 0x66, 0xd1, 0x8e, 0xa3, 0xc8, 0x7d, 0x58, 0xe1, 0x60, 0xf3, 0x92, 0xa1,
	0xd7, 0xc3, 0x5e, 0x9b, 0x39, 0x2c, 0xa8, 0x9a, 0x82, 0x2f, 0x4d, 0xb0, 0x0e, 0xa0, 0x1c, 0xa9,
	0x10, 0x8c, 0x7c, 0x2f, 0x40, 0x52, 0x85, 0xb9, 0xf6, 0xb8, 0xdb, 0xc5, 0x20, 0x10, 0x6a, 0x14,
	0x6d, 0x0d, 0x86, 0xda, 0xe5, 0xb2, 0xb5, 0xb3, 0xbe, 0xcb, 0x41, 0xf9, 0xc0, 0x0d, 0x18, 0x07,
	0x82, 0xeb, 0x9a, 0xf4, 0x31, 0x94, 0x6c, 0xec, 0x8e, 0x69, 0xe0, 0x5e, 0xa0, 0x32, 0x28, 0x42,
	0x70, 0x6a, 0xdd, 0xeb, 0x62, 0xc0, 0x7c, 0xaa, 0xcd, 0x88, 0x10, 0xc4, 0x82, 0x05, 0x6e, 0xd3,
	0x37, 0x48, 0x03, 0xd7, 0xf7, 0x82, 0xea, 0x9c, 0x60, 0x48, 0xe0, 0xa6, 0x5d, 0x56, 0x4c, 0xbb,
	0xac, 0x02, 0xb3, 0x07, 0xee, 0xd0, 0x65, 0xd5, 0xfc, 0x86, 0xb1, 0x69, 0xda, 0x12, 0x20, 0xb7,
	0xa0, 0x70, 0x7c, 0x7a, 0x1a, 0x20, 0xab, 0xce, 0x0a, 0xb4, 0x82, 0xc8, 0x16, 0xc0, 0xae, 0x3b,
	0x60, 0x48, 0x3b, 0x93, 0x11, 0x56, 0x0b, 0x1b, 0xc6, 0xe6, 0xd2, 0xf6, 0x52, 0x64, 0x15, 0xc7,
	0xda, 0x31, 0x0e, 0xeb, 0x21, 0xac, 0xc4, 0x7c, 0xa2, 0x7c, 0xfc, 0x0e, 0xa7, 0x58, 0x7f, 0x37,
	0x60, 0xa5, 0x41, 0xd1, 0x61, 0x78, 0x93, 0xec, 0xb8, 0x0b, 0x4b, 0x2f, 0x46, 0x3d, 0x87, 0xe1,
	0xde, 0x69, 0xf3, 0xd2, 0x0d, 0xc2, 0x04, 0x99, 0xc2, 0xf2, 0x1c, 0xd9, 0xf3, 0x7a, 0x78, 0xe9,
	0x30, 0xd7, 0xf7, 0xda, 0x18, 0x70, 0x47, 0x09, 0xe7, 0x96, 0xec, 0x34, 0x81, 0x3b, 0xa2, 0xed,
	0x0e, 0xd0, 0x93, 0xfe, 0x29, 0xda, 0x0a, 0xb2, 0x8e, 0x80, 0xc4, 0x55, 0xfc, 0xe0, 0xec, 0xf9,
	0x9b, 0x01, 0x2b, 0x52, 0xd1, 0x29, 0x9b, 0x77, 0xa9, 0x3f, 0xcc, 0xb2, 0x99, 0xe3, 0x49, 0x0d,
	0x72, 0x1d, 0x3f, 0x43, 0x66, 0xae, 0xe3, 0xff, 0x78, 0x76, 0xc6, 0xd5, 0xfa, 0x60, 0x3b, 0x27,
	0xb0, 0xb2, 0x83, 0x03, 0xbc, 0x59, 0x68, 0x33, 0x4d, 0xc9, 0xbd, 0xdb, 0x14, 0x33, 0x61, 0xca,
	0x16, 0x90, 0xf8, 0xd6, 0xef, 0x32, 0xc5, 0xfa, 0xaf, 0x91, 0xb1, 0x2d, 0x21, 0x90, 0x7f, 0x31,
	0x76, 0x7b, 0x82, 0xb9, 0x64, 0x8b, 0x6f, 0x7e, 0xca, 0x76, 0x30, 0xe8, 0x52, 0x77, 0xc4, 0x22,
	0xcd, 0xe2, 0x28, 0x72, 0x17, 0x8a, 0xb6, 0xef, 0x8b, 0x73, 0x20, 0xb4, 0x4a, 0x5a, 0x19, 0xd2,
	0xc8, 0x63, 0x58, 0x6f, 0x5e, 0x8e, 0xb0, 0xcb, 0xb0, 0x77, 0x3c, 0x42, 0x2a, 0x76, 0x0e, 0x1a,
	0xfe, 0xd8, 0xd3, 0xe7, 0xf3, 0x2a, 0x32, 0xf9, 0x39, 0xac, 0x35, 0xc6, 0x94, 0xa2, 0xc7, 0x42,
	0x8a, 0x5c, 0x27, 0x0f, 0x70, 0x36, 0xd1, 0x3a, 0x87, 0xd5, 0xc8, 0xc4, 0x90, 0xc6, 0x0d, 0x52,
	0xf6, 0xc6, 0x6c, 0x8d, 0xa3, 0xae, 0x61, 0xf2, 0x2d, 0x28, 0x34, 0xc6, 0x34, 0xf0, 0xa9, 0x30,
	0xd8, 0xb4, 0x15, 0x64, 0x3d, 0x03, 0x72, 0x3c, 0x42, 0xed, 0x4f, 0x9d, 0x02, 0x9f, 0xc3, 0x9c,
	0x0e, 0xac, 0xcc, 0x82, 0x75, 0xe9, 0x9f, 0x54, 0x00, 0x6c, 0xcd, 0x67, 0x3d, 0x87, 0xd5, 0x84,
	0x20, 0x15, 0xd0, 0xf7, 0x93, 0xb4, 0x3b, 0x18, 0x07, 0x67, 0x1f, 0xae, 0xd3, 0x1e, 0x54, 0x92,
	0x92, 0x3e, 0x48, 0xa9, 0xc6, 0xc0, 0x0f, 0xf0, 0x47, 0x51, 0x2a, 0x29, 0xe9, 0xfd, 0x95, 0xda,
	0x86, 0xf2, 0x89, 0xc3, 0xba, 0x67, 0x37, 0x38, 0xbd, 0xbc, 0x06, 0xc4, 0xd6, 0x5c, 0xb3, 0x06,
	0xfc, 0xd9, 0x80, 0xc5, 0x36, 0x3a, 0xb4, 0x7b, 0xa6, 0xb7, 0xf9, 0x29, 0xcc, 0xfe, 0x66, 0x8c,
	0x74, 0xa2, 0x96, 0xcc, 0xcb, 0x25, 0x02, 0x65, 0x4b, 0x0a, 0x3f, 0x9b, 0x6d, 0xf7, 0xf7, 0xf2,
	0xf2, 0x99, 0xb5, 0xc5, 0x37, 0xc7, 0x89, 0x2b, 0xd4, 0x94, 0x38, 0x71, 0x6d, 0x56, 0x61, 0x6e,
	0x07, 0x99, 0xe3, 0x0e, 0x02, 0x75, 0xdb, 0x69, 0x90, 0x57, 0xc3, 0x5d, 0xa7, 0xab, 0xca, 0x5e,
	0xc9, 0x96, 0x80, 0xf5, 0x00, 0x96, 0xb4, 0x2e, 0xd7, 0x54, 0xff, 0x1c, 0x2a, 0xb2, 0x3c, 0xa8,
	0x4a, 0x7c, 0xdd, 0x9b, 0xee, 0x4b, 0x58, 0xe8, 0x50, 0xb7, 0xdf, 0x47, 0xda, 0xbc, 0xe0, 0x37,
	0x98, 0xbc, 0x46, 0xd7, 0x22, 0xbe, 0xc6, 0x99, 0xe3, 0xf5, 0x51, 0x10, 0xed, 0x04, 0xab, 0xf5,
	0x14, 0xd6, 0xa6, 0xb6, 0x54, 0xba, 0x7e, 0x06, 0x73, 0x0a, 0xa5, 0xb6, 0x5d, 0x96, 0xe2, 0xa4,
	0xa8, 0x03, 0xbf, 0x6f, 0x6b, 0xba, 0xf5, 0x08, 0x56, 0x79, 0xb9, 0xd6, 0xed, 0xc3, 0x75, 0x23,
	0x5c, 0x87, 0x4a, 0x72, 0xd9, 0xcd, 0x77, 0xb6, 0x81, 0x3c, 0x47, 0xa7, 0x77, 0x43, 0x77, 0x7d,
	0x0c, 0x25, 0xb5, 0x62, 0xaf, 0xa7, 0xee, 0xa0, 0x08, 0x61, 0x3d, 0x81, 0xd5, 0x84, 0xcc, 0x9b,
	0x6b, 0xf5, 0x3b, 0x58, 0x6d, 0x33, 0x9f, 0xde, 0x34, 0x8a, 0xb1, 0x1d, 0x72, 0xef, 0xd8, 0xa1,
	0x0f, 0x95, 0xe4, 0x0e, 0xef, 0xac, 0xb0, 0x8f, 0x60, 0xb1, 0x45, 0xc7, 0x1e, 0x86, 0x7d, 0x5f,
	0x6e, 0xc3, 0xcc, 0xda, 0x22, 0xc9, 0x65, 0x0d, 0xa0, 0x92, 0x40, 0x68, 0x5b, 0xee, 0x01, 0xbc,
	0xf0, 0xdc, 0xf3, 0x31, 0x5e, 0x61, 0x51, 0x8c, 0x4a, 0x36, 0x61, 0xb9, 0x3e, 0x18, 0xc8, 0x22,
	0x2a, 0xda, 0x66, 0xdd, 0x63, 0x4d, 0xa3, 0xad, 0x3a, 0xac, 0x4d, 0xed, 0xa6, 0xec, 0xda, 0x84,
	0x65, 0xc5, 0x18, 0xea, 0x6f, 0x6c, 0x98, 0x9b, 0x25, 0x7b, 0x1a, 0x6d, 0x7d, 0x67, 0x42, 0x59,
	0x01, 0xae, 0xd7, 0x6f, 0xf9, 0x03, 0xb7, 0x3b, 0xc9, 0xac, 0xbe, 0x04, 0xf2, 0x47, 0xce, 0x10,
	0x55, 0xfc, 0xc5, 0xf7, 0x74, 0x79, 0x32, 0xd3, 0xe5, 0xe9, 0x17, 0x70, 0x4b, 0x6f, 0xb5, 0xe3,
	0x30, 0xa7, 0xed, 0x8f, 0x69, 0x17, 0x85, 0x9c, 0xbc, 0x60, 0xbe, 0x82, 0x4a, 0xbe, 0x82, 0x6a,
	0x9a, 0xf2, 0x74, 0xdc, 0x7d, 0x1d, 0x5e, 0x1a, 0x57, 0xd2, 0x79, 0xc7, 0x7e, 0xe8, 0x5c, 0x76,
	0x7c, 0xe6, 0x0c, 0xc4, 0x3d, 0x55, 0x10, 0x85, 0x31, 0x81, 0xe3, 0x6d, 0xec, 0xa1, 0x73, 0xc9,
	0x3f, 0x5b, 0x48, 0x77, 0xdd, 0x01, 0x8a, 0xbe, 0xde, 0xb4, 0xa7, 0xb0, 0x5c, 0xff, 0xbd, 0xbe,
	0xe7, 0x53, 0xe4, 0x50, 0xf0, 0x4c, 0x9c, 0x7c, 0xda, 0x39, 0x73, 0x3c, 0xd1, 0xe4, 0x9b, 0xf6,
	0x15, 0x54, 0xf2, 0x35, 0xcc, 0xef, 0x23, 0x8e, 0x5a, 0x48, 0x5d, 0xbf, 0x17, 0x54, 0x4b, 0x22,
	0x79, 0x6a, 0x32, 0xe0, 0x91, 0xbb, 0x23, 0x16, 0x3b, 0xce, 0x6e, 0xfd, 0x16, 0x2a, 0x59, 0x4c,
	0xe4, 0x53, 0x58, 0xdc, 0xf3, 0x18, 0xd2, 0x0b, 0x67, 0xd0, 0x66, 0x0e, 0x65, 0x2a, 0x40, 0x49,
	0x24, 0x3f, 0xae, 0x87, 0xce, 0xe5, 0xd1, 0x78, 0xf8, 0x0a, 0xa9, 0xba, 0x90, 0x23, 0x84, 0xf5,
	0xd6, 0x94, 0xc7, 0xea, 0xaa, 0x20, 0xb7, 0x1c, 0x76, 0xa6, 0x83, 0xcc, 0xbf, 0x89, 0x05, 0x79,
	0xf1, 0x0c, 0x31, 0x33, 0x9f, 0x21, 0x82, 0x16, 0x96, 0x04, 0xd9, 0x3d, 0xc9, 0x92, 0x50, 0x81,
	0xd9, 0xc3, 0x8e, 0x3b, 0x44, 0xd5, 0x1a, 0x49, 0x80, 0x73, 0x1e, 0xf2, 0x23, 0x50, 0x90, 0x85,
	0xe2, 0x50, 0x69, 0xd2, 0x64, 0x4e, 0x5f, 0x84, 0xa0, 0x64, 0x8b, 0x6f, 0x7e, 0xb8, 0xf5, 0x73,
	0xaa, 0x94, 0x7d, 0xf2, 0x34, 0x9d, 0x7c, 0x01, 0xa5, 0x43, 0x64, 0x8e, 0x38, 0xe0, 0xd5, 0xa2,
	0x60, 0xfe, 0x28, 0xd2, 0x72, 0x2b, 0xa4, 0x35, 0x3d, 0x46, 0x27, 0x76, 0xc4, 0x4b, 0xbe, 0x84,
	0x52, 0x7d, 0x34, 0x42, 0x87, 0x06, 0x7b, 0x5e, 0x15, 0xc4, 0xc2, 0xdb, 0x72, 0xe1, 0x89, 0x4f,
	0x5f, 0x07, 0x23, 0xa7, 0x8b, 0x36, 0x0e, 0x1c, 0xe6, 0x5e, 0x20, 0xf7, 0x84, 0x1d, 0x71, 0xd7,
	0xbe, 0x86, 0xa5, 0xa4, 0x5c, 0x52, 0x06, 0xf3, 0x35, 0x4e, 0x94, 0x37, 0xf9, 0x27, 0x77, 0xc0,
	0x85, 0x33, 0x18, 0xeb, 0x23, 0x23, 0x81, 0xaf, 0x72, 0x8f, 0x0d, 0xeb, 0x5b, 0x58, 0xcb, 0xdc,
	0x81, 0x77, 0x73, 0x27, 0x41, 0x2c, 0x2a, 0x0a, 0xe2, 0xf7, 0xd4, 0x49, 0x70, 0xe0, 0xbc, 0xc2,
	0x81, 0x12, 0xa6, 0xc1, 0x30, 0x62, 0x66, 0x14, 0x31, 0xeb, 0x5f, 0x06, 0x94, 0x42, 0x3f, 0xbd,
	0x67, 0x2b, 0x1d, 0x46, 0xcf, 0x9c, 0x8a, 0x5e, 0x2a, 0xce, 0x04, 0xf2, 0xfc, 0x08, 0x8a, 0x30,
	0x2f, 0xd8, 0xe2, 0x9b, 0xa7, 0xe0, 0xf1, 0x1b, 0x0f, 0xa9, 0xd8, 0xb8, 0x20, 0x2b, 0x46, 0x88,
	0x20, 0x3f, 0x83, 0x59, 0x59, 0x77, 0xe7, 0x7e, 0xa8, 0xee, 0x4a, 0x1e, 0xeb, 0xdf, 0x39, 0xd5,
	0x91, 0x90, 0x3b, 0x00, 0xdc, 0xbc, 0x16, 0xc5, 0x53, 0xf7, 0x52, 0xdd, 0x67, 0x31, 0x0c, 0x77,
	0xd2, 0xa1, 0xeb, 0x85, 0xad, 0x89, 0x69, 0x6b, 0x50, 0x50, 0xe4, 0xb9, 0x56, 0xe6, 0x68, 0x50,
	0xad, 0xd9, 0x71, 0x98, 0xb6, 0x49, 0x83, 0x6a, 0x8d, 0xa0, 0xcc, 0x86, 0x6b, 0x04, 0x45, 0x1f,
	0x88, 0xc2, 0x0f, 0x1c, 0x88, 0x1a, 0x14, 0xf9, 0x9d, 0x20, 0x6e, 0x3a, 0x99, 0xd6, 0x21, 0xcc,
	0x25, 0x37, 0x7c, 0x8f, 0x71, 0x07, 0x14, 0x65, 0x30, 0x15, 0xc8, 0x2d, 0xdc, 0xa5, 0x88, 0x6d,
	0x46, 0x5d, 0xaf, 0x5f, 0x2d, 0x09, 0x62, 0x0c, 0xc3, 0xdd, 0x2a, 0x66, 0x2b, 0xa2, 0xe6, 0x81,
	0x74, 0x6b, 0x88, 0x20, 0xf7, 0xa0, 0xf8, 0x0c, 0x7d, 0xd9, 0xbd, 0xcd, 0x0b, 0xcf, 0x2a, 0xdd,
	0x34, 0xd6, 0x0e, 0xe9, 0xd6, 0x3f, 0x8d, 0x88, 0x99, 0xdc, 0x85, 0x42, 0x03, 0xf9, 0x15, 0xa2,
	0x0a, 0x53, 0xb4, 0xac, 0xe5, 0xbb, 0x1e, 0xb3, 0x15, 0x95, 0x1b, 0xb5, 0xe3, 0x06, 0xcc, 0xf1,
	0xba, 0x3a, 0xa7, 0x43, 0x98, 0x6c, 0xc2, 0x5c, 0xc7, 0x1f, 0x1d, 0xe0, 0x29, 0x53, 0x2f, 0xaf,
	0x69, 0x21, 0x9a, 0x4c, 0x1e, 0xc0, 0xfc, 0x53, 0x9f, 0x31, 0x7f, 0x68, 0xbb, 0xfd, 0x33, 0xf9,
	0xe0, 0x4a, 0x73, 0xc7, 0x59, 0xac, 0x2d, 0xa1, 0xab, 0x20, 0xf0, 0x63, 0x76, 0xe0, 0xc8, 0x8b,
	0xcf, 0xb0, 0xf9, 0xa7, 0xc0, 0xa8, 0x1c, 0xe6, 0x18, 0xdf, 0xb3, 0xfe, 0x92, 0x83, 0xe5, 0xa9,
	0x6c, 0x22, 0x0f, 0x55, 0xd0, 0x0c, 0x11, 0xb4, 0x9f, 0x64, 0xa6, 0xdc, 0x96, 0xf8, 0x8d, 0x45,
	0xd1, 0x82, 0x82, 0xac, 0x2c, 0x19, 0x0f, 0x6d, 0x45, 0xe1, 0x3c, 0x1d, 0x87, 0xf6, 0x91, 0x65,
	0xbc, 0x38, 0x15, 0xe5, 0xca, 0x67, 0x7f, 0x17, 0x4a, 0xe1, 0x96, 0x04, 0xa0, 0xd0, 0xb0, 0x9b,
	0xf5, 0x4e, 0xb3, 0x3c, 0x43, 0x8a, 0x90, 0xb7, 0x9b, 0xf5, 0x9d, 0xb2, 0x41, 0x96, 0x61, 0xfe,
	0x45, 0x6b, 0xa7, 0xde, 0x69, 0xbe, 0x6c, 0xd5, 0x3b, 0xcf, 0xcb, 0x39, 0x42, 0x60, 0x49, 0x21,
	0x1a, 0xc7, 0x47, 0x9d, 0xe6, 0x51, 0xa7, 0x6c, 0xc6, 0x98, 0x0e, 0x9b, 0x9d, 0x7a, 0x39, 0xcf,
	0x65, 0xed, 0x34, 0x0f, 0x9a, 0x9d, 0x66, 0x79, 0xd6, 0xfa, 0x87, 0x01, 0x20, 0xde, 0x1a, 0xd2,
	0x11, 0x9f, 0xc2, 0x62, 0x93, 0x52, 0x9f, 0xee, 0x20, 0x13, 0x2f, 0x5c, 0xd5, 0xf8, 0x24, 0x91,
	0xbc, 0x3e, 0x4e, 0xd5, 0x6b, 0x19, 0xf0, 0x29, 0xac, 0xc8, 0x48, 0xbe, 0x30, 0x76, 0x07, 0x45,
	0x08, 0x72, 0x1f, 0x56, 0xd4, 0x93, 0x66, 0xd7, 0xa7, 0x5d, 0x14, 0xcf, 0x23, 0x55, 0xf8, 0xd3,
	0x04, 0xeb, 0xad, 0x01, 0xeb, 0xcf, 0x90, 0x35, 0xbd, 0x2e, 0x9d, 0x88, 0x4b, 0x68, 0x1f, 0x27,
	0xba, 0x7f, 0xe2, 0x97, 0x58, 0xa0, 0x12, 0x94, 0x5f, 0x62, 0x81, 0x4c, 0xc7, 0x96, 0x13, 0x04,
	0x6f, 0x7c, 0xaa, 0xbb, 0xd2, 0x10, 0x0e, 0x7b, 0x47, 0xf3, 0x8a, 0xde, 0x91, 0x3f, 0x9b, 0x45,
	0xb9, 0x16, 0x87, 0xbb, 0x68, 0x2b, 0xc8, 0xba, 0x0f, 0xd5, 0xb4, 0x0a, 0xaa, 0xa9, 0x2a, 0x83,
	0xb9, 0xaf, 0x6e, 0xf8, 0x05, 0x9b, 0x7f, 0x5a, 0x7f, 0xcc, 0x01, 0xb4, 0x27, 0x5e, 0x57, 0xe6,
	0x10, 0x67, 0x08, 0xf0, 0x5c, 0x30, 0xe4, 0x6d, 0xfe, 0x49, 0xd6, 0xa1, 0xe0, 0xf9, 0x3d, 0x0c,
	0xdb, 0xe6, 0x39, 0x0e, 0xbd, 0x74, 0x7b, 0xe4, 0x33, 0xc8, 0xb3, 0xa8, 0xa8, 0xaa, 0x1b, 0x30,
	0x12, 0xb5, 0x25, 0x93, 0x90, 0xb3, 0x70, 0x55, 0x03, 0x99, 0x84, 0xd2, 0x73, 0x0a, 0xe2, 0x78,
	0x26, 0x13, 0x4f, 0x36, 0x44, 0x0a, 0x22, 0x9b, 0x90, 0xf7, 0x74, 0x85, 0x9d, 0xdf, 0xae, 0x4c,
	0x8b, 0x96, 0x4e, 0xe0, 0x1c, 0xd6, 0x53, 0x79, 0x26, 0xc8, 0x3c, 0xcc, 0x8d, 0xbd, 0xd7, 0x9e,
	0xff, 0xc6, 0x2b, 0xcf, 0xf0, 0xd4, 0xe9, 0x0a, 0x5f, 0x94, 0x0d, 0xfe, 0xdd, 0x13, 0xfd, 0x62,
	0x39, 0xc7, 0x53, 0x72, 0xe4, 0xb0, 0xb3, 0xb2, 0xc9, 0xd9, 0xbb, 0xf2, 0xc2, 0x2a, 0xe7, 0x79,
	0x76, 0x2d, 0x25, 0x85, 0xf3, 0xb8, 0xbc, 0x9a, 0x30, 0x0c, 0xf8, 0x75, 0x6b, 0x88, 0xab, 0x33,
	0x84, 0xb9, 0x8b, 0x86, 0xbd, 0x47, 0xca, 0x1b, 0xfc, 0x93, 0x17, 0x9a, 0x21, 0x8b, 0x15, 0x1a,
	0x01, 0x90, 0xdb, 0x50, 0xe4, 0x2a, 0x8a, 0xb4, 0x92, 0x66, 0x97, 0x84, 0xeb, 0xb8, 0x0a, 0xe4,
	0x21, 0x54, 0x28, 0x8e, 0xfc, 0xc0, 0x65, 0x3e, 0x9d, 0xec, 0xf5, 0xd0, 0x63, 0xee, 0xa9, 0x8b,
	0x54, 0xf9, 0x61, 0x2d, 0xa2, 0xbd, 0x74, 0x43, 0xa2, 0xd5, 0x80, 0xb5, 0xd6, 0x98, 0x45, 0xaa,
	0xc6, 0xdf, 0x00, 0x41, 0xf2, 0x0d, 0xa0, 0x40, 0xa1, 0x6c, 0xd0, 0x0f, 0x95, 0x0d, 0xfa, 0xd6,
	0x1f, 0x60, 0x5d, 0x3e, 0x51, 0xe3, 0x72, 0x64, 0x86, 0xa6, 0x83, 0x5f, 0x85, 0xb9, 0xd3, 0x81,
	0xc3, 0x18, 0x7a, 0xaa, 0x7f, 0xd7, 0x20, 0x0f, 0xdd, 0x48, 0x56, 0x31, 0x79, 0x64, 0x14, 0xc4,
	0xcb, 0xf2, 0xc0, 0x09, 0x58, 0x1b, 0xcf, 0x8f, 0xbd, 0xc1, 0x44, 0x5d, 0x16, 0x71, 0xd4, 0xbd,
	0xcf, 0xa1, 0xa8, 0x2b, 0x0d, 0x8f, 0xc3, 0x8b, 0xa3, 0xfd, 0xa3, 0xe3, 0x93, 0x23, 0x79, 0x63,
	0x1c, 0x34, 0xeb, 0xbb, 0x65, 0x83, 0x2c, 0x01, 0x34, 0x8e, 0x0f, 0x0e, 0x9a, 0x8d, 0xce, 0xde,
	0xf1, 0x51, 0x39, 0xb7, 0xfd, 0x57, 0x03, 0x16, 0xf8, 0x9a, 0x16, 0xf5, 0x2f, 0xdc, 0x1e, 0x52,
	0xf2, 0x4b, 0x28, 0xea, 0x81, 0x3c, 0x51, 0x99, 0x37, 0xf5, 0x1f, 0x41, 0xed, 0xd6, 0x34, 0x5a,
	0xfa, 0xca, 0x9a, 0x21, 0x4f, 0xa0, 0x14, 0x8e, 0x9a, 0x89, 0x62, 0x9b, 0x9e, 0xc7, 0xd7, 0xd6,
	0x53, 0x78, 0xbd, 0xfe, 0x81, 0xb1, 0xfd, 0x2d, 0x54, 0xe2, 0xea, 0xb4, 0x19, 0x45, 0x67, 0x88,
	0x94, 0x34, 0x61, 0x49, 0xef, 0x27, 0x71, 0x37, 0x56, 0x6e, 0xd3, 0x78, 0x60, 0x6c, 0xff, 0x47,
	0x99, 0x6b, 0x63, 0x17, 0xdd, 0x0b, 0xa4, 0xa4, 0x0e, 0x10, 0xcd, 0x90, 0x89, 0x52, 0x2d, 0x35,
	0xf8, 0xae, 0x55, 0xd3, 0x84, 0xd0, 0xe8, 0x3a, 0x40, 0x34, 0x9e, 0xd5, 0x22, 0x52, 0x73, 0x64,
	0x2d, 0x22, 0x3d, 0xc9, 0x95, 0x22, 0xa2, 0xb1, 0xa8, 0x16, 0x91, 0x9a, 0xd1, 0x6a, 0x11, 0xe9,
	0x09, 0xaa, 0x35, 0xb3, 0xfd, 0x7f, 0x03, 0x48, 0xdc, 0x32, 0xe5, 0xa5, 0x7d, 0x28, 0x47, 0x4a,
	0x2b, 0xdc, 0xfb, 0x58, 0xc9, 0xbd, 0xc7, 0x85, 0x45, 0xea, 0x27, 0x85, 0xdd, 0xc8, 0x5e, 0x2d,
	0x2c, 0x32, 0x24, 0x29, 0xec, 0x46, 0x96, 0x8b, 0xb8, 0xfe, 0x8f, 0x5f, 0x34, 0xb2, 0x66, 0x88,
	0x6a, 0x86, 0x94, 0xec, 0xc0, 0x7c, 0x6c, 0x34, 0x49, 0x94, 0x84, 0xf4, 0xd8, 0xb3, 0xf6, 0x51,
	0x06, 0x25, 0x8c, 0xcc, 0x33, 0x58, 0x88, 0x0f, 0x13, 0x89, 0x62, 0xce, 0x18, 0x55, 0xd6, 0x6a,
	0x59, 0xa4, 0xb8, 0xa0, 0xf8, 0x00, 0x50, 0x0b, 0xca, 0x18, 0x2f, 0x6a, 0x41, 0x59, 0xf3, 0x42,
	0x6b, 0x66, 0xfb, 0x1b, 0x19, 0x67, 0x51, 0xaf, 0x83, 0xf0, 0xd8, 0x3e, 0x81, 0x52, 0x38, 0xe0,
	0xd3, 0x27, 0x6f, 0x7a, 0x4a, 0xa8, 0x4f, 0x5e, 0x6a, 0x12, 0x28, 0x4e, 0x5e, 0x03, 0x8a, 0xf2,
	0xf6, 0x42, 0x4a, 0xbe, 0x80, 0x82, 0xfc, 0x26, 0xab, 0xaa, 0x42, 0xc4, 0xc7, 0x80, 0xb5, 0x4a,
	0x12, 0x19, 0x13, 0xb2, 0x0a, 0x2b, 0xa2, 0x6d, 0x92, 0x15, 0x80, 0x1f, 0x42, 0xa4, 0x53, 0xc8,
	0x13, 0xea, 0x32, 0xa4, 0xdb, 0x6f, 0x4d, 0x58, 0xe4, 0x58, 0xf5, 0x94, 0x45, 0x4a, 0x7e, 0x0d,
	0x8b, 0x89, 0xe1, 0x19, 0xa9, 0xc5, 0xd3, 0x31, 0x39, 0xfe, 0xa9, 0xdd, 0xce, 0xa4, 0xc5, 0xbd,
	0x1d, 0x1f, 0xe9, 0x68, 0x6f, 0x67, 0x0c, 0x92, 0xb4, 0xb7, 0xb3, 0x26, 0x40, 0xd6, 0x0c, 0xd9,
	0x83, 0x85, 0xf8, 0x58, 0x4d, 0x0b, 0xca, 0x98, 0xd0, 0x69, 0x41, 0x59, 0x53, 0x38, 0xee, 0x1b,
	0x9e, 0x90, 0xb1, 0x51, 0x98, 0x4e, 0xc8, 0xf4, 0xc4, 0x4d, 0x27, 0x64, 0xc6, 0xdc, 0xcc, 0x9a,
	0xe1, 0x5e, 0x4a, 0x4c, 0x75, 0xb4, 0x97, 0xb2, 0x06, 0x4b, 0xda, 0x4b, 0x99, 0x63, 0x20, 0x6b,
	0x66, 0x1b, 0x61, 0x89, 0xbf, 0x3b, 0xf6, 0x71, 0x72, 0xe8, 0x78, 0x4e, 0x1f, 0x29, 0x69, 0x43,
	0x79, 0xba, 0xc3, 0x21, 0x9f, 0xe8, 0xee, 0x3b, 0xb3, 0xf9, 0xaa, 0xdd, 0xb9, 0x8a, 0x1c, 0x6e,
	0xf3, 0x27, 0x03, 0xe6, 0xa3, 0x92, 0x18, 0x90, 0xc7, 0x60, 0xb6, 0xc6, 0x8c, 0x94, 0xa7, 0x9b,
	0x8f, 0x50, 0xdd, 0xac, 0x4a, 0xcc, 0x0f, 0x3a, 0xf9, 0x55, 0x98, 0x97, 0x9f, 0xc4, 0x53, 0x30,
	0x55, 0x6f, 0x6b, 0x29, 0xd9, 0x3c, 0x02, 0xaf, 0x0a, 0xe2, 0xdf, 0xef, 0x87, 0xdf, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xe1, 0x89, 0x9e, 0xc4, 0x0b, 0x1f, 0x00, 0x00,
}
