/*
 * Copyright (c) 2018. Abstrium SAS <team (at) pydio.com>
 * This file is part of Pydio Cells.
 *
 * Pydio Cells is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Pydio Cells is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Pydio Cells.  If not, see <http://www.gnu.org/licenses/>.
 *
 * The latest code can be found at <https://pydio.com>.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: broker.proto

/*
Package rest is a generated protocol buffer package.

It is generated from these files:
	broker.proto
	common.proto
	config.proto
	data.proto
	frontend.proto
	graph.proto
	idm.proto
	rest.proto
	scheduler.proto
	share.proto

It has these top-level messages:
	ActivitiesCollection
	SubscriptionsCollection
	LogCollection
	LogMessageCollection
	TimeRangeResultCollection
	DeleteResponse
	Configuration
	ListDataSourceRequest
	DataSourceCollection
	DeleteDataSourceResponse
	ListPeersAddressesRequest
	ListPeersAddressesResponse
	ListPeerFoldersRequest
	ListVersioningPolicyRequest
	VersioningPolicyCollection
	DeleteVersioningPolicyResponse
	ListServiceRequest
	ServiceCollection
	ControlServiceRequest
	DiscoveryRequest
	DiscoveryResponse
	ConfigFormRequest
	OpenApiResponse
	ListExternalDirectoryRequest
	ExternalDirectoryResponse
	ExternalDirectoryConfig
	ExternalDirectoryCollection
	SearchResults
	Metadata
	MetaCollection
	MetaNamespaceRequest
	GetBulkMetaRequest
	BulkMetaResponse
	SetBulkMetaRequest
	DeleteBulkMetaRequest
	NodesCollection
	ListDocstoreRequest
	DocstoreCollection
	ChangeRequest
	ChangeCollection
	FrontLogMessage
	FrontLogResponse
	SettingsMenuRequest
	SettingsEntryMeta
	SettingsEntry
	SettingsSection
	SettingsMenuResponse
	FrontBootConfRequest
	FrontBootConfResponse
	UserStateRequest
	UserStateResponse
	RelationRequest
	RelationResponse
	ResourcePolicyQuery
	SearchRoleRequest
	RolesCollection
	SearchUserRequest
	UsersCollection
	BindResponse
	SearchACLRequest
	ACLCollection
	SearchWorkspaceRequest
	WorkspaceCollection
	UserMetaCollection
	UserMetaNamespaceCollection
	UserBookmarksRequest
	RevokeRequest
	RevokeResponse
	ResetPasswordTokenRequest
	ResetPasswordTokenResponse
	ResetPasswordRequest
	ResetPasswordResponse
	UserJobRequest
	UserJobResponse
	UserJobsCollection
	CellAcl
	Cell
	ShareLinkTargetUser
	ShareLink
	PutCellRequest
	GetCellRequest
	DeleteCellRequest
	DeleteCellResponse
	GetShareLinkRequest
	PutShareLinkRequest
	DeleteShareLinkRequest
	DeleteShareLinkResponse
	ListSharedResourcesRequest
	ListSharedResourcesResponse
*/
package rest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import activity "github.com/pydio/cells/common/proto/activity"
import log "github.com/pydio/cells/common/proto/log"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Collection of Activities
type ActivitiesCollection struct {
	Activities []*activity.Object `protobuf:"bytes,1,rep,name=activities" json:"activities,omitempty"`
}

func (m *ActivitiesCollection) Reset()                    { *m = ActivitiesCollection{} }
func (m *ActivitiesCollection) String() string            { return proto.CompactTextString(m) }
func (*ActivitiesCollection) ProtoMessage()               {}
func (*ActivitiesCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ActivitiesCollection) GetActivities() []*activity.Object {
	if m != nil {
		return m.Activities
	}
	return nil
}

type SubscriptionsCollection struct {
	Subscriptions []*activity.Subscription `protobuf:"bytes,1,rep,name=subscriptions" json:"subscriptions,omitempty"`
}

func (m *SubscriptionsCollection) Reset()                    { *m = SubscriptionsCollection{} }
func (m *SubscriptionsCollection) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionsCollection) ProtoMessage()               {}
func (*SubscriptionsCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubscriptionsCollection) GetSubscriptions() []*activity.Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

// Collection of serialized log messages
type LogCollection struct {
	Lines []*log.Log `protobuf:"bytes,1,rep,name=lines" json:"lines,omitempty"`
}

func (m *LogCollection) Reset()                    { *m = LogCollection{} }
func (m *LogCollection) String() string            { return proto.CompactTextString(m) }
func (*LogCollection) ProtoMessage()               {}
func (*LogCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogCollection) GetLines() []*log.Log {
	if m != nil {
		return m.Lines
	}
	return nil
}

// Collection of serialized log messages
type LogMessageCollection struct {
	Logs []*log.LogMessage `protobuf:"bytes,1,rep,name=Logs" json:"Logs,omitempty"`
}

func (m *LogMessageCollection) Reset()                    { *m = LogMessageCollection{} }
func (m *LogMessageCollection) String() string            { return proto.CompactTextString(m) }
func (*LogMessageCollection) ProtoMessage()               {}
func (*LogMessageCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogMessageCollection) GetLogs() []*log.LogMessage {
	if m != nil {
		return m.Logs
	}
	return nil
}

// Collection of serialized aggregated result of time range request
// with a cursor to ease navigation implementation
type TimeRangeResultCollection struct {
	Results []*log.TimeRangeResult `protobuf:"bytes,1,rep,name=Results" json:"Results,omitempty"`
	Links   []*log.TimeRangeCursor `protobuf:"bytes,2,rep,name=Links" json:"Links,omitempty"`
}

func (m *TimeRangeResultCollection) Reset()                    { *m = TimeRangeResultCollection{} }
func (m *TimeRangeResultCollection) String() string            { return proto.CompactTextString(m) }
func (*TimeRangeResultCollection) ProtoMessage()               {}
func (*TimeRangeResultCollection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TimeRangeResultCollection) GetResults() []*log.TimeRangeResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *TimeRangeResultCollection) GetLinks() []*log.TimeRangeCursor {
	if m != nil {
		return m.Links
	}
	return nil
}

func init() {
	proto.RegisterType((*ActivitiesCollection)(nil), "rest.ActivitiesCollection")
	proto.RegisterType((*SubscriptionsCollection)(nil), "rest.SubscriptionsCollection")
	proto.RegisterType((*LogCollection)(nil), "rest.LogCollection")
	proto.RegisterType((*LogMessageCollection)(nil), "rest.LogMessageCollection")
	proto.RegisterType((*TimeRangeResultCollection)(nil), "rest.TimeRangeResultCollection")
}

func init() { proto.RegisterFile("broker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4b, 0x03, 0x31,
	0x14, 0xc6, 0x51, 0x5b, 0x95, 0xa7, 0x45, 0x29, 0x45, 0x6b, 0x07, 0x91, 0x73, 0x11, 0x87, 0x44,
	0xd4, 0x4d, 0x17, 0xa9, 0x83, 0xc3, 0x89, 0x10, 0x05, 0xe7, 0xbb, 0xf8, 0x88, 0xb1, 0x77, 0xf7,
	0x4a, 0x5e, 0xae, 0xd2, 0xff, 0x5e, 0x7a, 0xe9, 0xd5, 0x28, 0x0e, 0x0e, 0x81, 0xf0, 0xbd, 0xdf,
	0xf7, 0x4b, 0x42, 0x60, 0x37, 0x77, 0x34, 0x41, 0x27, 0xa6, 0x8e, 0x3c, 0xf5, 0x3b, 0x0e, 0xd9,
	0x8f, 0xee, 0x8d, 0xf5, 0xef, 0x75, 0x2e, 0x34, 0x95, 0x72, 0x3a, 0x7f, 0xb3, 0x24, 0x19, 0xdd,
	0xcc, 0x6a, 0x64, 0xa9, 0xa9, 0x2c, 0xa9, 0x92, 0x0d, 0x2d, 0x33, 0xed, 0xed, 0xcc, 0xfa, 0xf9,
	0x6a, 0xc3, 0xde, 0x61, 0x56, 0x06, 0xd7, 0xe8, 0xfa, 0x9f, 0x96, 0x82, 0xcc, 0x62, 0x85, 0x56,
	0xf2, 0x00, 0x83, 0xbb, 0x60, 0xb3, 0xc8, 0x63, 0x2a, 0x0a, 0xd4, 0xde, 0x52, 0xd5, 0xbf, 0x00,
	0xc8, 0x56, 0xf9, 0x70, 0xed, 0x64, 0xe3, 0x6c, 0xe7, 0x72, 0x5f, 0xb4, 0x07, 0x8b, 0xa7, 0xfc,
	0x03, 0xb5, 0x57, 0x11, 0x93, 0xbc, 0xc2, 0xe1, 0x73, 0x9d, 0xb3, 0x76, 0x76, 0xba, 0x30, 0xc4,
	0xb2, 0x5b, 0xe8, 0x71, 0x3c, 0x5a, 0xfa, 0x0e, 0xbe, 0x7d, 0x71, 0x53, 0xfd, 0x84, 0x13, 0x09,
	0xbd, 0x94, 0x4c, 0xa4, 0x3b, 0x86, 0x6e, 0x61, 0xab, 0xd5, 0xb5, 0xb6, 0xc5, 0xe2, 0x39, 0x29,
	0x19, 0x15, 0xe2, 0xe4, 0x06, 0x06, 0x29, 0x99, 0x47, 0x64, 0xce, 0x0c, 0x46, 0xbd, 0x53, 0xe8,
	0xa4, 0x64, 0xda, 0xda, 0x5e, 0x5b, 0x5b, 0x82, 0xaa, 0x19, 0x26, 0x9f, 0x70, 0xf4, 0x62, 0x4b,
	0x54, 0x59, 0x65, 0x50, 0x21, 0xd7, 0x85, 0x8f, 0x0c, 0x02, 0xb6, 0x42, 0xd6, 0x4a, 0x06, 0x8d,
	0xe4, 0x57, 0x41, 0xb5, 0x50, 0xff, 0x1c, 0xba, 0xa9, 0xad, 0x26, 0x3c, 0x5c, 0xff, 0x8b, 0x1e,
	0xd7, 0x8e, 0xc9, 0xa9, 0x80, 0xe4, 0x9b, 0xcd, 0x87, 0x5c, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xab, 0xbe, 0xfe, 0xd8, 0x22, 0x02, 0x00, 0x00,
}
