// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cellsapi-rest.proto

package rest

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	activity "github.com/pydio/cells/v5/common/proto/activity"
	ctl "github.com/pydio/cells/v5/common/proto/ctl"
	encryption "github.com/pydio/cells/v5/common/proto/encryption"
	idm "github.com/pydio/cells/v5/common/proto/idm"
	install "github.com/pydio/cells/v5/common/proto/install"
	jobs "github.com/pydio/cells/v5/common/proto/jobs"
	log "github.com/pydio/cells/v5/common/proto/log"
	mailer "github.com/pydio/cells/v5/common/proto/mailer"
	object "github.com/pydio/cells/v5/common/proto/object"
	registry "github.com/pydio/cells/v5/common/proto/registry"
	tree "github.com/pydio/cells/v5/common/proto/tree"
	update "github.com/pydio/cells/v5/common/proto/update"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=Slug,proto3" json:"Slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_cellsapi_rest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cellsapi_rest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_cellsapi_rest_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteWorkspaceRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type HealthServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthServiceRequest) Reset() {
	*x = HealthServiceRequest{}
	mi := &file_cellsapi_rest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthServiceRequest) ProtoMessage() {}

func (x *HealthServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cellsapi_rest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthServiceRequest.ProtoReflect.Descriptor instead.
func (*HealthServiceRequest) Descriptor() ([]byte, []int) {
	return file_cellsapi_rest_proto_rawDescGZIP(), []int{1}
}

func (x *HealthServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ComponentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=Details,proto3" json:"Details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentStatus) Reset() {
	*x = ComponentStatus{}
	mi := &file_cellsapi_rest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentStatus) ProtoMessage() {}

func (x *ComponentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cellsapi_rest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentStatus.ProtoReflect.Descriptor instead.
func (*ComponentStatus) Descriptor() ([]byte, []int) {
	return file_cellsapi_rest_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentStatus) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type HealthServiceResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Components    map[string]*ComponentStatus `protobuf:"bytes,2,rep,name=Components,proto3" json:"Components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthServiceResponse) Reset() {
	*x = HealthServiceResponse{}
	mi := &file_cellsapi_rest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthServiceResponse) ProtoMessage() {}

func (x *HealthServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cellsapi_rest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthServiceResponse.ProtoReflect.Descriptor instead.
func (*HealthServiceResponse) Descriptor() ([]byte, []int) {
	return file_cellsapi_rest_proto_rawDescGZIP(), []int{3}
}

func (x *HealthServiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthServiceResponse) GetComponents() map[string]*ComponentStatus {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_cellsapi_rest_proto protoreflect.FileDescriptor

const file_cellsapi_rest_proto_rawDesc = "" +
	"\n" +
	"\x13cellsapi-rest.proto\x12\x04rest\x1a\x15cellsapi-common.proto\x1a\x13cellsapi-data.proto\x1a\x12cellsapi-idm.proto\x1a\x15cellsapi-broker.proto\x1a\x15cellsapi-config.proto\x1a\x18cellsapi-scheduler.proto\x1a\x14cellsapi-graph.proto\x1a\x14cellsapi-share.proto\x1a\x17cellsapi-frontend.proto\x1a\x18cellsapi-templates.proto\x1a\x10cells-tree.proto\x1a\x0fcells-idm.proto\x1a\x12cells-mailer.proto\x1a\x1acells-activitystream.proto\x1a\x10cells-jobs.proto\x1a\x16cells-encryption.proto\x1a\x0fcells-log.proto\x1a\x12cells-object.proto\x1a\x13cells-install.proto\x1a\x0fcells-ctl.proto\x1a\x12cells-update.proto\x1a\x14cells-registry.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\",\n" +
	"\x16DeleteWorkspaceRequest\x12\x12\n" +
	"\x04Slug\x18\x01 \x01(\tR\x04Slug\"8\n" +
	"\x14HealthServiceRequest\x12 \n" +
	"\vServiceName\x18\x01 \x01(\tR\vServiceName\"C\n" +
	"\x0fComponentStatus\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\x12\x18\n" +
	"\aDetails\x18\x02 \x01(\tR\aDetails\"\xd2\x01\n" +
	"\x15HealthServiceResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\x12K\n" +
	"\n" +
	"Components\x18\x02 \x03(\v2+.rest.HealthServiceResponse.ComponentsEntryR\n" +
	"Components\x1aT\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.rest.ComponentStatusR\x05value:\x028\x012\x96\x19\n" +
	"\rConfigService\x12T\n" +
	"\tPutConfig\x12\x13.rest.Configuration\x1a\x13.rest.Configuration\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/config/{FullPath}\x12Q\n" +
	"\tGetConfig\x12\x13.rest.Configuration\x1a\x13.rest.Configuration\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/config/{FullPath}\x12]\n" +
	"\rPutDataSource\x12\x12.object.DataSource\x1a\x12.object.DataSource\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/config/datasource/{Name}\x12Z\n" +
	"\rGetDataSource\x12\x12.object.DataSource\x1a\x12.object.DataSource\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/config/datasource/{Name}\x12i\n" +
	"\x10DeleteDataSource\x12\x12.object.DataSource\x1a\x1e.rest.DeleteDataSourceResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/config/datasource/{Name}\x12f\n" +
	"\x0fListDataSources\x12\x1b.rest.ListDataSourceRequest\x1a\x1a.rest.DataSourceCollection\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/config/datasource\x12y\n" +
	"\x16ListVersioningPolicies\x12!.rest.ListVersioningPolicyRequest\x1a .rest.VersioningPolicyCollection\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/config/versioning\x12h\n" +
	"\x13GetVersioningPolicy\x12\x16.tree.VersioningPolicy\x1a\x16.tree.VersioningPolicy\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/config/versioning/{Uuid}\x12f\n" +
	"\x10ListVirtualNodes\x12\x1d.rest.ListVirtualNodesRequest\x1a\x15.rest.NodesCollection\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/config/virtualnodes\x12V\n" +
	"\fListServices\x12\x18.rest.ListServiceRequest\x1a\x17.rest.ServiceCollection\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/config/ctl\x12S\n" +
	"\x0eControlService\x12\x1b.rest.ControlServiceRequest\x1a\f.ctl.Service\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/config/ctl\x12Z\n" +
	"\fListRegistry\x12\x15.registry.ListRequest\x1a\x16.registry.ListResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/config/registry\x12n\n" +
	"\x12ListPeersAddresses\x12\x1f.rest.ListPeersAddressesRequest\x1a .rest.ListPeersAddressesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/config/peers\x12n\n" +
	"\x0fListPeerFolders\x12\x1c.rest.ListPeerFoldersRequest\x1a\x15.rest.NodesCollection\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/config/peers/{PeerAddress}\x12y\n" +
	"\x10CreatePeerFolder\x12\x1d.rest.CreatePeerFolderRequest\x1a\x1e.rest.CreatePeerFolderResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/config/peers/{PeerAddress}\x12h\n" +
	"\x12ListStorageBuckets\x12\x1f.rest.ListStorageBucketsRequest\x1a\x15.rest.NodesCollection\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/config/buckets\x12\x83\x01\n" +
	"\x13CreateStorageBucket\x12 .rest.CreateStorageBucketRequest\x1a!.rest.CreateStorageBucketResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/config/buckets/{BucketName}\x12f\n" +
	"\rListProcesses\x12\x1a.rest.ListProcessesRequest\x1a\x1b.rest.ListProcessesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/config/processes\x12}\n" +
	"\x12ListEncryptionKeys\x12 .encryption.AdminListKeysRequest\x1a!.encryption.AdminListKeysResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/config/encryption/list\x12\x82\x01\n" +
	"\x13CreateEncryptionKey\x12!.encryption.AdminCreateKeyRequest\x1a\".encryption.AdminCreateKeyResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/config/encryption/create\x12\x82\x01\n" +
	"\x13DeleteEncryptionKey\x12!.encryption.AdminDeleteKeyRequest\x1a\".encryption.AdminDeleteKeyResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/config/encryption/delete\x12\x82\x01\n" +
	"\x13ExportEncryptionKey\x12!.encryption.AdminExportKeyRequest\x1a\".encryption.AdminExportKeyResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/config/encryption/export\x12\x82\x01\n" +
	"\x13ImportEncryptionKey\x12!.encryption.AdminImportKeyRequest\x1a\".encryption.AdminImportKeyResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/config/encryption/import\x12`\n" +
	"\x12EndpointsDiscovery\x12\x16.rest.DiscoveryRequest\x1a\x17.rest.DiscoveryResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/config/discovery\x12d\n" +
	"\x10OpenApiDiscovery\x12\x16.rest.DiscoveryRequest\x1a\x15.rest.OpenApiResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/config/discovery/openapi\x12w\n" +
	"\x14ConfigFormsDiscovery\x12\x17.rest.ConfigFormRequest\x1a\x17.rest.DiscoveryResponse\"-\x82\xd3\xe4\x93\x02'\x12%/config/discovery/forms/{ServiceName}\x12}\n" +
	"\x19SchedulerActionsDiscovery\x12\x1d.rest.SchedulerActionsRequest\x1a\x1e.rest.SchedulerActionsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/config/scheduler/actions\x12\x93\x01\n" +
	"\x1cSchedulerActionFormDiscovery\x12 .rest.SchedulerActionFormRequest\x1a!.rest.SchedulerActionFormResponse\".\x82\xd3\xe4\x93\x02(\x12&/config/scheduler/actions/{ActionName}\x12\\\n" +
	"\tListSites\x12\x16.rest.ListSitesRequest\x1a\x17.rest.ListSitesResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/config/sites/{Filter}2\x89\x02\n" +
	"\vRoleService\x128\n" +
	"\aSetRole\x12\t.idm.Role\x1a\t.idm.Role\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\x1a\f/role/{Uuid}\x128\n" +
	"\n" +
	"DeleteRole\x12\t.idm.Role\x1a\t.idm.Role\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/role/{Uuid}\x125\n" +
	"\aGetRole\x12\t.idm.Role\x1a\t.idm.Role\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/role/{Uuid}\x12O\n" +
	"\vSearchRoles\x12\x17.rest.SearchRoleRequest\x1a\x15.rest.RolesCollection\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/role2\xd9\x02\n" +
	"\vUserService\x129\n" +
	"\aPutUser\x12\t.idm.User\x1a\t.idm.User\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/user/{Login}\x12D\n" +
	"\n" +
	"DeleteUser\x12\t.idm.User\x1a\x14.rest.DeleteResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/user/{Login}\x126\n" +
	"\aGetUser\x12\t.idm.User\x1a\t.idm.User\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/user/{Login}\x12O\n" +
	"\vSearchUsers\x12\x17.rest.SearchUserRequest\x1a\x15.rest.UsersCollection\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/user\x12@\n" +
	"\bPutRoles\x12\t.idm.User\x1a\t.idm.User\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/user/roles/{Login}2\xd1\x01\n" +
	"\n" +
	"ACLService\x12-\n" +
	"\x06PutAcl\x12\b.idm.ACL\x1a\b.idm.ACL\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\x1a\x04/acl\x12H\n" +
	"\tDeleteAcl\x12\b.idm.ACL\x1a\x14.rest.DeleteResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/acl/bulk/delete\x12J\n" +
	"\n" +
	"SearchAcls\x12\x16.rest.SearchACLRequest\x1a\x13.rest.ACLCollection\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/acl2p\n" +
	"\rPolicyService\x12_\n" +
	"\fListPolicies\x12\x1c.idm.ListPolicyGroupsRequest\x1a\x1d.idm.ListPolicyGroupsResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/policy2\xa6\x02\n" +
	"\x10WorkspaceService\x12L\n" +
	"\fPutWorkspace\x12\x0e.idm.Workspace\x1a\x0e.idm.Workspace\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/workspace/{Slug}\x12`\n" +
	"\x0fDeleteWorkspace\x12\x1c.rest.DeleteWorkspaceRequest\x1a\x14.rest.DeleteResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/workspace/{Slug}\x12b\n" +
	"\x10SearchWorkspaces\x12\x1c.rest.SearchWorkspaceRequest\x1a\x19.rest.WorkspaceCollection\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/workspace2\xca\x02\n" +
	"\x0fActivityService\x12Z\n" +
	"\x06Stream\x12!.activity.StreamActivitiesRequest\x1a\x10.activity.Object\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/activity/stream\x12[\n" +
	"\tSubscribe\x12\x16.activity.Subscription\x1a\x16.activity.Subscription\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/activity/subscribe\x12~\n" +
	"\x13SearchSubscriptions\x12$.activity.SearchSubscriptionsRequest\x1a\x1d.rest.SubscriptionsCollection\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/activity/subscriptions2\\\n" +
	"\n" +
	"LogService\x12N\n" +
	"\x06Syslog\x12\x13.log.ListLogRequest\x1a\x1a.rest.LogMessageCollection\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/log/sys2\xe0\x03\n" +
	"\fTokenService\x12R\n" +
	"\x06Revoke\x12\x13.rest.RevokeRequest\x1a\x14.rest.RevokeResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/auth/token/revoke\x12\x8a\x01\n" +
	"\x12ResetPasswordToken\x12\x1f.rest.ResetPasswordTokenRequest\x1a .rest.ResetPasswordTokenResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\x1a&/auth/reset-password-token/{UserLogin}\x12i\n" +
	"\rResetPassword\x12\x1a.rest.ResetPasswordRequest\x1a\x1b.rest.ResetPasswordResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/auth/reset-password\x12\x83\x01\n" +
	"\x1bGenerateDocumentAccessToken\x12 .rest.DocumentAccessTokenRequest\x1a!.rest.DocumentAccessTokenResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/auth/token/document2X\n" +
	"\rMailerService\x12G\n" +
	"\x04Send\x12\f.mailer.Mail\x1a\x18.mailer.SendMailResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/mailer/send2\\\n" +
	"\rSearchService\x12K\n" +
	"\x05Nodes\x12\x13.tree.SearchRequest\x1a\x13.rest.SearchResults\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/search/nodes2\xc1\x04\n" +
	"\vTreeService\x12Y\n" +
	"\rBulkStatNodes\x12\x18.rest.GetBulkMetaRequest\x1a\x16.rest.BulkMetaResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/tree/stats\x12W\n" +
	"\vCreateNodes\x12\x18.rest.CreateNodesRequest\x1a\x15.rest.NodesCollection\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/tree/create\x12T\n" +
	"\bHeadNode\x12\x15.rest.HeadNodeRequest\x1a\x16.rest.HeadNodeResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/tree/stat/{Node}\x12[\n" +
	"\vDeleteNodes\x12\x18.rest.DeleteNodesRequest\x1a\x19.rest.DeleteNodesResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/tree/delete\x12_\n" +
	"\fRestoreNodes\x12\x19.rest.RestoreNodesRequest\x1a\x1a.rest.RestoreNodesResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/tree/restore\x12j\n" +
	"\x0fCreateSelection\x12\x1c.rest.CreateSelectionRequest\x1a\x1d.rest.CreateSelectionResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/tree/selection2p\n" +
	"\x10TemplatesService\x12\\\n" +
	"\rListTemplates\x12\x1a.rest.ListTemplatesRequest\x1a\x1b.rest.ListTemplatesResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/templates2\xe5\x02\n" +
	"\vMetaService\x12R\n" +
	"\aGetMeta\x12\x1a.rest.MetaNamespaceRequest\x1a\n" +
	".tree.Node\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/meta/get/{NodePath}\x12L\n" +
	"\aSetMeta\x12\x14.rest.MetaCollection\x1a\n" +
	".tree.Node\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/meta/set/{NodePath}\x12X\n" +
	"\n" +
	"DeleteMeta\x12\x1a.rest.MetaNamespaceRequest\x1a\n" +
	".tree.Node\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/meta/delete/{NodePath}\x12Z\n" +
	"\vGetBulkMeta\x12\x18.rest.GetBulkMetaRequest\x1a\x16.rest.BulkMetaResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/meta/bulk/get2\xb7\t\n" +
	"\x0fUserMetaService\x12g\n" +
	"\x0eUpdateUserMeta\x12\x1a.idm.UpdateUserMetaRequest\x1a\x1b.idm.UpdateUserMetaResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/user-meta/update\x12d\n" +
	"\x0eSearchUserMeta\x12\x1a.idm.SearchUserMetaRequest\x1a\x18.rest.UserMetaCollection\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/user-meta/search\x12d\n" +
	"\rUserBookmarks\x12\x1a.rest.UserBookmarksRequest\x1a\x16.rest.BulkMetaResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/user-meta/bookmarks\x12\x85\x01\n" +
	"\x17UpdateUserMetaNamespace\x12#.idm.UpdateUserMetaNamespaceRequest\x1a$.idm.UpdateUserMetaNamespaceResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/user-meta/namespace\x12{\n" +
	"\x15ListUserMetaNamespace\x12!.idm.ListUserMetaNamespaceRequest\x1a!.rest.UserMetaNamespaceCollection\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/user-meta/namespace\x12\x7f\n" +
	"\x0eGetFieldSchema\x12\x1a.idm.GetFieldSchemaRequest\x1a\x17.idm.JsonSchemaResponse\"8\x82\xd3\xe4\x93\x022\x120/user-meta/namespace/discovery/field/{FieldType}\x12v\n" +
	"\x12GetNamespaceSchema\x12\x1e.idm.GetNamespaceSchemaRequest\x1a\x17.idm.JsonSchemaResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/user-meta/namespace/jsonschema\x12v\n" +
	"\x10ListUserMetaTags\x12\x1d.rest.ListUserMetaTagsRequest\x1a\x1e.rest.ListUserMetaTagsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/user-meta/tags/{Namespace}\x12s\n" +
	"\x0ePutUserMetaTag\x12\x1b.rest.PutUserMetaTagRequest\x1a\x1c.rest.PutUserMetaTagResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/user-meta/tags/{Namespace}\x12\x83\x01\n" +
	"\x12DeleteUserMetaTags\x12\x1f.rest.DeleteUserMetaTagsRequest\x1a .rest.DeleteUserMetaTagsResponse\"*\x82\xd3\xe4\x93\x02$*\"/user-meta/tags/{Namespace}/{Tags}2\xe1\x03\n" +
	"\vJobsService\x12]\n" +
	"\rUserCreateJob\x12\x14.rest.UserJobRequest\x1a\x15.rest.UserJobResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/jobs/user/{JobName}\x12V\n" +
	"\fUserListJobs\x12\x15.jobs.ListJobsRequest\x1a\x18.rest.UserJobsCollection\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/jobs/user\x12U\n" +
	"\x0eUserControlJob\x12\x11.jobs.CtrlCommand\x1a\x19.jobs.CtrlCommandResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\x1a\n" +
	"/jobs/user\x12e\n" +
	"\x0fUserDeleteTasks\x12\x18.jobs.DeleteTasksRequest\x1a\x19.jobs.DeleteTasksResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/jobs/tasks/delete\x12]\n" +
	"\rListTasksLogs\x12\x13.log.ListLogRequest\x1a\x1a.rest.LogMessageCollection\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/jobs/tasks/logs2\xcc\x01\n" +
	"\x10AdminTreeService\x12[\n" +
	"\rListAdminTree\x12\x16.tree.ListNodesRequest\x1a\x15.rest.NodesCollection\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/tree/admin/list\x12[\n" +
	"\rStatAdminTree\x12\x15.tree.ReadNodeRequest\x1a\x16.tree.ReadNodeResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/tree/admin/stat2\xa4\x02\n" +
	"\fGraphService\x12\\\n" +
	"\tUserState\x12\x16.rest.UserStateRequest\x1a\x17.rest.UserStateResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/graph/state/{Segment}\x12[\n" +
	"\bRelation\x12\x15.rest.RelationRequest\x1a\x16.rest.RelationResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/graph/relation/{UserId}\x12Y\n" +
	"\tRecommend\x12\x16.rest.RecommendRequest\x1a\x17.rest.RecommendResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/graph/recommend2\x82\x06\n" +
	"\fShareService\x12C\n" +
	"\aPutCell\x12\x14.rest.PutCellRequest\x1a\n" +
	".rest.Cell\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/share/cell\x12G\n" +
	"\aGetCell\x12\x14.rest.GetCellRequest\x1a\n" +
	".rest.Cell\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/share/cell/{Uuid}\x12[\n" +
	"\n" +
	"DeleteCell\x12\x17.rest.DeleteCellRequest\x1a\x18.rest.DeleteCellResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/share/cell/{Uuid}\x12R\n" +
	"\fPutShareLink\x12\x19.rest.PutShareLinkRequest\x1a\x0f.rest.ShareLink\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/share/link\x12V\n" +
	"\fGetShareLink\x12\x19.rest.GetShareLinkRequest\x1a\x0f.rest.ShareLink\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/share/link/{Uuid}\x12j\n" +
	"\x0fDeleteShareLink\x12\x1c.rest.DeleteShareLinkRequest\x1a\x1d.rest.DeleteShareLinkResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/share/link/{Uuid}\x12w\n" +
	"\x13ListSharedResources\x12 .rest.ListSharedResourcesRequest\x1a!.rest.ListSharedResourcesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/share/resources\x12v\n" +
	"\x13UpdateSharePolicies\x12 .rest.UpdateSharePoliciesRequest\x1a!.rest.UpdateSharePoliciesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/share/policies2\x83\x04\n" +
	"\x0eInstallService\x12Y\n" +
	"\n" +
	"GetInstall\x12\x1b.install.GetDefaultsRequest\x1a\x1c.install.GetDefaultsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/install\x12U\n" +
	"\vPostInstall\x12\x17.install.InstallRequest\x1a\x18.install.InstallResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/install\x12m\n" +
	"\x13PerformInstallCheck\x12\x1c.install.PerformCheckRequest\x1a\x1d.install.PerformCheckResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/install/check\x12g\n" +
	"\fGetAgreement\x12\x1c.install.GetAgreementRequest\x1a\x1d.install.GetAgreementResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/install/agreement\x12g\n" +
	"\rInstallEvents\x12\x1d.install.InstallEventsRequest\x1a\x1e.install.InstallEventsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/install/events2\xd0\x01\n" +
	"\rUpdateService\x12S\n" +
	"\x0eUpdateRequired\x12\x15.update.UpdateRequest\x1a\x16.update.UpdateResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/update\x12j\n" +
	"\vApplyUpdate\x12\x1a.update.ApplyUpdateRequest\x1a\x1b.update.ApplyUpdateResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/update/{TargetVersion}2\xd1\a\n" +
	"\x0fFrontendService\x12X\n" +
	"\n" +
	"FrontState\x12\x17.rest.FrontStateRequest\x1a\x18.rest.FrontStateResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/frontend/state\x12d\n" +
	"\rFrontBootConf\x12\x1a.rest.FrontBootConfRequest\x1a\x1b.rest.FrontBootConfResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/frontend/bootconf\x12k\n" +
	"\rFrontMessages\x12\x1a.rest.FrontMessagesRequest\x1a\x1b.rest.FrontMessagesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/frontend/messages/{Lang}\x12g\n" +
	"\fFrontPlugins\x12\x19.rest.FrontPluginsRequest\x1a\x1a.rest.FrontPluginsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/frontend/plugins/{Lang}\x12c\n" +
	"\fFrontSession\x12\x19.rest.FrontSessionRequest\x1a\x1a.rest.FrontSessionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/frontend/session\x12k\n" +
	"\x0fFrontEnrollAuth\x12\x1c.rest.FrontEnrollAuthRequest\x1a\x1d.rest.FrontEnrollAuthResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/frontend/enroll\x12w\n" +
	"\x10FrontServeBinary\x12\x18.rest.FrontBinaryRequest\x1a\x19.rest.FrontBinaryResponse\".\x82\xd3\xe4\x93\x02(\x12&/frontend/binaries/{BinaryType}/{Uuid}\x12u\n" +
	"\x0eFrontPutBinary\x12\x18.rest.FrontBinaryRequest\x1a\x19.rest.FrontBinaryResponse\".\x82\xd3\xe4\x93\x02(\"&/frontend/binaries/{BinaryType}/{Uuid}\x12f\n" +
	"\fSettingsMenu\x12\x19.rest.SettingsMenuRequest\x1a\x1a.rest.SettingsMenuResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/frontend/settings-menu2\xf9\x03\n" +
	"\rHealthService\x12X\n" +
	"\aApiPing\x12\x1a.rest.HealthServiceRequest\x1a\x1b.rest.HealthServiceResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/health/ping\x12X\n" +
	"\aApiLive\x12\x1a.rest.HealthServiceRequest\x1a\x1b.rest.HealthServiceResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/health/live\x12Z\n" +
	"\bApiReady\x12\x1a.rest.HealthServiceRequest\x1a\x1b.rest.HealthServiceResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/health/ready\x12j\n" +
	"\vServiceLive\x12\x1a.rest.HealthServiceRequest\x1a\x1b.rest.HealthServiceResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/health/{ServiceName}/live\x12l\n" +
	"\fServiceReady\x12\x1a.rest.HealthServiceRequest\x1a\x1b.rest.HealthServiceResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/health/{ServiceName}/readyB\xc5\x01\x92A\x94\x01\x127\n" +
	"\x14Pydio Cells Rest API\"\x1a\n" +
	"\x05Pydio\x12\x11https://pydio.com2\x034.0*\x03\x01\x02\x042\x10application/json:\x10application/jsonr0\n" +
	"\x1bMore about Pydio Cells Apis\x12\x11https://pydio.comZ+github.com/pydio/cells/v5/common/proto/restb\x06proto3"

var (
	file_cellsapi_rest_proto_rawDescOnce sync.Once
	file_cellsapi_rest_proto_rawDescData []byte
)

func file_cellsapi_rest_proto_rawDescGZIP() []byte {
	file_cellsapi_rest_proto_rawDescOnce.Do(func() {
		file_cellsapi_rest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cellsapi_rest_proto_rawDesc), len(file_cellsapi_rest_proto_rawDesc)))
	})
	return file_cellsapi_rest_proto_rawDescData
}

var file_cellsapi_rest_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cellsapi_rest_proto_goTypes = []any{
	(*DeleteWorkspaceRequest)(nil),              // 0: rest.DeleteWorkspaceRequest
	(*HealthServiceRequest)(nil),                // 1: rest.HealthServiceRequest
	(*ComponentStatus)(nil),                     // 2: rest.ComponentStatus
	(*HealthServiceResponse)(nil),               // 3: rest.HealthServiceResponse
	nil,                                         // 4: rest.HealthServiceResponse.ComponentsEntry
	(*Configuration)(nil),                       // 5: rest.Configuration
	(*object.DataSource)(nil),                   // 6: object.DataSource
	(*ListDataSourceRequest)(nil),               // 7: rest.ListDataSourceRequest
	(*ListVersioningPolicyRequest)(nil),         // 8: rest.ListVersioningPolicyRequest
	(*tree.VersioningPolicy)(nil),               // 9: tree.VersioningPolicy
	(*ListVirtualNodesRequest)(nil),             // 10: rest.ListVirtualNodesRequest
	(*ListServiceRequest)(nil),                  // 11: rest.ListServiceRequest
	(*ControlServiceRequest)(nil),               // 12: rest.ControlServiceRequest
	(*registry.ListRequest)(nil),                // 13: registry.ListRequest
	(*ListPeersAddressesRequest)(nil),           // 14: rest.ListPeersAddressesRequest
	(*ListPeerFoldersRequest)(nil),              // 15: rest.ListPeerFoldersRequest
	(*CreatePeerFolderRequest)(nil),             // 16: rest.CreatePeerFolderRequest
	(*ListStorageBucketsRequest)(nil),           // 17: rest.ListStorageBucketsRequest
	(*CreateStorageBucketRequest)(nil),          // 18: rest.CreateStorageBucketRequest
	(*ListProcessesRequest)(nil),                // 19: rest.ListProcessesRequest
	(*encryption.AdminListKeysRequest)(nil),     // 20: encryption.AdminListKeysRequest
	(*encryption.AdminCreateKeyRequest)(nil),    // 21: encryption.AdminCreateKeyRequest
	(*encryption.AdminDeleteKeyRequest)(nil),    // 22: encryption.AdminDeleteKeyRequest
	(*encryption.AdminExportKeyRequest)(nil),    // 23: encryption.AdminExportKeyRequest
	(*encryption.AdminImportKeyRequest)(nil),    // 24: encryption.AdminImportKeyRequest
	(*DiscoveryRequest)(nil),                    // 25: rest.DiscoveryRequest
	(*ConfigFormRequest)(nil),                   // 26: rest.ConfigFormRequest
	(*SchedulerActionsRequest)(nil),             // 27: rest.SchedulerActionsRequest
	(*SchedulerActionFormRequest)(nil),          // 28: rest.SchedulerActionFormRequest
	(*ListSitesRequest)(nil),                    // 29: rest.ListSitesRequest
	(*idm.Role)(nil),                            // 30: idm.Role
	(*SearchRoleRequest)(nil),                   // 31: rest.SearchRoleRequest
	(*idm.User)(nil),                            // 32: idm.User
	(*SearchUserRequest)(nil),                   // 33: rest.SearchUserRequest
	(*idm.ACL)(nil),                             // 34: idm.ACL
	(*SearchACLRequest)(nil),                    // 35: rest.SearchACLRequest
	(*idm.ListPolicyGroupsRequest)(nil),         // 36: idm.ListPolicyGroupsRequest
	(*idm.Workspace)(nil),                       // 37: idm.Workspace
	(*SearchWorkspaceRequest)(nil),              // 38: rest.SearchWorkspaceRequest
	(*activity.StreamActivitiesRequest)(nil),    // 39: activity.StreamActivitiesRequest
	(*activity.Subscription)(nil),               // 40: activity.Subscription
	(*activity.SearchSubscriptionsRequest)(nil), // 41: activity.SearchSubscriptionsRequest
	(*log.ListLogRequest)(nil),                  // 42: log.ListLogRequest
	(*RevokeRequest)(nil),                       // 43: rest.RevokeRequest
	(*ResetPasswordTokenRequest)(nil),           // 44: rest.ResetPasswordTokenRequest
	(*ResetPasswordRequest)(nil),                // 45: rest.ResetPasswordRequest
	(*DocumentAccessTokenRequest)(nil),          // 46: rest.DocumentAccessTokenRequest
	(*mailer.Mail)(nil),                         // 47: mailer.Mail
	(*tree.SearchRequest)(nil),                  // 48: tree.SearchRequest
	(*GetBulkMetaRequest)(nil),                  // 49: rest.GetBulkMetaRequest
	(*CreateNodesRequest)(nil),                  // 50: rest.CreateNodesRequest
	(*HeadNodeRequest)(nil),                     // 51: rest.HeadNodeRequest
	(*DeleteNodesRequest)(nil),                  // 52: rest.DeleteNodesRequest
	(*RestoreNodesRequest)(nil),                 // 53: rest.RestoreNodesRequest
	(*CreateSelectionRequest)(nil),              // 54: rest.CreateSelectionRequest
	(*ListTemplatesRequest)(nil),                // 55: rest.ListTemplatesRequest
	(*MetaNamespaceRequest)(nil),                // 56: rest.MetaNamespaceRequest
	(*MetaCollection)(nil),                      // 57: rest.MetaCollection
	(*idm.UpdateUserMetaRequest)(nil),           // 58: idm.UpdateUserMetaRequest
	(*idm.SearchUserMetaRequest)(nil),           // 59: idm.SearchUserMetaRequest
	(*UserBookmarksRequest)(nil),                // 60: rest.UserBookmarksRequest
	(*idm.UpdateUserMetaNamespaceRequest)(nil),  // 61: idm.UpdateUserMetaNamespaceRequest
	(*idm.ListUserMetaNamespaceRequest)(nil),    // 62: idm.ListUserMetaNamespaceRequest
	(*idm.GetFieldSchemaRequest)(nil),           // 63: idm.GetFieldSchemaRequest
	(*idm.GetNamespaceSchemaRequest)(nil),       // 64: idm.GetNamespaceSchemaRequest
	(*ListUserMetaTagsRequest)(nil),             // 65: rest.ListUserMetaTagsRequest
	(*PutUserMetaTagRequest)(nil),               // 66: rest.PutUserMetaTagRequest
	(*DeleteUserMetaTagsRequest)(nil),           // 67: rest.DeleteUserMetaTagsRequest
	(*UserJobRequest)(nil),                      // 68: rest.UserJobRequest
	(*jobs.ListJobsRequest)(nil),                // 69: jobs.ListJobsRequest
	(*jobs.CtrlCommand)(nil),                    // 70: jobs.CtrlCommand
	(*jobs.DeleteTasksRequest)(nil),             // 71: jobs.DeleteTasksRequest
	(*tree.ListNodesRequest)(nil),               // 72: tree.ListNodesRequest
	(*tree.ReadNodeRequest)(nil),                // 73: tree.ReadNodeRequest
	(*UserStateRequest)(nil),                    // 74: rest.UserStateRequest
	(*RelationRequest)(nil),                     // 75: rest.RelationRequest
	(*RecommendRequest)(nil),                    // 76: rest.RecommendRequest
	(*PutCellRequest)(nil),                      // 77: rest.PutCellRequest
	(*GetCellRequest)(nil),                      // 78: rest.GetCellRequest
	(*DeleteCellRequest)(nil),                   // 79: rest.DeleteCellRequest
	(*PutShareLinkRequest)(nil),                 // 80: rest.PutShareLinkRequest
	(*GetShareLinkRequest)(nil),                 // 81: rest.GetShareLinkRequest
	(*DeleteShareLinkRequest)(nil),              // 82: rest.DeleteShareLinkRequest
	(*ListSharedResourcesRequest)(nil),          // 83: rest.ListSharedResourcesRequest
	(*UpdateSharePoliciesRequest)(nil),          // 84: rest.UpdateSharePoliciesRequest
	(*install.GetDefaultsRequest)(nil),          // 85: install.GetDefaultsRequest
	(*install.InstallRequest)(nil),              // 86: install.InstallRequest
	(*install.PerformCheckRequest)(nil),         // 87: install.PerformCheckRequest
	(*install.GetAgreementRequest)(nil),         // 88: install.GetAgreementRequest
	(*install.InstallEventsRequest)(nil),        // 89: install.InstallEventsRequest
	(*update.UpdateRequest)(nil),                // 90: update.UpdateRequest
	(*update.ApplyUpdateRequest)(nil),           // 91: update.ApplyUpdateRequest
	(*FrontStateRequest)(nil),                   // 92: rest.FrontStateRequest
	(*FrontBootConfRequest)(nil),                // 93: rest.FrontBootConfRequest
	(*FrontMessagesRequest)(nil),                // 94: rest.FrontMessagesRequest
	(*FrontPluginsRequest)(nil),                 // 95: rest.FrontPluginsRequest
	(*FrontSessionRequest)(nil),                 // 96: rest.FrontSessionRequest
	(*FrontEnrollAuthRequest)(nil),              // 97: rest.FrontEnrollAuthRequest
	(*FrontBinaryRequest)(nil),                  // 98: rest.FrontBinaryRequest
	(*SettingsMenuRequest)(nil),                 // 99: rest.SettingsMenuRequest
	(*DeleteDataSourceResponse)(nil),            // 100: rest.DeleteDataSourceResponse
	(*DataSourceCollection)(nil),                // 101: rest.DataSourceCollection
	(*VersioningPolicyCollection)(nil),          // 102: rest.VersioningPolicyCollection
	(*NodesCollection)(nil),                     // 103: rest.NodesCollection
	(*ServiceCollection)(nil),                   // 104: rest.ServiceCollection
	(*ctl.Service)(nil),                         // 105: ctl.Service
	(*registry.ListResponse)(nil),               // 106: registry.ListResponse
	(*ListPeersAddressesResponse)(nil),          // 107: rest.ListPeersAddressesResponse
	(*CreatePeerFolderResponse)(nil),            // 108: rest.CreatePeerFolderResponse
	(*CreateStorageBucketResponse)(nil),         // 109: rest.CreateStorageBucketResponse
	(*ListProcessesResponse)(nil),               // 110: rest.ListProcessesResponse
	(*encryption.AdminListKeysResponse)(nil),    // 111: encryption.AdminListKeysResponse
	(*encryption.AdminCreateKeyResponse)(nil),   // 112: encryption.AdminCreateKeyResponse
	(*encryption.AdminDeleteKeyResponse)(nil),   // 113: encryption.AdminDeleteKeyResponse
	(*encryption.AdminExportKeyResponse)(nil),   // 114: encryption.AdminExportKeyResponse
	(*encryption.AdminImportKeyResponse)(nil),   // 115: encryption.AdminImportKeyResponse
	(*DiscoveryResponse)(nil),                   // 116: rest.DiscoveryResponse
	(*OpenApiResponse)(nil),                     // 117: rest.OpenApiResponse
	(*SchedulerActionsResponse)(nil),            // 118: rest.SchedulerActionsResponse
	(*SchedulerActionFormResponse)(nil),         // 119: rest.SchedulerActionFormResponse
	(*ListSitesResponse)(nil),                   // 120: rest.ListSitesResponse
	(*RolesCollection)(nil),                     // 121: rest.RolesCollection
	(*DeleteResponse)(nil),                      // 122: rest.DeleteResponse
	(*UsersCollection)(nil),                     // 123: rest.UsersCollection
	(*ACLCollection)(nil),                       // 124: rest.ACLCollection
	(*idm.ListPolicyGroupsResponse)(nil),        // 125: idm.ListPolicyGroupsResponse
	(*WorkspaceCollection)(nil),                 // 126: rest.WorkspaceCollection
	(*activity.Object)(nil),                     // 127: activity.Object
	(*SubscriptionsCollection)(nil),             // 128: rest.SubscriptionsCollection
	(*LogMessageCollection)(nil),                // 129: rest.LogMessageCollection
	(*RevokeResponse)(nil),                      // 130: rest.RevokeResponse
	(*ResetPasswordTokenResponse)(nil),          // 131: rest.ResetPasswordTokenResponse
	(*ResetPasswordResponse)(nil),               // 132: rest.ResetPasswordResponse
	(*DocumentAccessTokenResponse)(nil),         // 133: rest.DocumentAccessTokenResponse
	(*mailer.SendMailResponse)(nil),             // 134: mailer.SendMailResponse
	(*SearchResults)(nil),                       // 135: rest.SearchResults
	(*BulkMetaResponse)(nil),                    // 136: rest.BulkMetaResponse
	(*HeadNodeResponse)(nil),                    // 137: rest.HeadNodeResponse
	(*DeleteNodesResponse)(nil),                 // 138: rest.DeleteNodesResponse
	(*RestoreNodesResponse)(nil),                // 139: rest.RestoreNodesResponse
	(*CreateSelectionResponse)(nil),             // 140: rest.CreateSelectionResponse
	(*ListTemplatesResponse)(nil),               // 141: rest.ListTemplatesResponse
	(*tree.Node)(nil),                           // 142: tree.Node
	(*idm.UpdateUserMetaResponse)(nil),          // 143: idm.UpdateUserMetaResponse
	(*UserMetaCollection)(nil),                  // 144: rest.UserMetaCollection
	(*idm.UpdateUserMetaNamespaceResponse)(nil), // 145: idm.UpdateUserMetaNamespaceResponse
	(*UserMetaNamespaceCollection)(nil),         // 146: rest.UserMetaNamespaceCollection
	(*idm.JsonSchemaResponse)(nil),              // 147: idm.JsonSchemaResponse
	(*ListUserMetaTagsResponse)(nil),            // 148: rest.ListUserMetaTagsResponse
	(*PutUserMetaTagResponse)(nil),              // 149: rest.PutUserMetaTagResponse
	(*DeleteUserMetaTagsResponse)(nil),          // 150: rest.DeleteUserMetaTagsResponse
	(*UserJobResponse)(nil),                     // 151: rest.UserJobResponse
	(*UserJobsCollection)(nil),                  // 152: rest.UserJobsCollection
	(*jobs.CtrlCommandResponse)(nil),            // 153: jobs.CtrlCommandResponse
	(*jobs.DeleteTasksResponse)(nil),            // 154: jobs.DeleteTasksResponse
	(*tree.ReadNodeResponse)(nil),               // 155: tree.ReadNodeResponse
	(*UserStateResponse)(nil),                   // 156: rest.UserStateResponse
	(*RelationResponse)(nil),                    // 157: rest.RelationResponse
	(*RecommendResponse)(nil),                   // 158: rest.RecommendResponse
	(*Cell)(nil),                                // 159: rest.Cell
	(*DeleteCellResponse)(nil),                  // 160: rest.DeleteCellResponse
	(*ShareLink)(nil),                           // 161: rest.ShareLink
	(*DeleteShareLinkResponse)(nil),             // 162: rest.DeleteShareLinkResponse
	(*ListSharedResourcesResponse)(nil),         // 163: rest.ListSharedResourcesResponse
	(*UpdateSharePoliciesResponse)(nil),         // 164: rest.UpdateSharePoliciesResponse
	(*install.GetDefaultsResponse)(nil),         // 165: install.GetDefaultsResponse
	(*install.InstallResponse)(nil),             // 166: install.InstallResponse
	(*install.PerformCheckResponse)(nil),        // 167: install.PerformCheckResponse
	(*install.GetAgreementResponse)(nil),        // 168: install.GetAgreementResponse
	(*install.InstallEventsResponse)(nil),       // 169: install.InstallEventsResponse
	(*update.UpdateResponse)(nil),               // 170: update.UpdateResponse
	(*update.ApplyUpdateResponse)(nil),          // 171: update.ApplyUpdateResponse
	(*FrontStateResponse)(nil),                  // 172: rest.FrontStateResponse
	(*FrontBootConfResponse)(nil),               // 173: rest.FrontBootConfResponse
	(*FrontMessagesResponse)(nil),               // 174: rest.FrontMessagesResponse
	(*FrontPluginsResponse)(nil),                // 175: rest.FrontPluginsResponse
	(*FrontSessionResponse)(nil),                // 176: rest.FrontSessionResponse
	(*FrontEnrollAuthResponse)(nil),             // 177: rest.FrontEnrollAuthResponse
	(*FrontBinaryResponse)(nil),                 // 178: rest.FrontBinaryResponse
	(*SettingsMenuResponse)(nil),                // 179: rest.SettingsMenuResponse
}
var file_cellsapi_rest_proto_depIdxs = []int32{
	4,   // 0: rest.HealthServiceResponse.Components:type_name -> rest.HealthServiceResponse.ComponentsEntry
	2,   // 1: rest.HealthServiceResponse.ComponentsEntry.value:type_name -> rest.ComponentStatus
	5,   // 2: rest.ConfigService.PutConfig:input_type -> rest.Configuration
	5,   // 3: rest.ConfigService.GetConfig:input_type -> rest.Configuration
	6,   // 4: rest.ConfigService.PutDataSource:input_type -> object.DataSource
	6,   // 5: rest.ConfigService.GetDataSource:input_type -> object.DataSource
	6,   // 6: rest.ConfigService.DeleteDataSource:input_type -> object.DataSource
	7,   // 7: rest.ConfigService.ListDataSources:input_type -> rest.ListDataSourceRequest
	8,   // 8: rest.ConfigService.ListVersioningPolicies:input_type -> rest.ListVersioningPolicyRequest
	9,   // 9: rest.ConfigService.GetVersioningPolicy:input_type -> tree.VersioningPolicy
	10,  // 10: rest.ConfigService.ListVirtualNodes:input_type -> rest.ListVirtualNodesRequest
	11,  // 11: rest.ConfigService.ListServices:input_type -> rest.ListServiceRequest
	12,  // 12: rest.ConfigService.ControlService:input_type -> rest.ControlServiceRequest
	13,  // 13: rest.ConfigService.ListRegistry:input_type -> registry.ListRequest
	14,  // 14: rest.ConfigService.ListPeersAddresses:input_type -> rest.ListPeersAddressesRequest
	15,  // 15: rest.ConfigService.ListPeerFolders:input_type -> rest.ListPeerFoldersRequest
	16,  // 16: rest.ConfigService.CreatePeerFolder:input_type -> rest.CreatePeerFolderRequest
	17,  // 17: rest.ConfigService.ListStorageBuckets:input_type -> rest.ListStorageBucketsRequest
	18,  // 18: rest.ConfigService.CreateStorageBucket:input_type -> rest.CreateStorageBucketRequest
	19,  // 19: rest.ConfigService.ListProcesses:input_type -> rest.ListProcessesRequest
	20,  // 20: rest.ConfigService.ListEncryptionKeys:input_type -> encryption.AdminListKeysRequest
	21,  // 21: rest.ConfigService.CreateEncryptionKey:input_type -> encryption.AdminCreateKeyRequest
	22,  // 22: rest.ConfigService.DeleteEncryptionKey:input_type -> encryption.AdminDeleteKeyRequest
	23,  // 23: rest.ConfigService.ExportEncryptionKey:input_type -> encryption.AdminExportKeyRequest
	24,  // 24: rest.ConfigService.ImportEncryptionKey:input_type -> encryption.AdminImportKeyRequest
	25,  // 25: rest.ConfigService.EndpointsDiscovery:input_type -> rest.DiscoveryRequest
	25,  // 26: rest.ConfigService.OpenApiDiscovery:input_type -> rest.DiscoveryRequest
	26,  // 27: rest.ConfigService.ConfigFormsDiscovery:input_type -> rest.ConfigFormRequest
	27,  // 28: rest.ConfigService.SchedulerActionsDiscovery:input_type -> rest.SchedulerActionsRequest
	28,  // 29: rest.ConfigService.SchedulerActionFormDiscovery:input_type -> rest.SchedulerActionFormRequest
	29,  // 30: rest.ConfigService.ListSites:input_type -> rest.ListSitesRequest
	30,  // 31: rest.RoleService.SetRole:input_type -> idm.Role
	30,  // 32: rest.RoleService.DeleteRole:input_type -> idm.Role
	30,  // 33: rest.RoleService.GetRole:input_type -> idm.Role
	31,  // 34: rest.RoleService.SearchRoles:input_type -> rest.SearchRoleRequest
	32,  // 35: rest.UserService.PutUser:input_type -> idm.User
	32,  // 36: rest.UserService.DeleteUser:input_type -> idm.User
	32,  // 37: rest.UserService.GetUser:input_type -> idm.User
	33,  // 38: rest.UserService.SearchUsers:input_type -> rest.SearchUserRequest
	32,  // 39: rest.UserService.PutRoles:input_type -> idm.User
	34,  // 40: rest.ACLService.PutAcl:input_type -> idm.ACL
	34,  // 41: rest.ACLService.DeleteAcl:input_type -> idm.ACL
	35,  // 42: rest.ACLService.SearchAcls:input_type -> rest.SearchACLRequest
	36,  // 43: rest.PolicyService.ListPolicies:input_type -> idm.ListPolicyGroupsRequest
	37,  // 44: rest.WorkspaceService.PutWorkspace:input_type -> idm.Workspace
	0,   // 45: rest.WorkspaceService.DeleteWorkspace:input_type -> rest.DeleteWorkspaceRequest
	38,  // 46: rest.WorkspaceService.SearchWorkspaces:input_type -> rest.SearchWorkspaceRequest
	39,  // 47: rest.ActivityService.Stream:input_type -> activity.StreamActivitiesRequest
	40,  // 48: rest.ActivityService.Subscribe:input_type -> activity.Subscription
	41,  // 49: rest.ActivityService.SearchSubscriptions:input_type -> activity.SearchSubscriptionsRequest
	42,  // 50: rest.LogService.Syslog:input_type -> log.ListLogRequest
	43,  // 51: rest.TokenService.Revoke:input_type -> rest.RevokeRequest
	44,  // 52: rest.TokenService.ResetPasswordToken:input_type -> rest.ResetPasswordTokenRequest
	45,  // 53: rest.TokenService.ResetPassword:input_type -> rest.ResetPasswordRequest
	46,  // 54: rest.TokenService.GenerateDocumentAccessToken:input_type -> rest.DocumentAccessTokenRequest
	47,  // 55: rest.MailerService.Send:input_type -> mailer.Mail
	48,  // 56: rest.SearchService.Nodes:input_type -> tree.SearchRequest
	49,  // 57: rest.TreeService.BulkStatNodes:input_type -> rest.GetBulkMetaRequest
	50,  // 58: rest.TreeService.CreateNodes:input_type -> rest.CreateNodesRequest
	51,  // 59: rest.TreeService.HeadNode:input_type -> rest.HeadNodeRequest
	52,  // 60: rest.TreeService.DeleteNodes:input_type -> rest.DeleteNodesRequest
	53,  // 61: rest.TreeService.RestoreNodes:input_type -> rest.RestoreNodesRequest
	54,  // 62: rest.TreeService.CreateSelection:input_type -> rest.CreateSelectionRequest
	55,  // 63: rest.TemplatesService.ListTemplates:input_type -> rest.ListTemplatesRequest
	56,  // 64: rest.MetaService.GetMeta:input_type -> rest.MetaNamespaceRequest
	57,  // 65: rest.MetaService.SetMeta:input_type -> rest.MetaCollection
	56,  // 66: rest.MetaService.DeleteMeta:input_type -> rest.MetaNamespaceRequest
	49,  // 67: rest.MetaService.GetBulkMeta:input_type -> rest.GetBulkMetaRequest
	58,  // 68: rest.UserMetaService.UpdateUserMeta:input_type -> idm.UpdateUserMetaRequest
	59,  // 69: rest.UserMetaService.SearchUserMeta:input_type -> idm.SearchUserMetaRequest
	60,  // 70: rest.UserMetaService.UserBookmarks:input_type -> rest.UserBookmarksRequest
	61,  // 71: rest.UserMetaService.UpdateUserMetaNamespace:input_type -> idm.UpdateUserMetaNamespaceRequest
	62,  // 72: rest.UserMetaService.ListUserMetaNamespace:input_type -> idm.ListUserMetaNamespaceRequest
	63,  // 73: rest.UserMetaService.GetFieldSchema:input_type -> idm.GetFieldSchemaRequest
	64,  // 74: rest.UserMetaService.GetNamespaceSchema:input_type -> idm.GetNamespaceSchemaRequest
	65,  // 75: rest.UserMetaService.ListUserMetaTags:input_type -> rest.ListUserMetaTagsRequest
	66,  // 76: rest.UserMetaService.PutUserMetaTag:input_type -> rest.PutUserMetaTagRequest
	67,  // 77: rest.UserMetaService.DeleteUserMetaTags:input_type -> rest.DeleteUserMetaTagsRequest
	68,  // 78: rest.JobsService.UserCreateJob:input_type -> rest.UserJobRequest
	69,  // 79: rest.JobsService.UserListJobs:input_type -> jobs.ListJobsRequest
	70,  // 80: rest.JobsService.UserControlJob:input_type -> jobs.CtrlCommand
	71,  // 81: rest.JobsService.UserDeleteTasks:input_type -> jobs.DeleteTasksRequest
	42,  // 82: rest.JobsService.ListTasksLogs:input_type -> log.ListLogRequest
	72,  // 83: rest.AdminTreeService.ListAdminTree:input_type -> tree.ListNodesRequest
	73,  // 84: rest.AdminTreeService.StatAdminTree:input_type -> tree.ReadNodeRequest
	74,  // 85: rest.GraphService.UserState:input_type -> rest.UserStateRequest
	75,  // 86: rest.GraphService.Relation:input_type -> rest.RelationRequest
	76,  // 87: rest.GraphService.Recommend:input_type -> rest.RecommendRequest
	77,  // 88: rest.ShareService.PutCell:input_type -> rest.PutCellRequest
	78,  // 89: rest.ShareService.GetCell:input_type -> rest.GetCellRequest
	79,  // 90: rest.ShareService.DeleteCell:input_type -> rest.DeleteCellRequest
	80,  // 91: rest.ShareService.PutShareLink:input_type -> rest.PutShareLinkRequest
	81,  // 92: rest.ShareService.GetShareLink:input_type -> rest.GetShareLinkRequest
	82,  // 93: rest.ShareService.DeleteShareLink:input_type -> rest.DeleteShareLinkRequest
	83,  // 94: rest.ShareService.ListSharedResources:input_type -> rest.ListSharedResourcesRequest
	84,  // 95: rest.ShareService.UpdateSharePolicies:input_type -> rest.UpdateSharePoliciesRequest
	85,  // 96: rest.InstallService.GetInstall:input_type -> install.GetDefaultsRequest
	86,  // 97: rest.InstallService.PostInstall:input_type -> install.InstallRequest
	87,  // 98: rest.InstallService.PerformInstallCheck:input_type -> install.PerformCheckRequest
	88,  // 99: rest.InstallService.GetAgreement:input_type -> install.GetAgreementRequest
	89,  // 100: rest.InstallService.InstallEvents:input_type -> install.InstallEventsRequest
	90,  // 101: rest.UpdateService.UpdateRequired:input_type -> update.UpdateRequest
	91,  // 102: rest.UpdateService.ApplyUpdate:input_type -> update.ApplyUpdateRequest
	92,  // 103: rest.FrontendService.FrontState:input_type -> rest.FrontStateRequest
	93,  // 104: rest.FrontendService.FrontBootConf:input_type -> rest.FrontBootConfRequest
	94,  // 105: rest.FrontendService.FrontMessages:input_type -> rest.FrontMessagesRequest
	95,  // 106: rest.FrontendService.FrontPlugins:input_type -> rest.FrontPluginsRequest
	96,  // 107: rest.FrontendService.FrontSession:input_type -> rest.FrontSessionRequest
	97,  // 108: rest.FrontendService.FrontEnrollAuth:input_type -> rest.FrontEnrollAuthRequest
	98,  // 109: rest.FrontendService.FrontServeBinary:input_type -> rest.FrontBinaryRequest
	98,  // 110: rest.FrontendService.FrontPutBinary:input_type -> rest.FrontBinaryRequest
	99,  // 111: rest.FrontendService.SettingsMenu:input_type -> rest.SettingsMenuRequest
	1,   // 112: rest.HealthService.ApiPing:input_type -> rest.HealthServiceRequest
	1,   // 113: rest.HealthService.ApiLive:input_type -> rest.HealthServiceRequest
	1,   // 114: rest.HealthService.ApiReady:input_type -> rest.HealthServiceRequest
	1,   // 115: rest.HealthService.ServiceLive:input_type -> rest.HealthServiceRequest
	1,   // 116: rest.HealthService.ServiceReady:input_type -> rest.HealthServiceRequest
	5,   // 117: rest.ConfigService.PutConfig:output_type -> rest.Configuration
	5,   // 118: rest.ConfigService.GetConfig:output_type -> rest.Configuration
	6,   // 119: rest.ConfigService.PutDataSource:output_type -> object.DataSource
	6,   // 120: rest.ConfigService.GetDataSource:output_type -> object.DataSource
	100, // 121: rest.ConfigService.DeleteDataSource:output_type -> rest.DeleteDataSourceResponse
	101, // 122: rest.ConfigService.ListDataSources:output_type -> rest.DataSourceCollection
	102, // 123: rest.ConfigService.ListVersioningPolicies:output_type -> rest.VersioningPolicyCollection
	9,   // 124: rest.ConfigService.GetVersioningPolicy:output_type -> tree.VersioningPolicy
	103, // 125: rest.ConfigService.ListVirtualNodes:output_type -> rest.NodesCollection
	104, // 126: rest.ConfigService.ListServices:output_type -> rest.ServiceCollection
	105, // 127: rest.ConfigService.ControlService:output_type -> ctl.Service
	106, // 128: rest.ConfigService.ListRegistry:output_type -> registry.ListResponse
	107, // 129: rest.ConfigService.ListPeersAddresses:output_type -> rest.ListPeersAddressesResponse
	103, // 130: rest.ConfigService.ListPeerFolders:output_type -> rest.NodesCollection
	108, // 131: rest.ConfigService.CreatePeerFolder:output_type -> rest.CreatePeerFolderResponse
	103, // 132: rest.ConfigService.ListStorageBuckets:output_type -> rest.NodesCollection
	109, // 133: rest.ConfigService.CreateStorageBucket:output_type -> rest.CreateStorageBucketResponse
	110, // 134: rest.ConfigService.ListProcesses:output_type -> rest.ListProcessesResponse
	111, // 135: rest.ConfigService.ListEncryptionKeys:output_type -> encryption.AdminListKeysResponse
	112, // 136: rest.ConfigService.CreateEncryptionKey:output_type -> encryption.AdminCreateKeyResponse
	113, // 137: rest.ConfigService.DeleteEncryptionKey:output_type -> encryption.AdminDeleteKeyResponse
	114, // 138: rest.ConfigService.ExportEncryptionKey:output_type -> encryption.AdminExportKeyResponse
	115, // 139: rest.ConfigService.ImportEncryptionKey:output_type -> encryption.AdminImportKeyResponse
	116, // 140: rest.ConfigService.EndpointsDiscovery:output_type -> rest.DiscoveryResponse
	117, // 141: rest.ConfigService.OpenApiDiscovery:output_type -> rest.OpenApiResponse
	116, // 142: rest.ConfigService.ConfigFormsDiscovery:output_type -> rest.DiscoveryResponse
	118, // 143: rest.ConfigService.SchedulerActionsDiscovery:output_type -> rest.SchedulerActionsResponse
	119, // 144: rest.ConfigService.SchedulerActionFormDiscovery:output_type -> rest.SchedulerActionFormResponse
	120, // 145: rest.ConfigService.ListSites:output_type -> rest.ListSitesResponse
	30,  // 146: rest.RoleService.SetRole:output_type -> idm.Role
	30,  // 147: rest.RoleService.DeleteRole:output_type -> idm.Role
	30,  // 148: rest.RoleService.GetRole:output_type -> idm.Role
	121, // 149: rest.RoleService.SearchRoles:output_type -> rest.RolesCollection
	32,  // 150: rest.UserService.PutUser:output_type -> idm.User
	122, // 151: rest.UserService.DeleteUser:output_type -> rest.DeleteResponse
	32,  // 152: rest.UserService.GetUser:output_type -> idm.User
	123, // 153: rest.UserService.SearchUsers:output_type -> rest.UsersCollection
	32,  // 154: rest.UserService.PutRoles:output_type -> idm.User
	34,  // 155: rest.ACLService.PutAcl:output_type -> idm.ACL
	122, // 156: rest.ACLService.DeleteAcl:output_type -> rest.DeleteResponse
	124, // 157: rest.ACLService.SearchAcls:output_type -> rest.ACLCollection
	125, // 158: rest.PolicyService.ListPolicies:output_type -> idm.ListPolicyGroupsResponse
	37,  // 159: rest.WorkspaceService.PutWorkspace:output_type -> idm.Workspace
	122, // 160: rest.WorkspaceService.DeleteWorkspace:output_type -> rest.DeleteResponse
	126, // 161: rest.WorkspaceService.SearchWorkspaces:output_type -> rest.WorkspaceCollection
	127, // 162: rest.ActivityService.Stream:output_type -> activity.Object
	40,  // 163: rest.ActivityService.Subscribe:output_type -> activity.Subscription
	128, // 164: rest.ActivityService.SearchSubscriptions:output_type -> rest.SubscriptionsCollection
	129, // 165: rest.LogService.Syslog:output_type -> rest.LogMessageCollection
	130, // 166: rest.TokenService.Revoke:output_type -> rest.RevokeResponse
	131, // 167: rest.TokenService.ResetPasswordToken:output_type -> rest.ResetPasswordTokenResponse
	132, // 168: rest.TokenService.ResetPassword:output_type -> rest.ResetPasswordResponse
	133, // 169: rest.TokenService.GenerateDocumentAccessToken:output_type -> rest.DocumentAccessTokenResponse
	134, // 170: rest.MailerService.Send:output_type -> mailer.SendMailResponse
	135, // 171: rest.SearchService.Nodes:output_type -> rest.SearchResults
	136, // 172: rest.TreeService.BulkStatNodes:output_type -> rest.BulkMetaResponse
	103, // 173: rest.TreeService.CreateNodes:output_type -> rest.NodesCollection
	137, // 174: rest.TreeService.HeadNode:output_type -> rest.HeadNodeResponse
	138, // 175: rest.TreeService.DeleteNodes:output_type -> rest.DeleteNodesResponse
	139, // 176: rest.TreeService.RestoreNodes:output_type -> rest.RestoreNodesResponse
	140, // 177: rest.TreeService.CreateSelection:output_type -> rest.CreateSelectionResponse
	141, // 178: rest.TemplatesService.ListTemplates:output_type -> rest.ListTemplatesResponse
	142, // 179: rest.MetaService.GetMeta:output_type -> tree.Node
	142, // 180: rest.MetaService.SetMeta:output_type -> tree.Node
	142, // 181: rest.MetaService.DeleteMeta:output_type -> tree.Node
	136, // 182: rest.MetaService.GetBulkMeta:output_type -> rest.BulkMetaResponse
	143, // 183: rest.UserMetaService.UpdateUserMeta:output_type -> idm.UpdateUserMetaResponse
	144, // 184: rest.UserMetaService.SearchUserMeta:output_type -> rest.UserMetaCollection
	136, // 185: rest.UserMetaService.UserBookmarks:output_type -> rest.BulkMetaResponse
	145, // 186: rest.UserMetaService.UpdateUserMetaNamespace:output_type -> idm.UpdateUserMetaNamespaceResponse
	146, // 187: rest.UserMetaService.ListUserMetaNamespace:output_type -> rest.UserMetaNamespaceCollection
	147, // 188: rest.UserMetaService.GetFieldSchema:output_type -> idm.JsonSchemaResponse
	147, // 189: rest.UserMetaService.GetNamespaceSchema:output_type -> idm.JsonSchemaResponse
	148, // 190: rest.UserMetaService.ListUserMetaTags:output_type -> rest.ListUserMetaTagsResponse
	149, // 191: rest.UserMetaService.PutUserMetaTag:output_type -> rest.PutUserMetaTagResponse
	150, // 192: rest.UserMetaService.DeleteUserMetaTags:output_type -> rest.DeleteUserMetaTagsResponse
	151, // 193: rest.JobsService.UserCreateJob:output_type -> rest.UserJobResponse
	152, // 194: rest.JobsService.UserListJobs:output_type -> rest.UserJobsCollection
	153, // 195: rest.JobsService.UserControlJob:output_type -> jobs.CtrlCommandResponse
	154, // 196: rest.JobsService.UserDeleteTasks:output_type -> jobs.DeleteTasksResponse
	129, // 197: rest.JobsService.ListTasksLogs:output_type -> rest.LogMessageCollection
	103, // 198: rest.AdminTreeService.ListAdminTree:output_type -> rest.NodesCollection
	155, // 199: rest.AdminTreeService.StatAdminTree:output_type -> tree.ReadNodeResponse
	156, // 200: rest.GraphService.UserState:output_type -> rest.UserStateResponse
	157, // 201: rest.GraphService.Relation:output_type -> rest.RelationResponse
	158, // 202: rest.GraphService.Recommend:output_type -> rest.RecommendResponse
	159, // 203: rest.ShareService.PutCell:output_type -> rest.Cell
	159, // 204: rest.ShareService.GetCell:output_type -> rest.Cell
	160, // 205: rest.ShareService.DeleteCell:output_type -> rest.DeleteCellResponse
	161, // 206: rest.ShareService.PutShareLink:output_type -> rest.ShareLink
	161, // 207: rest.ShareService.GetShareLink:output_type -> rest.ShareLink
	162, // 208: rest.ShareService.DeleteShareLink:output_type -> rest.DeleteShareLinkResponse
	163, // 209: rest.ShareService.ListSharedResources:output_type -> rest.ListSharedResourcesResponse
	164, // 210: rest.ShareService.UpdateSharePolicies:output_type -> rest.UpdateSharePoliciesResponse
	165, // 211: rest.InstallService.GetInstall:output_type -> install.GetDefaultsResponse
	166, // 212: rest.InstallService.PostInstall:output_type -> install.InstallResponse
	167, // 213: rest.InstallService.PerformInstallCheck:output_type -> install.PerformCheckResponse
	168, // 214: rest.InstallService.GetAgreement:output_type -> install.GetAgreementResponse
	169, // 215: rest.InstallService.InstallEvents:output_type -> install.InstallEventsResponse
	170, // 216: rest.UpdateService.UpdateRequired:output_type -> update.UpdateResponse
	171, // 217: rest.UpdateService.ApplyUpdate:output_type -> update.ApplyUpdateResponse
	172, // 218: rest.FrontendService.FrontState:output_type -> rest.FrontStateResponse
	173, // 219: rest.FrontendService.FrontBootConf:output_type -> rest.FrontBootConfResponse
	174, // 220: rest.FrontendService.FrontMessages:output_type -> rest.FrontMessagesResponse
	175, // 221: rest.FrontendService.FrontPlugins:output_type -> rest.FrontPluginsResponse
	176, // 222: rest.FrontendService.FrontSession:output_type -> rest.FrontSessionResponse
	177, // 223: rest.FrontendService.FrontEnrollAuth:output_type -> rest.FrontEnrollAuthResponse
	178, // 224: rest.FrontendService.FrontServeBinary:output_type -> rest.FrontBinaryResponse
	178, // 225: rest.FrontendService.FrontPutBinary:output_type -> rest.FrontBinaryResponse
	179, // 226: rest.FrontendService.SettingsMenu:output_type -> rest.SettingsMenuResponse
	3,   // 227: rest.HealthService.ApiPing:output_type -> rest.HealthServiceResponse
	3,   // 228: rest.HealthService.ApiLive:output_type -> rest.HealthServiceResponse
	3,   // 229: rest.HealthService.ApiReady:output_type -> rest.HealthServiceResponse
	3,   // 230: rest.HealthService.ServiceLive:output_type -> rest.HealthServiceResponse
	3,   // 231: rest.HealthService.ServiceReady:output_type -> rest.HealthServiceResponse
	117, // [117:232] is the sub-list for method output_type
	2,   // [2:117] is the sub-list for method input_type
	2,   // [2:2] is the sub-list for extension type_name
	2,   // [2:2] is the sub-list for extension extendee
	0,   // [0:2] is the sub-list for field type_name
}

func init() { file_cellsapi_rest_proto_init() }
func file_cellsapi_rest_proto_init() {
	if File_cellsapi_rest_proto != nil {
		return
	}
	file_cellsapi_common_proto_init()
	file_cellsapi_data_proto_init()
	file_cellsapi_idm_proto_init()
	file_cellsapi_broker_proto_init()
	file_cellsapi_config_proto_init()
	file_cellsapi_scheduler_proto_init()
	file_cellsapi_graph_proto_init()
	file_cellsapi_share_proto_init()
	file_cellsapi_frontend_proto_init()
	file_cellsapi_templates_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cellsapi_rest_proto_rawDesc), len(file_cellsapi_rest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   23,
		},
		GoTypes:           file_cellsapi_rest_proto_goTypes,
		DependencyIndexes: file_cellsapi_rest_proto_depIdxs,
		MessageInfos:      file_cellsapi_rest_proto_msgTypes,
	}.Build()
	File_cellsapi_rest_proto = out.File
	file_cellsapi_rest_proto_goTypes = nil
	file_cellsapi_rest_proto_depIdxs = nil
}
