// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package rest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import tree "github.com/pydio/cells/common/proto/tree"
import docstore "github.com/pydio/cells/common/proto/docstore"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SearchResults struct {
	Results []*tree.Node `protobuf:"bytes,1,rep,name=Results" json:"Results,omitempty"`
	Total   int32        `protobuf:"varint,2,opt,name=Total" json:"Total,omitempty"`
}

func (m *SearchResults) Reset()                    { *m = SearchResults{} }
func (m *SearchResults) String() string            { return proto.CompactTextString(m) }
func (*SearchResults) ProtoMessage()               {}
func (*SearchResults) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *SearchResults) GetResults() []*tree.Node {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *SearchResults) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

// Generic container for responses sending pagination information
type Pagination struct {
	// Current Limit parameter, either passed by request or default value
	Limit int32 `protobuf:"varint,1,opt,name=Limit" json:"Limit,omitempty"`
	// Current Offset value
	CurrentOffset int32 `protobuf:"varint,2,opt,name=CurrentOffset" json:"CurrentOffset,omitempty"`
	// Total number of records
	Total int32 `protobuf:"varint,3,opt,name=Total" json:"Total,omitempty"`
	// Current number of Page
	CurrentPage int32 `protobuf:"varint,4,opt,name=CurrentPage" json:"CurrentPage,omitempty"`
	// Number of detected pages
	TotalPages int32 `protobuf:"varint,5,opt,name=TotalPages" json:"TotalPages,omitempty"`
	// Offset value for next page if there is one
	NextOffset int32 `protobuf:"varint,6,opt,name=NextOffset" json:"NextOffset,omitempty"`
	// Offset value for previous page, if there is one
	PrevOffset int32 `protobuf:"varint,7,opt,name=PrevOffset" json:"PrevOffset,omitempty"`
}

func (m *Pagination) Reset()                    { *m = Pagination{} }
func (m *Pagination) String() string            { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()               {}
func (*Pagination) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *Pagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetCurrentOffset() int32 {
	if m != nil {
		return m.CurrentOffset
	}
	return 0
}

func (m *Pagination) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Pagination) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Pagination) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Pagination) GetNextOffset() int32 {
	if m != nil {
		return m.NextOffset
	}
	return 0
}

func (m *Pagination) GetPrevOffset() int32 {
	if m != nil {
		return m.PrevOffset
	}
	return 0
}

type Metadata struct {
	Namespace string `protobuf:"bytes,1,opt,name=Namespace" json:"Namespace,omitempty"`
	JsonMeta  string `protobuf:"bytes,2,opt,name=JsonMeta" json:"JsonMeta,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *Metadata) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Metadata) GetJsonMeta() string {
	if m != nil {
		return m.JsonMeta
	}
	return ""
}

type MetaCollection struct {
	NodePath  string      `protobuf:"bytes,1,opt,name=NodePath" json:"NodePath,omitempty"`
	Metadatas []*Metadata `protobuf:"bytes,2,rep,name=Metadatas" json:"Metadatas,omitempty"`
}

func (m *MetaCollection) Reset()                    { *m = MetaCollection{} }
func (m *MetaCollection) String() string            { return proto.CompactTextString(m) }
func (*MetaCollection) ProtoMessage()               {}
func (*MetaCollection) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *MetaCollection) GetNodePath() string {
	if m != nil {
		return m.NodePath
	}
	return ""
}

func (m *MetaCollection) GetMetadatas() []*Metadata {
	if m != nil {
		return m.Metadatas
	}
	return nil
}

type MetaNamespaceRequest struct {
	NodePath  string   `protobuf:"bytes,1,opt,name=NodePath" json:"NodePath,omitempty"`
	Namespace []string `protobuf:"bytes,2,rep,name=Namespace" json:"Namespace,omitempty"`
}

func (m *MetaNamespaceRequest) Reset()                    { *m = MetaNamespaceRequest{} }
func (m *MetaNamespaceRequest) String() string            { return proto.CompactTextString(m) }
func (*MetaNamespaceRequest) ProtoMessage()               {}
func (*MetaNamespaceRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *MetaNamespaceRequest) GetNodePath() string {
	if m != nil {
		return m.NodePath
	}
	return ""
}

func (m *MetaNamespaceRequest) GetNamespace() []string {
	if m != nil {
		return m.Namespace
	}
	return nil
}

type GetBulkMetaRequest struct {
	NodePaths        []string `protobuf:"bytes,1,rep,name=NodePaths" json:"NodePaths,omitempty"`
	NodeUuids        []string `protobuf:"bytes,2,rep,name=NodeUuids" json:"NodeUuids,omitempty"`
	AllMetaProviders bool     `protobuf:"varint,3,opt,name=AllMetaProviders" json:"AllMetaProviders,omitempty"`
	Versions         bool     `protobuf:"varint,4,opt,name=Versions" json:"Versions,omitempty"`
	Offset           int32    `protobuf:"varint,5,opt,name=Offset" json:"Offset,omitempty"`
	Limit            int32    `protobuf:"varint,6,opt,name=Limit" json:"Limit,omitempty"`
}

func (m *GetBulkMetaRequest) Reset()                    { *m = GetBulkMetaRequest{} }
func (m *GetBulkMetaRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBulkMetaRequest) ProtoMessage()               {}
func (*GetBulkMetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *GetBulkMetaRequest) GetNodePaths() []string {
	if m != nil {
		return m.NodePaths
	}
	return nil
}

func (m *GetBulkMetaRequest) GetNodeUuids() []string {
	if m != nil {
		return m.NodeUuids
	}
	return nil
}

func (m *GetBulkMetaRequest) GetAllMetaProviders() bool {
	if m != nil {
		return m.AllMetaProviders
	}
	return false
}

func (m *GetBulkMetaRequest) GetVersions() bool {
	if m != nil {
		return m.Versions
	}
	return false
}

func (m *GetBulkMetaRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetBulkMetaRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type BulkMetaResponse struct {
	Nodes      []*tree.Node `protobuf:"bytes,1,rep,name=Nodes" json:"Nodes,omitempty"`
	Pagination *Pagination  `protobuf:"bytes,5,opt,name=Pagination" json:"Pagination,omitempty"`
}

func (m *BulkMetaResponse) Reset()                    { *m = BulkMetaResponse{} }
func (m *BulkMetaResponse) String() string            { return proto.CompactTextString(m) }
func (*BulkMetaResponse) ProtoMessage()               {}
func (*BulkMetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *BulkMetaResponse) GetNodes() []*tree.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *BulkMetaResponse) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type HeadNodeRequest struct {
	Node string `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
}

func (m *HeadNodeRequest) Reset()                    { *m = HeadNodeRequest{} }
func (m *HeadNodeRequest) String() string            { return proto.CompactTextString(m) }
func (*HeadNodeRequest) ProtoMessage()               {}
func (*HeadNodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *HeadNodeRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type HeadNodeResponse struct {
	Node *tree.Node `protobuf:"bytes,1,opt,name=Node" json:"Node,omitempty"`
}

func (m *HeadNodeResponse) Reset()                    { *m = HeadNodeResponse{} }
func (m *HeadNodeResponse) String() string            { return proto.CompactTextString(m) }
func (*HeadNodeResponse) ProtoMessage()               {}
func (*HeadNodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *HeadNodeResponse) GetNode() *tree.Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type CreateNodesRequest struct {
	Nodes        []*tree.Node `protobuf:"bytes,1,rep,name=Nodes" json:"Nodes,omitempty"`
	Recursive    bool         `protobuf:"varint,2,opt,name=Recursive" json:"Recursive,omitempty"`
	TemplateUUID string       `protobuf:"bytes,3,opt,name=TemplateUUID" json:"TemplateUUID,omitempty"`
}

func (m *CreateNodesRequest) Reset()                    { *m = CreateNodesRequest{} }
func (m *CreateNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateNodesRequest) ProtoMessage()               {}
func (*CreateNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *CreateNodesRequest) GetNodes() []*tree.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *CreateNodesRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

func (m *CreateNodesRequest) GetTemplateUUID() string {
	if m != nil {
		return m.TemplateUUID
	}
	return ""
}

type CreateSelectionRequest struct {
	Nodes        []*tree.Node `protobuf:"bytes,1,rep,name=Nodes" json:"Nodes,omitempty"`
	TargetAction string       `protobuf:"bytes,2,opt,name=TargetAction" json:"TargetAction,omitempty"`
	Persist      bool         `protobuf:"varint,3,opt,name=Persist" json:"Persist,omitempty"`
}

func (m *CreateSelectionRequest) Reset()                    { *m = CreateSelectionRequest{} }
func (m *CreateSelectionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSelectionRequest) ProtoMessage()               {}
func (*CreateSelectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *CreateSelectionRequest) GetNodes() []*tree.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *CreateSelectionRequest) GetTargetAction() string {
	if m != nil {
		return m.TargetAction
	}
	return ""
}

func (m *CreateSelectionRequest) GetPersist() bool {
	if m != nil {
		return m.Persist
	}
	return false
}

type CreateSelectionResponse struct {
	SelectionUUID string       `protobuf:"bytes,1,opt,name=SelectionUUID" json:"SelectionUUID,omitempty"`
	Nodes         []*tree.Node `protobuf:"bytes,2,rep,name=Nodes" json:"Nodes,omitempty"`
}

func (m *CreateSelectionResponse) Reset()                    { *m = CreateSelectionResponse{} }
func (m *CreateSelectionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSelectionResponse) ProtoMessage()               {}
func (*CreateSelectionResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *CreateSelectionResponse) GetSelectionUUID() string {
	if m != nil {
		return m.SelectionUUID
	}
	return ""
}

func (m *CreateSelectionResponse) GetNodes() []*tree.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodesCollection struct {
	Parent   *tree.Node   `protobuf:"bytes,1,opt,name=Parent" json:"Parent,omitempty"`
	Children []*tree.Node `protobuf:"bytes,2,rep,name=Children" json:"Children,omitempty"`
}

func (m *NodesCollection) Reset()                    { *m = NodesCollection{} }
func (m *NodesCollection) String() string            { return proto.CompactTextString(m) }
func (*NodesCollection) ProtoMessage()               {}
func (*NodesCollection) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

func (m *NodesCollection) GetParent() *tree.Node {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *NodesCollection) GetChildren() []*tree.Node {
	if m != nil {
		return m.Children
	}
	return nil
}

type DeleteNodesRequest struct {
	Nodes     []*tree.Node `protobuf:"bytes,1,rep,name=Nodes" json:"Nodes,omitempty"`
	Recursive bool         `protobuf:"varint,2,opt,name=Recursive" json:"Recursive,omitempty"`
}

func (m *DeleteNodesRequest) Reset()                    { *m = DeleteNodesRequest{} }
func (m *DeleteNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodesRequest) ProtoMessage()               {}
func (*DeleteNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

func (m *DeleteNodesRequest) GetNodes() []*tree.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *DeleteNodesRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

type BackgroundJobResult struct {
	Uuid     string `protobuf:"bytes,1,opt,name=Uuid" json:"Uuid,omitempty"`
	Label    string `protobuf:"bytes,2,opt,name=Label" json:"Label,omitempty"`
	NodeUuid string `protobuf:"bytes,3,opt,name=NodeUuid" json:"NodeUuid,omitempty"`
}

func (m *BackgroundJobResult) Reset()                    { *m = BackgroundJobResult{} }
func (m *BackgroundJobResult) String() string            { return proto.CompactTextString(m) }
func (*BackgroundJobResult) ProtoMessage()               {}
func (*BackgroundJobResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func (m *BackgroundJobResult) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BackgroundJobResult) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *BackgroundJobResult) GetNodeUuid() string {
	if m != nil {
		return m.NodeUuid
	}
	return ""
}

type DeleteNodesResponse struct {
	DeleteJobs []*BackgroundJobResult `protobuf:"bytes,1,rep,name=DeleteJobs" json:"DeleteJobs,omitempty"`
}

func (m *DeleteNodesResponse) Reset()                    { *m = DeleteNodesResponse{} }
func (m *DeleteNodesResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteNodesResponse) ProtoMessage()               {}
func (*DeleteNodesResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{15} }

func (m *DeleteNodesResponse) GetDeleteJobs() []*BackgroundJobResult {
	if m != nil {
		return m.DeleteJobs
	}
	return nil
}

type RestoreNodesRequest struct {
	Nodes []*tree.Node `protobuf:"bytes,1,rep,name=Nodes" json:"Nodes,omitempty"`
}

func (m *RestoreNodesRequest) Reset()                    { *m = RestoreNodesRequest{} }
func (m *RestoreNodesRequest) String() string            { return proto.CompactTextString(m) }
func (*RestoreNodesRequest) ProtoMessage()               {}
func (*RestoreNodesRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{16} }

func (m *RestoreNodesRequest) GetNodes() []*tree.Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type RestoreNodesResponse struct {
	RestoreJobs []*BackgroundJobResult `protobuf:"bytes,1,rep,name=RestoreJobs" json:"RestoreJobs,omitempty"`
}

func (m *RestoreNodesResponse) Reset()                    { *m = RestoreNodesResponse{} }
func (m *RestoreNodesResponse) String() string            { return proto.CompactTextString(m) }
func (*RestoreNodesResponse) ProtoMessage()               {}
func (*RestoreNodesResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{17} }

func (m *RestoreNodesResponse) GetRestoreJobs() []*BackgroundJobResult {
	if m != nil {
		return m.RestoreJobs
	}
	return nil
}

type ListDocstoreRequest struct {
	StoreID   string                  `protobuf:"bytes,1,opt,name=StoreID" json:"StoreID,omitempty"`
	Query     *docstore.DocumentQuery `protobuf:"bytes,2,opt,name=Query" json:"Query,omitempty"`
	CountOnly bool                    `protobuf:"varint,3,opt,name=CountOnly" json:"CountOnly,omitempty"`
}

func (m *ListDocstoreRequest) Reset()                    { *m = ListDocstoreRequest{} }
func (m *ListDocstoreRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDocstoreRequest) ProtoMessage()               {}
func (*ListDocstoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18} }

func (m *ListDocstoreRequest) GetStoreID() string {
	if m != nil {
		return m.StoreID
	}
	return ""
}

func (m *ListDocstoreRequest) GetQuery() *docstore.DocumentQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *ListDocstoreRequest) GetCountOnly() bool {
	if m != nil {
		return m.CountOnly
	}
	return false
}

type DocstoreCollection struct {
	Docs  []*docstore.Document `protobuf:"bytes,1,rep,name=Docs" json:"Docs,omitempty"`
	Total int64                `protobuf:"varint,2,opt,name=Total" json:"Total,omitempty"`
}

func (m *DocstoreCollection) Reset()                    { *m = DocstoreCollection{} }
func (m *DocstoreCollection) String() string            { return proto.CompactTextString(m) }
func (*DocstoreCollection) ProtoMessage()               {}
func (*DocstoreCollection) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{19} }

func (m *DocstoreCollection) GetDocs() []*docstore.Document {
	if m != nil {
		return m.Docs
	}
	return nil
}

func (m *DocstoreCollection) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type ChangeRequest struct {
	SeqID   int64  `protobuf:"varint,1,opt,name=SeqID" json:"SeqID,omitempty"`
	Filter  string `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	Flatten bool   `protobuf:"varint,3,opt,name=flatten" json:"flatten,omitempty"`
	Stream  bool   `protobuf:"varint,4,opt,name=stream" json:"stream,omitempty"`
}

func (m *ChangeRequest) Reset()                    { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()               {}
func (*ChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{20} }

func (m *ChangeRequest) GetSeqID() int64 {
	if m != nil {
		return m.SeqID
	}
	return 0
}

func (m *ChangeRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ChangeRequest) GetFlatten() bool {
	if m != nil {
		return m.Flatten
	}
	return false
}

func (m *ChangeRequest) GetStream() bool {
	if m != nil {
		return m.Stream
	}
	return false
}

type ChangeCollection struct {
	Changes   []*tree.SyncChange `protobuf:"bytes,1,rep,name=Changes,json=changes" json:"Changes,omitempty"`
	LastSeqId int64              `protobuf:"varint,2,opt,name=LastSeqId,json=last_seq" json:"LastSeqId,omitempty"`
}

func (m *ChangeCollection) Reset()                    { *m = ChangeCollection{} }
func (m *ChangeCollection) String() string            { return proto.CompactTextString(m) }
func (*ChangeCollection) ProtoMessage()               {}
func (*ChangeCollection) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{21} }

func (m *ChangeCollection) GetChanges() []*tree.SyncChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

func (m *ChangeCollection) GetLastSeqId() int64 {
	if m != nil {
		return m.LastSeqId
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchResults)(nil), "rest.SearchResults")
	proto.RegisterType((*Pagination)(nil), "rest.Pagination")
	proto.RegisterType((*Metadata)(nil), "rest.Metadata")
	proto.RegisterType((*MetaCollection)(nil), "rest.MetaCollection")
	proto.RegisterType((*MetaNamespaceRequest)(nil), "rest.MetaNamespaceRequest")
	proto.RegisterType((*GetBulkMetaRequest)(nil), "rest.GetBulkMetaRequest")
	proto.RegisterType((*BulkMetaResponse)(nil), "rest.BulkMetaResponse")
	proto.RegisterType((*HeadNodeRequest)(nil), "rest.HeadNodeRequest")
	proto.RegisterType((*HeadNodeResponse)(nil), "rest.HeadNodeResponse")
	proto.RegisterType((*CreateNodesRequest)(nil), "rest.CreateNodesRequest")
	proto.RegisterType((*CreateSelectionRequest)(nil), "rest.CreateSelectionRequest")
	proto.RegisterType((*CreateSelectionResponse)(nil), "rest.CreateSelectionResponse")
	proto.RegisterType((*NodesCollection)(nil), "rest.NodesCollection")
	proto.RegisterType((*DeleteNodesRequest)(nil), "rest.DeleteNodesRequest")
	proto.RegisterType((*BackgroundJobResult)(nil), "rest.BackgroundJobResult")
	proto.RegisterType((*DeleteNodesResponse)(nil), "rest.DeleteNodesResponse")
	proto.RegisterType((*RestoreNodesRequest)(nil), "rest.RestoreNodesRequest")
	proto.RegisterType((*RestoreNodesResponse)(nil), "rest.RestoreNodesResponse")
	proto.RegisterType((*ListDocstoreRequest)(nil), "rest.ListDocstoreRequest")
	proto.RegisterType((*DocstoreCollection)(nil), "rest.DocstoreCollection")
	proto.RegisterType((*ChangeRequest)(nil), "rest.ChangeRequest")
	proto.RegisterType((*ChangeCollection)(nil), "rest.ChangeCollection")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 927 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0x96, 0xe3, 0xf8, 0x76, 0x4c, 0x5a, 0x6b, 0x12, 0xb5, 0x26, 0x54, 0x55, 0x34, 0x0a, 0x55,
	0x55, 0x81, 0x8d, 0xd2, 0x07, 0x84, 0xfa, 0xd4, 0xda, 0x12, 0x10, 0x42, 0x6a, 0xc6, 0x09, 0x0f,
	0x54, 0x08, 0x8d, 0x77, 0x8f, 0xed, 0x55, 0xd7, 0x3b, 0xce, 0xcc, 0x6c, 0x94, 0x48, 0xfc, 0x3e,
	0x7e, 0x07, 0x3f, 0x05, 0xcd, 0x6d, 0x2f, 0x4a, 0x80, 0x20, 0xf1, 0x92, 0xec, 0xf9, 0xce, 0xed,
	0x3b, 0x97, 0x99, 0x31, 0x40, 0xcc, 0x35, 0x1f, 0x6d, 0xa5, 0xd0, 0x82, 0xec, 0x4a, 0x54, 0xfa,
	0xf0, 0xf5, 0x2a, 0xd1, 0xeb, 0x7c, 0x31, 0x8a, 0xc4, 0x66, 0xbc, 0xbd, 0x8d, 0x13, 0x31, 0x8e,
	0x30, 0x4d, 0xd5, 0x38, 0x12, 0x9b, 0x8d, 0xc8, 0xc6, 0xd6, 0x74, 0xac, 0x25, 0xa2, 0xfd, 0xe3,
	0x5c, 0x0f, 0xdf, 0x3c, 0xc4, 0x29, 0x16, 0x91, 0xd2, 0x42, 0x62, 0xf1, 0xe1, 0x9c, 0xe9, 0x0f,
	0xb0, 0x37, 0x47, 0x2e, 0xa3, 0x35, 0x43, 0x95, 0xa7, 0x5a, 0x91, 0x63, 0xe8, 0xf8, 0xcf, 0x61,
	0xe3, 0xa8, 0xf9, 0xb2, 0x7f, 0x02, 0x23, 0x9b, 0xeb, 0x5c, 0xc4, 0xc8, 0x82, 0x8a, 0x1c, 0x40,
	0xeb, 0x42, 0x68, 0x9e, 0x0e, 0x77, 0x8e, 0x1a, 0x2f, 0x5b, 0xcc, 0x09, 0xf4, 0xcf, 0x06, 0xc0,
	0x8c, 0xaf, 0x92, 0x8c, 0xeb, 0x44, 0x64, 0xc6, 0xe8, 0x2c, 0xd9, 0x24, 0x7a, 0xd8, 0x70, 0x46,
	0x56, 0x20, 0xc7, 0xb0, 0x37, 0xc9, 0xa5, 0xc4, 0x4c, 0xbf, 0x5f, 0x2e, 0x15, 0x6a, 0x1f, 0xa2,
	0x0e, 0x96, 0x09, 0x9a, 0x95, 0x04, 0xe4, 0x08, 0xfa, 0xde, 0x6c, 0xc6, 0x57, 0x38, 0xdc, 0xb5,
	0xba, 0x2a, 0x44, 0x9e, 0x03, 0x58, 0x53, 0x23, 0xa8, 0x61, 0xcb, 0x1a, 0x54, 0x10, 0xa3, 0x3f,
	0xc7, 0x9b, 0x90, 0xba, 0xed, 0xf4, 0x25, 0x62, 0xf4, 0x33, 0x89, 0xd7, 0x5e, 0xdf, 0x71, 0xfa,
	0x12, 0xa1, 0x53, 0xe8, 0xfe, 0x88, 0x9a, 0x9b, 0xc9, 0x91, 0x67, 0xd0, 0x3b, 0xe7, 0x1b, 0x54,
	0x5b, 0x1e, 0xa1, 0xad, 0xb1, 0xc7, 0x4a, 0x80, 0x1c, 0x42, 0xf7, 0x54, 0x89, 0xcc, 0x58, 0xdb,
	0x12, 0x7b, 0xac, 0x90, 0xe9, 0x2f, 0xf0, 0xc8, 0xfc, 0x9f, 0x88, 0x34, 0xc5, 0xc8, 0xf6, 0xea,
	0x10, 0xba, 0xa6, 0xc3, 0x33, 0xae, 0xd7, 0x3e, 0x54, 0x21, 0x93, 0x2f, 0xa0, 0x17, 0x72, 0xaa,
	0xe1, 0x8e, 0x1d, 0xca, 0xa3, 0x91, 0xd9, 0x97, 0x51, 0x80, 0x59, 0x69, 0x40, 0x67, 0x70, 0x60,
	0x84, 0x82, 0x08, 0xc3, 0xab, 0x1c, 0x95, 0xfe, 0xc7, 0x0c, 0xb5, 0x4a, 0x4c, 0x86, 0x6a, 0x25,
	0xf4, 0x8f, 0x06, 0x90, 0x6f, 0x51, 0xbf, 0xcb, 0xd3, 0x8f, 0x26, 0x72, 0x08, 0x68, 0x9c, 0x7c,
	0x00, 0xb7, 0x2b, 0xc6, 0x29, 0x00, 0x41, 0x7b, 0x99, 0x27, 0xb1, 0x2a, 0x42, 0x06, 0x80, 0xbc,
	0x82, 0xc1, 0xdb, 0x34, 0x35, 0xd1, 0x66, 0x52, 0x5c, 0x27, 0x31, 0x4a, 0x65, 0x27, 0xdd, 0x65,
	0x77, 0x70, 0x43, 0xfc, 0x67, 0x94, 0x2a, 0x11, 0x99, 0xb2, 0x13, 0xef, 0xb2, 0x42, 0x26, 0x4f,
	0xa0, 0xed, 0x47, 0xe5, 0x46, 0xdd, 0x2e, 0xd7, 0xc7, 0xad, 0x5e, 0xbb, 0xb2, 0x7a, 0x74, 0x09,
	0x83, 0xb2, 0x08, 0xb5, 0x15, 0x99, 0x42, 0x72, 0x04, 0x2d, 0x43, 0xeb, 0xbe, 0x6d, 0x77, 0x0a,
	0xf2, 0x55, 0x75, 0xa9, 0x6d, 0x9e, 0xfe, 0xc9, 0xc0, 0xf5, 0xbf, 0xc4, 0x59, 0xc5, 0x86, 0x7e,
	0x0e, 0x8f, 0xbf, 0x43, 0x1e, 0xdb, 0x20, 0xbe, 0x59, 0x04, 0x76, 0x8d, 0xe8, 0x3b, 0x6f, 0xbf,
	0xe9, 0x09, 0x0c, 0x4a, 0x33, 0x4f, 0xe7, 0x79, 0xc5, 0xae, 0xce, 0xc6, 0xf9, 0xdc, 0x00, 0x99,
	0x48, 0xe4, 0x1a, 0x2d, 0xb7, 0x10, 0xfd, 0xdf, 0x8b, 0x78, 0x06, 0x3d, 0x86, 0x51, 0x2e, 0x55,
	0x72, 0x8d, 0x76, 0x1d, 0xbb, 0xac, 0x04, 0x08, 0x85, 0x4f, 0x2e, 0x70, 0xb3, 0x4d, 0xb9, 0xc6,
	0xcb, 0xcb, 0xef, 0xa7, 0x76, 0x14, 0x3d, 0x56, 0xc3, 0xe8, 0x0d, 0x3c, 0x71, 0x99, 0xe7, 0xe8,
	0x97, 0xf6, 0xe1, 0xd9, 0x4d, 0x7c, 0x2e, 0x57, 0xa8, 0xdf, 0x5a, 0x47, 0x7f, 0x1e, 0x6a, 0x18,
	0x19, 0x42, 0x67, 0x66, 0xc6, 0xaa, 0xb4, 0xdf, 0x84, 0x20, 0x52, 0x0e, 0x4f, 0xef, 0x64, 0xf6,
	0xed, 0x3a, 0x36, 0xd7, 0x97, 0x07, 0x2d, 0x73, 0xd7, 0xdf, 0x3a, 0x58, 0x12, 0xdc, 0xf9, 0x1b,
	0x82, 0xf4, 0x57, 0x78, 0x6c, 0x3f, 0x2a, 0x27, 0x92, 0x42, 0x7b, 0xc6, 0xcd, 0xbd, 0x72, 0xcf,
	0x2c, 0xbc, 0x86, 0xbc, 0x80, 0xee, 0x64, 0x9d, 0xa4, 0xb1, 0xc4, 0xec, 0x9e, 0xd8, 0x85, 0x8e,
	0x5e, 0x00, 0x99, 0x62, 0x8a, 0xff, 0xef, 0xd4, 0xe8, 0x07, 0xd8, 0x7f, 0xc7, 0xa3, 0x8f, 0x2b,
	0x29, 0xf2, 0x2c, 0x3e, 0x15, 0x0b, 0x77, 0x39, 0x9b, 0x55, 0x33, 0x87, 0x2c, 0xac, 0x9a, 0xf9,
	0xb6, 0xe7, 0x81, 0x2f, 0x30, 0xf5, 0x9d, 0x77, 0x42, 0xb8, 0x12, 0xac, 0x75, 0xb3, 0xbc, 0x12,
	0x8c, 0x4c, 0x67, 0xb0, 0x5f, 0xa3, 0xec, 0x1b, 0xfe, 0x0d, 0x80, 0x83, 0x4f, 0xc5, 0x22, 0x10,
	0xff, 0xd4, 0x1d, 0x86, 0x7b, 0xb8, 0xb0, 0x8a, 0x31, 0xfd, 0x1a, 0xf6, 0x19, 0xda, 0xb7, 0xe7,
	0xbf, 0x75, 0x81, 0xce, 0xe1, 0xa0, 0xee, 0xe8, 0xb9, 0xbc, 0x81, 0xbe, 0xc7, 0x1f, 0x46, 0xa6,
	0x6a, 0x4d, 0x7f, 0x87, 0xfd, 0xb3, 0x44, 0xe9, 0xa9, 0x7f, 0x0e, 0x03, 0x9b, 0x21, 0x74, 0xe6,
	0x46, 0x2e, 0x56, 0x29, 0x88, 0xe4, 0x4b, 0x68, 0xfd, 0x94, 0xa3, 0xbc, 0xb5, 0x2d, 0xec, 0x9f,
	0x3c, 0x1d, 0x15, 0x2f, 0xe9, 0x54, 0x44, 0xf9, 0x06, 0x33, 0x6d, 0xd5, 0xcc, 0x59, 0x99, 0xd1,
	0x4d, 0x44, 0x9e, 0xe9, 0xf7, 0x59, 0x7a, 0xeb, 0x17, 0xba, 0x04, 0x28, 0x03, 0x12, 0x32, 0x57,
	0x56, 0xee, 0x05, 0xec, 0x1a, 0xd4, 0x57, 0x42, 0xee, 0x66, 0x60, 0x56, 0x5f, 0x7f, 0x7d, 0x9b,
	0xe1, 0xf5, 0x15, 0xb0, 0x37, 0x59, 0xf3, 0x6c, 0x55, 0xd4, 0x72, 0x00, 0xad, 0x39, 0x5e, 0xf9,
	0x4a, 0x9a, 0xcc, 0x09, 0xe6, 0xca, 0x5c, 0x26, 0xa9, 0x46, 0xe9, 0x77, 0xc1, 0x4b, 0xa6, 0xf2,
	0x65, 0xca, 0xb5, 0xc6, 0x2c, 0x9c, 0x3f, 0x2f, 0x1a, 0x0f, 0xa5, 0x25, 0xf2, 0x8d, 0xbf, 0x7e,
	0xbd, 0x44, 0x3f, 0xc0, 0xc0, 0x25, 0xac, 0x94, 0xf0, 0x0a, 0x3a, 0x0e, 0x0b, 0x55, 0x0c, 0xdc,
	0x3c, 0xe7, 0xb7, 0x59, 0xe4, 0xd9, 0x75, 0x22, 0x67, 0x40, 0x3e, 0x83, 0xde, 0x19, 0x57, 0xda,
	0xd0, 0x8a, 0x7d, 0x29, 0xdd, 0x94, 0x2b, 0xfd, 0x9b, 0xc2, 0xab, 0x45, 0xdb, 0xfe, 0x3e, 0x79,
	0xfd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x02, 0x42, 0x78, 0x25, 0x09, 0x00, 0x00,
}
