// Code generated by protoc-gen-go. DO NOT EDIT.
// source: frontend.proto

package rest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Frontend Log Level
type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_NOTICE  LogLevel = 2
	LogLevel_WARNING LogLevel = 3
	LogLevel_ERROR   LogLevel = 4
)

var LogLevel_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "NOTICE",
	3: "WARNING",
	4: "ERROR",
}
var LogLevel_value = map[string]int32{
	"DEBUG":   0,
	"INFO":    1,
	"NOTICE":  2,
	"WARNING": 3,
	"ERROR":   4,
}

func (x LogLevel) String() string {
	return proto.EnumName(LogLevel_name, int32(x))
}
func (LogLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

// Frontend message to log
type FrontLogMessage struct {
	Level       LogLevel `protobuf:"varint,1,opt,name=Level,enum=rest.LogLevel" json:"Level,omitempty"`
	Ip          string   `protobuf:"bytes,2,opt,name=Ip" json:"Ip,omitempty"`
	UserId      string   `protobuf:"bytes,3,opt,name=UserId" json:"UserId,omitempty"`
	WorkspaceId string   `protobuf:"bytes,4,opt,name=WorkspaceId" json:"WorkspaceId,omitempty"`
	Source      string   `protobuf:"bytes,5,opt,name=Source" json:"Source,omitempty"`
	Prefix      string   `protobuf:"bytes,6,opt,name=Prefix" json:"Prefix,omitempty"`
	Message     string   `protobuf:"bytes,7,opt,name=Message" json:"Message,omitempty"`
	Nodes       []string `protobuf:"bytes,8,rep,name=Nodes" json:"Nodes,omitempty"`
}

func (m *FrontLogMessage) Reset()                    { *m = FrontLogMessage{} }
func (m *FrontLogMessage) String() string            { return proto.CompactTextString(m) }
func (*FrontLogMessage) ProtoMessage()               {}
func (*FrontLogMessage) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *FrontLogMessage) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_DEBUG
}

func (m *FrontLogMessage) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *FrontLogMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *FrontLogMessage) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *FrontLogMessage) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *FrontLogMessage) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *FrontLogMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FrontLogMessage) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// Basic response for confirmation
type FrontLogResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
}

func (m *FrontLogResponse) Reset()                    { *m = FrontLogResponse{} }
func (m *FrontLogResponse) String() string            { return proto.CompactTextString(m) }
func (*FrontLogResponse) ProtoMessage()               {}
func (*FrontLogResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *FrontLogResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SettingsMenuRequest struct {
}

func (m *SettingsMenuRequest) Reset()                    { *m = SettingsMenuRequest{} }
func (m *SettingsMenuRequest) String() string            { return proto.CompactTextString(m) }
func (*SettingsMenuRequest) ProtoMessage()               {}
func (*SettingsMenuRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

type SettingsEntryMeta struct {
	IconClass string `protobuf:"bytes,1,opt,name=IconClass,json=icon_class" json:"IconClass,omitempty"`
	Component string `protobuf:"bytes,2,opt,name=Component,json=component" json:"Component,omitempty"`
	Props     string `protobuf:"bytes,3,opt,name=Props,json=props" json:"Props,omitempty"`
}

func (m *SettingsEntryMeta) Reset()                    { *m = SettingsEntryMeta{} }
func (m *SettingsEntryMeta) String() string            { return proto.CompactTextString(m) }
func (*SettingsEntryMeta) ProtoMessage()               {}
func (*SettingsEntryMeta) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *SettingsEntryMeta) GetIconClass() string {
	if m != nil {
		return m.IconClass
	}
	return ""
}

func (m *SettingsEntryMeta) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *SettingsEntryMeta) GetProps() string {
	if m != nil {
		return m.Props
	}
	return ""
}

type SettingsEntry struct {
	Key         string             `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Label       string             `protobuf:"bytes,2,opt,name=Label,json=LABEL" json:"Label,omitempty"`
	Description string             `protobuf:"bytes,3,opt,name=Description,json=DESCRIPTION" json:"Description,omitempty"`
	Manager     string             `protobuf:"bytes,4,opt,name=Manager,json=MANAGER" json:"Manager,omitempty"`
	Alias       string             `protobuf:"bytes,5,opt,name=Alias,json=ALIAS" json:"Alias,omitempty"`
	Metadata    *SettingsEntryMeta `protobuf:"bytes,6,opt,name=Metadata,json=METADATA" json:"Metadata,omitempty"`
}

func (m *SettingsEntry) Reset()                    { *m = SettingsEntry{} }
func (m *SettingsEntry) String() string            { return proto.CompactTextString(m) }
func (*SettingsEntry) ProtoMessage()               {}
func (*SettingsEntry) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *SettingsEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SettingsEntry) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *SettingsEntry) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SettingsEntry) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

func (m *SettingsEntry) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *SettingsEntry) GetMetadata() *SettingsEntryMeta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type SettingsSection struct {
	Key         string           `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Label       string           `protobuf:"bytes,2,opt,name=Label,json=LABEL" json:"Label,omitempty"`
	Description string           `protobuf:"bytes,3,opt,name=Description,json=DESCRIPTION" json:"Description,omitempty"`
	Children    []*SettingsEntry `protobuf:"bytes,4,rep,name=Children,json=CHILDREN" json:"Children,omitempty"`
}

func (m *SettingsSection) Reset()                    { *m = SettingsSection{} }
func (m *SettingsSection) String() string            { return proto.CompactTextString(m) }
func (*SettingsSection) ProtoMessage()               {}
func (*SettingsSection) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *SettingsSection) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SettingsSection) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *SettingsSection) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SettingsSection) GetChildren() []*SettingsEntry {
	if m != nil {
		return m.Children
	}
	return nil
}

type SettingsMenuResponse struct {
	RootMetadata *SettingsEntryMeta `protobuf:"bytes,1,opt,name=RootMetadata,json=__metadata__" json:"RootMetadata,omitempty"`
	Sections     []*SettingsSection `protobuf:"bytes,2,rep,name=Sections" json:"Sections,omitempty"`
}

func (m *SettingsMenuResponse) Reset()                    { *m = SettingsMenuResponse{} }
func (m *SettingsMenuResponse) String() string            { return proto.CompactTextString(m) }
func (*SettingsMenuResponse) ProtoMessage()               {}
func (*SettingsMenuResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *SettingsMenuResponse) GetRootMetadata() *SettingsEntryMeta {
	if m != nil {
		return m.RootMetadata
	}
	return nil
}

func (m *SettingsMenuResponse) GetSections() []*SettingsSection {
	if m != nil {
		return m.Sections
	}
	return nil
}

type FrontBootConfRequest struct {
}

func (m *FrontBootConfRequest) Reset()                    { *m = FrontBootConfRequest{} }
func (m *FrontBootConfRequest) String() string            { return proto.CompactTextString(m) }
func (*FrontBootConfRequest) ProtoMessage()               {}
func (*FrontBootConfRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

type FrontBootConfResponse struct {
	JsonData map[string]string `protobuf:"bytes,1,rep,name=JsonData" json:"JsonData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *FrontBootConfResponse) Reset()                    { *m = FrontBootConfResponse{} }
func (m *FrontBootConfResponse) String() string            { return proto.CompactTextString(m) }
func (*FrontBootConfResponse) ProtoMessage()               {}
func (*FrontBootConfResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *FrontBootConfResponse) GetJsonData() map[string]string {
	if m != nil {
		return m.JsonData
	}
	return nil
}

func init() {
	proto.RegisterType((*FrontLogMessage)(nil), "rest.FrontLogMessage")
	proto.RegisterType((*FrontLogResponse)(nil), "rest.FrontLogResponse")
	proto.RegisterType((*SettingsMenuRequest)(nil), "rest.SettingsMenuRequest")
	proto.RegisterType((*SettingsEntryMeta)(nil), "rest.SettingsEntryMeta")
	proto.RegisterType((*SettingsEntry)(nil), "rest.SettingsEntry")
	proto.RegisterType((*SettingsSection)(nil), "rest.SettingsSection")
	proto.RegisterType((*SettingsMenuResponse)(nil), "rest.SettingsMenuResponse")
	proto.RegisterType((*FrontBootConfRequest)(nil), "rest.FrontBootConfRequest")
	proto.RegisterType((*FrontBootConfResponse)(nil), "rest.FrontBootConfResponse")
	proto.RegisterEnum("rest.LogLevel", LogLevel_name, LogLevel_value)
}

func init() { proto.RegisterFile("frontend.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 629 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x3e, 0xce, 0xaf, 0x3d, 0x69, 0x53, 0x9f, 0xed, 0xcf, 0xb1, 0x8e, 0x40, 0x8a, 0x2c, 0x2e,
	0x02, 0x42, 0x41, 0xb4, 0x37, 0x88, 0x5e, 0xb9, 0x8e, 0x5b, 0x0c, 0x8e, 0x53, 0x6d, 0x52, 0xf5,
	0x32, 0x72, 0x9d, 0x49, 0xb0, 0x9a, 0xee, 0x1a, 0xaf, 0x53, 0xd1, 0x17, 0xe0, 0x8a, 0x37, 0xe0,
	0x5d, 0x78, 0x17, 0xde, 0x04, 0xad, 0xbd, 0x2e, 0x04, 0x2a, 0xae, 0xb8, 0xcb, 0xf7, 0x7d, 0x33,
	0xb3, 0x33, 0xf3, 0x4d, 0x0c, 0xdd, 0x45, 0xc6, 0x59, 0x8e, 0x6c, 0x3e, 0x48, 0x33, 0x9e, 0x73,
	0xd2, 0xc8, 0x50, 0xe4, 0xf6, 0x37, 0x0d, 0x76, 0x4e, 0xa5, 0x10, 0xf0, 0xe5, 0x08, 0x85, 0x88,
	0x96, 0x48, 0x9e, 0x40, 0x33, 0xc0, 0x5b, 0x5c, 0x59, 0x5a, 0x4f, 0xeb, 0x77, 0x0f, 0xbb, 0x03,
	0x19, 0x39, 0x08, 0xf8, 0xb2, 0x60, 0x69, 0x29, 0x92, 0x2e, 0xd4, 0xfc, 0xd4, 0xaa, 0xf5, 0xb4,
	0xbe, 0x41, 0x6b, 0x7e, 0x4a, 0x0e, 0xa0, 0x75, 0x21, 0x30, 0xf3, 0xe7, 0x56, 0xbd, 0xe0, 0x14,
	0x22, 0x3d, 0xe8, 0x5c, 0xf2, 0xec, 0x5a, 0xa4, 0x51, 0x8c, 0xfe, 0xdc, 0x6a, 0x14, 0xe2, 0xcf,
	0x94, 0xcc, 0x9c, 0xf0, 0x75, 0x16, 0xa3, 0xd5, 0x2c, 0x33, 0x4b, 0x24, 0xf9, 0xf3, 0x0c, 0x17,
	0xc9, 0x47, 0xab, 0x55, 0xf2, 0x25, 0x22, 0x16, 0xb4, 0x55, 0xab, 0x56, 0xbb, 0x10, 0x2a, 0x48,
	0xf6, 0xa0, 0x19, 0xf2, 0x39, 0x0a, 0x4b, 0xef, 0xd5, 0xfb, 0x06, 0x2d, 0x81, 0xfd, 0x1c, 0xcc,
	0x6a, 0x44, 0x8a, 0x22, 0xe5, 0x4c, 0xa0, 0xac, 0x31, 0x59, 0xc7, 0x31, 0x0a, 0x51, 0x4c, 0xa9,
	0xd3, 0x0a, 0xda, 0xfb, 0xb0, 0x3b, 0xc1, 0x3c, 0x4f, 0xd8, 0x52, 0x8c, 0x90, 0xad, 0x29, 0x7e,
	0x58, 0xcb, 0x45, 0x2d, 0xe0, 0xdf, 0x8a, 0xf6, 0x58, 0x9e, 0xdd, 0x8d, 0x30, 0x8f, 0xc8, 0x63,
	0x30, 0xfc, 0x98, 0x33, 0x77, 0x15, 0xa9, 0x3a, 0x06, 0x85, 0x24, 0xe6, 0x6c, 0x16, 0x4b, 0x86,
	0x3c, 0x02, 0xc3, 0xe5, 0x37, 0x29, 0x67, 0xc8, 0x72, 0xb5, 0x29, 0x23, 0xae, 0x08, 0xd9, 0xec,
	0x79, 0xc6, 0x53, 0xa1, 0xf6, 0xd5, 0x4c, 0x25, 0xb0, 0xbf, 0x6a, 0xb0, 0xbd, 0xf1, 0x10, 0x31,
	0xa1, 0xfe, 0x0e, 0xef, 0x54, 0x79, 0xf9, 0x53, 0x66, 0x06, 0xd1, 0x15, 0xae, 0x54, 0xcd, 0x66,
	0xe0, 0x9c, 0x78, 0x81, 0x5c, 0xf4, 0x10, 0x45, 0x9c, 0x25, 0x69, 0x9e, 0x70, 0xa6, 0xaa, 0x76,
	0x86, 0xde, 0xc4, 0xa5, 0xfe, 0xf9, 0xd4, 0x1f, 0x87, 0xc5, 0xe2, 0x22, 0x16, 0x2d, 0x31, 0x53,
	0x36, 0xb4, 0x47, 0x4e, 0xe8, 0x9c, 0x79, 0x54, 0x56, 0x74, 0x56, 0x49, 0x24, 0x94, 0x03, 0x4d,
	0x27, 0xf0, 0x9d, 0x09, 0x39, 0x02, 0x5d, 0x8e, 0x39, 0x8f, 0xf2, 0xa8, 0xb0, 0xa0, 0x73, 0xf8,
	0x5f, 0x79, 0x0b, 0xbf, 0x6d, 0x82, 0xea, 0x23, 0x6f, 0xea, 0x0c, 0x9d, 0xa9, 0x63, 0x7f, 0xd6,
	0x60, 0xa7, 0xd2, 0x27, 0x18, 0xcb, 0x5e, 0xfe, 0xe2, 0x08, 0x2f, 0x40, 0x77, 0xdf, 0x27, 0xab,
	0x79, 0x86, 0xcc, 0x6a, 0xf4, 0xea, 0xfd, 0xce, 0xe1, 0xee, 0x03, 0x2d, 0x51, 0xdd, 0x7d, 0xe3,
	0x07, 0x43, 0xea, 0x85, 0xf6, 0x27, 0x0d, 0xf6, 0x36, 0xfd, 0x54, 0x17, 0x70, 0x0c, 0x5b, 0x94,
	0xf3, 0xfc, 0x7e, 0x40, 0xed, 0xcf, 0x03, 0x6e, 0xcd, 0x66, 0x37, 0x2a, 0x74, 0x36, 0x23, 0x2f,
	0x41, 0x57, 0xb3, 0x09, 0xab, 0x56, 0xb4, 0xb1, 0xbf, 0x99, 0xa8, 0x54, 0x7a, 0x1f, 0x66, 0x1f,
	0xc0, 0x5e, 0x71, 0x85, 0x27, 0x9c, 0xe7, 0x2e, 0x67, 0x8b, 0xea, 0xb0, 0xbe, 0x68, 0xb0, 0xff,
	0x8b, 0xa0, 0x3a, 0xf4, 0x40, 0x7f, 0x2b, 0x38, 0x1b, 0x96, 0xdd, 0xc9, 0x47, 0x9e, 0x96, 0x8f,
	0x3c, 0x18, 0x3e, 0xa8, 0x62, 0xd5, 0x06, 0x2a, 0xf8, 0xff, 0x31, 0x6c, 0x6f, 0x48, 0xd2, 0x8d,
	0xeb, 0x1f, 0x6e, 0x5c, 0x97, 0x6e, 0xdc, 0x46, 0xab, 0x35, 0x56, 0x6e, 0x14, 0xe0, 0x75, 0xed,
	0x95, 0xf6, 0xcc, 0x05, 0xbd, 0xfa, 0xe3, 0x13, 0x03, 0x9a, 0x43, 0xef, 0xe4, 0xe2, 0xcc, 0xfc,
	0x87, 0xe8, 0xd0, 0xf0, 0xc3, 0xd3, 0xb1, 0xa9, 0x11, 0x80, 0x56, 0x38, 0x9e, 0xfa, 0xae, 0x67,
	0xd6, 0x48, 0x07, 0xda, 0x97, 0x0e, 0x0d, 0xfd, 0xf0, 0xcc, 0xac, 0xcb, 0x68, 0x8f, 0xd2, 0x31,
	0x35, 0x1b, 0x57, 0xad, 0xe2, 0x8b, 0x73, 0xf4, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xda, 0x99, 0xe1,
	0x58, 0x83, 0x04, 0x00, 0x00,
}
