<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <style type="text/css" rel="stylesheet" media="all">

    *:not(br):not(tr):not(html) {
      font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif;
      -webkit-box-sizing: border-box;
      box-sizing: border-box;
    }
    body {
      width: 100% !important;
      height: 100%;
      margin: 0;
      line-height: 1.4;
      background-color: #2c3e50;
      color: #74787E;
      -webkit-text-size-adjust: none;
    }
    a {
      color: #3869D4;
    }


    .email-wrapper {
      width: 100%;
      margin: 0;
      padding: 0;
      background-color: #2c3e50;
    }
    .email-content {
      width: 100%;
      margin: 0;
      padding: 0;
    }

    .email-masthead {
      padding: 19pt 0;
      text-align: center;
    }
    .email-masthead_logo {
      max-width: 400px;
      border: 0;
    }
    .email-masthead_name {
      font-size: 12pt;
      font-weight: bold;
      color: #2F3133;
      text-decoration: none;
      text-shadow: 0 1px 0 white;
    }
    .email-logo {
      max-height: 50px;
    }

    .email-body {
      width: 100%;
      margin: 0;
      padding: 0;
      border-top: 1px solid #EDEFF2;
      border-bottom: 1px solid #EDEFF2;
      background-color: #FFF;
    }
    .email-body_inner {
      width: 570px;
      margin: 0 auto;
      padding: 0;
    }
    .email-footer {
      width: 570px;
      margin: 0 auto;
      padding: 0;
      text-align: center;
    }
    .email-footer p {
      color: #eaeaea;
    }
    .body-action {
      width: 100%;
      margin: 23pt auto;
      padding: 0;
      text-align: center;
    }

    .body-dictionary {
      width: 100%;
      overflow: hidden;
      margin: 15pt auto 15pt;
      padding: 0;
    }
    .body-dictionary dt {
      clear: both;
      color: #000;
      font-weight: bold;
      float: left;
      width: 50%;
      padding: 0;
      margin: 0;
      margin-bottom: 0.3em;
    }
    .body-dictionary dd {
      float: left;
      width: 50%;
      padding: 0;
      margin: 0;
    }
    .body-sub {
      margin-top: 19pt;
      padding-top: 19pt;
      border-top: 1px solid #EDEFF2;
      table-layout: fixed;
    }
    .body-sub a {
      word-break: break-all;
    }
    .content-cell {
      padding: 26pt;
    }
    .align-right {
      text-align: right;
    }

    h1 {
      margin-top: 0;
      color: #2F3133;
      font-size: 14pt;
      font-weight: bold;
    }
    h2 {
      margin-top: 0;
      color: #2F3133;
      font-size: 12pt;
      font-weight: bold;
    }
    h3 {
      margin-top: 0;
      color: #2F3133;
      font-size: 11pt;
      font-weight: bold;
    }
    blockquote {
      margin: 19pt 0;
      padding-left: 10px;
      border-left: 10px solid #F0F2F4;
    }
    blockquote p {
        font-size: 1.1rem;
        color: #999;
    }
    blockquote cite {
        display: block;
        text-align: right;
        color: #666;
        font-size: 1.2rem;
    }
    cite {
      display: block;
      font-size: 0.925rem;
    }
    cite:before {
      content: "\2014 \0020";
    }
    p {
      margin-top: 0;
      color: #74787E;
      font-size: 12pt;
      line-height: 1.5em;
    }
    p.sub {
      font-size: 9pt;
    }
    p.center {
      text-align: center;
    }
    table {
      width: 100%;
    }
    th {
      padding: 0px 5px;
      padding-bottom: 8px;
      border-bottom: 1px solid #EDEFF2;
    }
    th p {
      margin: 0;
      color: #9BA2AB;
      font-size: 9pt;
    }
    td {
      padding: 10px 5px;
      color: #74787E;
      font-size: 11pt;
      line-height: 14pt;
    }
    .content {
      align: center;
      padding: 0;
    }

    .data-wrapper {
      width: 100%;
      margin: 0;
      padding: 26pt 0;
    }
    .data-table {
      width: 100%;
      margin: 0;
    }
    .data-table th {
      text-align: left;
      padding: 0px 5px;
      padding-bottom: 8px;
      border-bottom: 1px solid #EDEFF2;
    }
    .data-table th p {
      margin: 0;
      color: #9BA2AB;
      font-size: 9pt;
    }
    .data-table td {
      padding: 10px 5px;
      color: #74787E;
      font-size: 11pt;
      line-height: 14pt;
    }

    .invite-code {
      display: inline-block;
      padding-top: 15pt;
      padding-right: 27pt;
      padding-bottom: 12pt;
      padding-left: 27pt;
      border-radius: 3px;
      font-family: Consolas, monaco, monospace;
      font-size: 21pt;
      text-align: center;
      letter-spacing: 8px;
      color: #555;
      background-color: #eee;
    }

    .button {
      display: inline-block;
      width: 100%;
      background-color: #00948d;
      color: #ffffff !important;
      font-size: 11pt;
      line-height: 34pt;
      text-align: center;
      text-decoration: none;
      -webkit-text-size-adjust: none;

    }

    @media only screen and (max-width: 600px) {
      .email-body_inner,
      .email-footer {
        width: 100% !important;
      }
    }
  </style>
</head>
<body dir="ltr">
  <table class="email-wrapper" width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td class="content">
        <table class="email-content" width="100%" cellpadding="0" cellspacing="0">

          <tr>
            <td class="email-masthead">
              <a class="email-masthead_name" href="https://pydio.henleyglobal.net" target="_blank">

                  <img src="https://cdn.henleyglobal.com/themes/hgo/assets/dist/svg/logo.svg" class="email-logo" />

                </a>
            </td>
          </tr>


          <tr>
            <td class="email-body" width="100%">
              <table class="email-body_inner" align="center" width="570" cellpadding="0" cellspacing="0">

                <tr>
                  <td class="content-cell">
                    <h1>Hello gillard.de4d@litmusemail.com,</h1>
                            <p>Test message</p>

                            <p>Click to open the frontend</p>
                            <!--[if mso]>

                            <div style="margin: 23pt auto">
                              <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml"
                                xmlns:w="urn:schemas-microsoft-com:office:word"
                                href="https://pydio.henleyglobal.net"
                                style="height:36pt;v-text-anchor:middle;width:570px;background-color:#22BC66;"
                                arcsize="0%"
                                strokecolor="#22BC66" fillcolor="#22BC66"
                                >
                                <w:anchorlock/>
                                <center style="color: #FFFFFF;font-size: 11pt;text-align: center;font-family:sans-serif;font-weight:bold;">
                                  Open Cells 1
                                </center>
                              </v:roundrect>
                            </div>


                            <![endif]-->
                            <!--[if !mso]><!-- -->
                            <table class="body-action" align="center" width="100%" cellpadding="0" cellspacing="0">
                              <tr>
                                <td align="center">
                                  <div>

                                      <a href="https://pydio.henleyglobal.net" class="button" style="background-color: #22BC66; " target="_blank">
                                        Open Cells 2
                                      </a>


                                  </div>
                                </td>
                              </tr>
                            </table>
                            <![endif]-->








                            <p>H&amp;P Secure Transfer Portal File Sharing platform is used by teams to efficiently collaborate on documents.</p>




                    <p>
                      Sincerely,
                      <br />
                      H&amp;P Secure Transfer Portal
                    </p>



                        <table class="body-sub">
                          <tbody>


                                <tr>
                                  <td>
                                    <p class="sub">If the Open Cells-button is not working for you, just copy and paste the URL below into your web browser.</p>
                                    <p class="sub"><a href="https://pydio.henleyglobal.net">https://pydio.henleyglobal.net</a></p>
                                  </td>
                                </tr>


                          </tbody>
                        </table>


                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <tr>
            <td>
              <table class="email-footer" align="center" width="570" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-cell">
                    <p class="sub center">
                      © 2023 Henley &amp; Partners Holdings Ltd, All rights reserved
                    </p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
