FROM busybox:glibc

ENV CELLS_VERSION 1.0.0

ADD cmd.sh /cells/cmd.sh
ADD libdl.so.2 /cells/libdl.so.2

WORKDIR /cells

RUN wget "https://download.pydio.com/pub/cells/release/${CELLS_VERSION}/linux-amd64/cells"

RUN chmod +x /cells/cells
RUN chmod +x /cells/cmd.sh

RUN ln -s /cells/cells /bin/cells
RUN ln -s /cells/libdl.so.2 /lib64/libdl.so.2

ENV CELLS_BIND localhost:8080
ENV CELLS_EXTERNAL localhost:8080

VOLUME /root/.config

CMD ["/cells/cmd.sh"]
